# frozen_string_literal: true
# Japanese translation for openEHR-EHR-INSTRUCTION.service_request.v1
# Generated by tools/scaffold_fill.rb - fill every empty string, following glossary-ja.md.
# Human proofreading: edit work/openEHR-EHR-INSTRUCTION.service_request.v1.ja.tsv and run `make import ID=openEHR-EHR-INSTRUCTION.service_request.v1` (regenerates this file).

T = {
  # Generic request framework for a health-related service or activity to be delivered by a clinician, organisation or agency.
  ['description', '-', 'purpose'] => "医療従事者、医療機関、または事業者が提供する保健医療関連のサービスや活動を依頼するための汎用的な枠組み。",

  # Use to record a request for a health-related service or activity to be delivered by a clinician, organisation or agency.
  # 
  # This archetype has been designed as a framework that can be used as the basis for:
  # - a request from one clinician, organisation or agency to another clinician, organisation or agency for a health-related service. For example: a referral to a specialist clinician for treatment or a second clinical opinion; transfer of care to an emergency department; four hourly vital signs monitoring; and provision of home services from a municipal council; or
  # - a request for a follow up service to be scheduled for the same clinician, organisation or agency. For example: a review appointment in outpatients in 6 weeks. 
  # 
  # Clinical use cases:
  # - consider a clinician ordering a follow-up appointment in 6 weeks. 'Follow-up appointment' will be the 'Service name'. If they enter '6 weeks' as the proposed timing for the appointment in the User Interface, the clinical system will record the date six weeks from today in the 'Service due' data element.
  # - consider a clinician ordering Diabetes Education as the 'Service name'. The values for 'Reason for request' may be 'New diagnosis' and 'Prevention of ketoacidosis'. The 'Clinical indication' will be 'Diabetes Type 1', which may be linked to the Problem Diagnosis and/or Laboratory test results. If a 4 week course is required, with sessions organised at weekly intervals on 4 separate occasions, then the complex timing requires use of the CLUSTER.service_direction and associated CLUSTER.timing_nondaily archetype.
  # - consider a clinician ordering a recurring blood test, such as an INR. The complex timing for this requires use of the CLUSTER.service_direction and associated CLUSTER.timing_nondaily archetype to define each timing in a sequence of tests, such as 'daily for one week, weekly for 4 weeks, monthly for 6 months'.
  # 
  # The default assumption for this archetype is that it's a request for a single service. If a series of services are required, use the CLUSTER.service_direction archetype within the 'Complex timing' SLOT.
  # 
  # In many situations it will be possible to record the steps that occur as part of this request being carried out using the corresponding generic ACTION.service. However, there will be many occasions where the required ACTION archetype will be very specific for purpose, as the data requirements for recording provision of many health-related services will need quite unique data elements, recording patterns or pathway steps. For example: ACTION.screening or ACTION.health_education.
  ['description', '-', 'use'] => "医療従事者、医療機関、または事業者が提供する保健医療関連のサービスや活動の依頼を記録するために用いる。\n\n本archetypeは、以下のような依頼の基盤として使える枠組みとして設計されている：\n- ある医療従事者・医療機関・事業者から、別の医療従事者・医療機関・事業者に保健医療関連サービスを依頼する。例：治療またはセカンドオピニオンを求める専門医への紹介、救急部門への診療の移管、4時間ごとのバイタルサイン測定、市町村による在宅サービスの提供。\n- 同じ医療従事者・医療機関・事業者に対して、フォローアップサービスの予約を依頼する。例：6週間後の外来再診。\n\n臨床でのユースケース：\n- 医療従事者が6週間後のフォローアップ受診をオーダーする場合を考える。「フォローアップ受診」が「サービス名」になる。ユーザーインターフェースで受診の希望時期として「6週間」を入力すると、臨床システムは本日から6週間後の日付を「サービス実施予定」データエレメントに記録する。\n- 医療従事者が「サービス名」として糖尿病教育をオーダーする場合を考える。「依頼理由」の値は「新規診断」や「ケトアシドーシスの予防」となることもある。「臨床的適応」は「1型糖尿病」となり、プロブレム・診断や臨床検査結果にリンクされることもある。週1回の間隔で4回に分けたセッションからなる4週間のコースが必要な場合、その複雑なタイミングには CLUSTER.service_direction と、それに関連する CLUSTER.timing_nondaily archetypeを用いる必要がある。\n- 医療従事者が INR のような反復する血液検査をオーダーする場合を考える。この複雑なタイミングには、「1週間は毎日、4週間は毎週、6か月間は毎月」のような一連の検査の各タイミングを定義するために、CLUSTER.service_direction と、それに関連する CLUSTER.timing_nondaily archetypeを用いる必要がある。\n\n本archetypeは、単一のサービスの依頼であることを既定の前提としている。一連のサービスが必要な場合は、「複雑なタイミング」SLOT 内で CLUSTER.service_direction archetypeを用いる。\n\n多くの状況では、この依頼が実施される過程で生じる各ステップを、対応する汎用の ACTION.service を用いて記録できる。しかし、多くの保健医療関連サービスの提供を記録するには、かなり固有のデータエレメント、記録パターン、またはパスウェイのステップが必要になるため、必要な ACTION archetypeが目的に非常に特化したものになる場合も多い。例：ACTION.screening や ACTION.health_education。",

  # request | order | service | provide | referral
  ['description', '-', 'keywords'] => "依頼 | オーダー | サービス | 提供 | 紹介 | 診療依頼",

  # © openEHR Foundation, Nasjonal IKT HF
  ['description', '-', 'copyright'] => "© openEHR Foundation, Nasjonal IKT HF",

  # INSTRUCTION
  # Service request
  ['term', 'at0000', 'text'] => "サービス依頼",

  # INSTRUCTION
  # Request for a health-related service or activity to be delivered by a clinician, organisation or agency.
  ['term', 'at0000', 'description'] => "医療従事者、医療機関、または事業者が提供する保健医療関連のサービスや活動の依頼。",

  # INSTRUCTION > activities/ACTIVITY
  # Current Activity
  ['term', 'at0001', 'text'] => "現在のアクティビティ",

  # INSTRUCTION > activities/ACTIVITY
  # Current Activity.
  ['term', 'at0001', 'description'] => "現在のアクティビティ。",

  # INSTRUCTION > protocol/ITEM_TREE
  # Tree
  ['term', 'at0008', 'text'] => "Tree",

  # INSTRUCTION > protocol/ITEM_TREE
  # @ internal @
  ['term', 'at0008', 'description'] => "@ internal @",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE
  # Tree
  ['term', 'at0009', 'text'] => "Tree",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE
  # @ internal @
  ['term', 'at0009', 'description'] => "@ internal @",

  # INSTRUCTION > protocol/ITEM_TREE > items/ELEMENT
  # Requester order identifier
  ['term', 'at0010', 'text'] => "依頼者オーダー識別子",

  # INSTRUCTION > protocol/ITEM_TREE > items/ELEMENT
  # The local identifier assigned by the requesting clinical system.
  ['term', 'at0010', 'description'] => "依頼側の臨床システムが付与したローカルな識別子。",

  # INSTRUCTION > protocol/ITEM_TREE > items/ELEMENT
  # Usually equivalent to the HL7 Placer Order Identifier.
  ['term', 'at0010', 'comment'] => "通常、HL7 の Placer Order Identifier に相当する。",

  # INSTRUCTION > protocol/ITEM_TREE > items/ELEMENT
  # Receiver order identifier
  ['term', 'at0011', 'text'] => "受領者オーダー識別子",

  # INSTRUCTION > protocol/ITEM_TREE > items/ELEMENT
  # The local identifier assigned to the request by the clinician or organisation receiving the request for service.
  ['term', 'at0011', 'description'] => "サービス依頼を受領する医療従事者または医療機関が、その依頼に付与したローカルな識別子。",

  # INSTRUCTION > protocol/ITEM_TREE > items/ELEMENT
  # Usually equivalent to the HL7 Filler Order Identifier.
  ['term', 'at0011', 'comment'] => "通常、HL7 の Filler Order Identifier に相当する。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Service due
  ['term', 'at0040', 'text'] => "サービス実施予定",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # The date/time, or acceptable interval of date/time, for provision of the service.
  ['term', 'at0040', 'description'] => "サービスを提供する日時、または許容される日時の範囲。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # This data element allows for recording of the timing for a single service, either as a date and time, a date ranges or a text descriptor which can allow for 'next available. In practice, clinicians will often think in terms of ordering services as approximate timing, for example: review in 3 months, 6 months or 12 months. As clinical systems need more exact parameters to operate on, this '3 months' will usually be converted to an exact date 3 months from the date of recording and stored using this data element. If complex timing or sequences of timings are required, use the CLUSTER.service_direction archetype within the 'Complex timing' SLOT and this data element becomes redundant.
  ['term', 'at0040', 'comment'] => "このデータエレメントは、単一のサービスのタイミングを、日付と時刻、日付の範囲、または「次に空いている枠」のような表現を可能にするテキスト記述子として記録できるようにする。実際には、医療従事者はサービスのオーダーを「3か月後、6か月後、12か月後に再診」のような大まかなタイミングで考えることが多い。臨床システムは動作にもっと正確なパラメータを必要とするため、この「3か月」は通常、記録日から3か月後の正確な日付に変換され、このデータエレメントを用いて保存される。複雑なタイミングや一連のタイミングが必要な場合は、「複雑なタイミング」SLOT 内で CLUSTER.service_direction archetypeを用いる。その場合、このデータエレメントは冗長になる。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Reason for request
  ['term', 'at0062', 'text'] => "依頼理由",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # A short phrase describing the reason for the request.
  ['term', 'at0062', 'description'] => "依頼の理由を述べる短い語句。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Coding of the 'Reason for request' with a coding system is desirable, if available. This data element allows multiple occurrences to enable the user to record a multiple responses, if required. For example: 'manage diabetes complications'.
  ['term', 'at0062', 'comment'] => "利用可能であれば、「依頼理由」はコード体系によりコード化することが望ましい。このデータエレメントは複数回の出現を許容し、必要に応じて利用者が複数の回答を記録できる。例：「糖尿病合併症の管理」。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Reason description
  ['term', 'at0064', 'text'] => "理由の説明",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Narrative description about the reason for request.
  ['term', 'at0064', 'description'] => "依頼理由に関する叙述的な説明。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # For example: 'The patient's diabetes has recently become more difficult to stabilise and renal function is deteriorating'.
  ['term', 'at0064', 'comment'] => "例：「患者の糖尿病は最近コントロールが難しくなっており、腎機能も悪化している」。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Intent
  ['term', 'at0065', 'text'] => "意図",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Description of the intent for the request.
  ['term', 'at0065', 'description'] => "依頼の意図の説明。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # For example: a referral to a specialist may have the intent of the specialist taking over responsibility for care of the patient, or it may be to provide a second opinion on treatment options. Coding of the 'Intent' with a coding system is desirable, if available. This data element allows multiple occurrences to enable the user to record a multiple responses, if required.
  ['term', 'at0065', 'comment'] => "例：専門医への紹介には、専門医が患者の診療責任を引き継ぐという意図もあれば、治療選択肢についてセカンドオピニオンを求めるという意図もある。利用可能であれば、「意図」はコード体系によりコード化することが望ましい。このデータエレメントは複数回の出現を許容し、必要に応じて利用者が複数の回答を記録できる。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Urgency
  ['term', 'at0068', 'text'] => "緊急度",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Urgency of the request for service.
  ['term', 'at0068', 'description'] => "サービス依頼の緊急度。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Specific definitions of emergency and urgent will vary between clinical contexts, clinical systems and the nature of the request itself, so have not been defined in this archetype. If explicit timing is required then the Service period should be clearly stated.
  ['term', 'at0068', 'comment'] => "「緊急」と「至急」の具体的な定義は、臨床の文脈、臨床システム、依頼そのものの性質によって異なるため、本archetypeでは定義していない。明示的なタイミングが必要な場合は、サービス期間を明確に記載すること。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Supplementary information
  ['term', 'at0076', 'text'] => "補足情報",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Supplementary information will be following request.
  ['term', 'at0076', 'description'] => "補足情報が依頼に続いて送付される。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Record as TRUE if additional information has been identified and will be forwarded when available. For example: pending test results.
  ['term', 'at0076', 'comment'] => "追加の情報があることが判明しており、利用可能になり次第送付する場合に TRUE として記録する。例：結果待ちの検査。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Information description
  ['term', 'at0078', 'text'] => "情報の説明",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Description of the supplementary information.
  ['term', 'at0078', 'description'] => "補足情報の説明。",

  # INSTRUCTION > protocol/ITEM_TREE > items/CLUSTER
  # Extension
  ['term', 'at0112', 'text'] => "Extension",

  # INSTRUCTION > protocol/ITEM_TREE > items/CLUSTER
  # Additional information required to capture local content or to align with other reference models/formalisms.
  ['term', 'at0112', 'description'] => "ローカルコンテンツを捕捉するため、あるいは他の参照モデルや形式手法と整合させるために必要な追加情報。",

  # INSTRUCTION > protocol/ITEM_TREE > items/CLUSTER
  # For example: local information requirements or additional metadata to align with FHIR or CIMI equivalents.
  ['term', 'at0112', 'comment'] => "例：ローカルな情報要件や、FHIR または CIMI の相当するものに適合させるための追加メタデータ。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # Patient requirements
  ['term', 'at0116', 'text'] => "患者の必要事項",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # Language, transport or other personal requirements to support the patient's attendance or participation in provision of the service.
  ['term', 'at0116', 'description'] => "患者がサービスの提供に出向く、または参加するのを支えるための、言語、移動手段、その他の個人的な必要事項。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Service name
  ['term', 'at0121', 'text'] => "サービス名",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # The name of the single service or activity requested.
  ['term', 'at0121', 'description'] => "依頼する単一のサービスまたは活動の名称。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Coding of the 'Service name' with a coding system is desirable, if available. For example: 'referral' to an endocrinologist for diabetes management.
  ['term', 'at0121', 'comment'] => "利用可能であれば、「サービス名」はコード体系によりコード化することが望ましい。例：糖尿病管理のための内分泌専門医への「紹介」。",

  # INSTRUCTION > protocol/ITEM_TREE > items/ELEMENT
  # Request status
  ['term', 'at0127', 'text'] => "依頼状態",

  # INSTRUCTION > protocol/ITEM_TREE > items/ELEMENT
  # The status of the request for service as indicated by the requester.
  ['term', 'at0127', 'description'] => "依頼者が示す、サービス依頼の状態。",

  # INSTRUCTION > protocol/ITEM_TREE > items/ELEMENT
  # Status is used to denote whether this is the initial request, or a follow-up request to change or provide supplementary information. Coding with a terminology is preferred, where possible.
  ['term', 'at0127', 'comment'] => "状態は、これが最初の依頼なのか、変更または補足情報の提供のためのフォローアップの依頼なのかを示すために用いる。可能であれば用語集によるコード化が望ましい。",

  # INSTRUCTION > protocol/ITEM_TREE > items/CLUSTER
  # Distribution list
  ['term', 'at0128', 'text'] => "配布先リスト",

  # INSTRUCTION > protocol/ITEM_TREE > items/CLUSTER
  # Details of additional clinicians, organisations or agencies who require copies of any communication.
  ['term', 'at0128', 'description'] => "通信の写しを必要とする追加の医療従事者、医療機関、または事業者に関する詳細情報。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # Specific details
  ['term', 'at0132', 'text'] => "詳細記録",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # Additional detail about the service requested.
  ['term', 'at0132', 'description'] => "依頼するサービスに関する追加の詳細情報。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # For example: Specimen details for a laboratory test request, or anatomical location for a procedure request.
  ['term', 'at0132', 'comment'] => "例：臨床検査依頼における検体の詳細、処置依頼における解剖学的部位。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Description
  ['term', 'at0135', 'text'] => "説明",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Narrative description about the service requested.
  ['term', 'at0135', 'description'] => "依頼するサービスに関する叙述的な説明。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # This data point should be used to describe the named service in more detail, including how it should be delivered, patient concerns and issues that might be encountered in delivering the service.
  ['term', 'at0135', 'comment'] => "このデータ項目は、名称で示したサービスをより詳しく説明するために用いる。提供の方法、患者の懸念、サービス提供の際に生じる可能性のある問題などを含む。",

  # Emergency
  ['term', 'at0136', 'text'] => "緊急",

  # The request requires immediate attention.
  ['term', 'at0136', 'description'] => "依頼には即時の対応が必要である。",

  # Urgent
  ['term', 'at0137', 'text'] => "至急",

  # The request requires prioritised attention.
  ['term', 'at0137', 'description'] => "依頼には優先的な対応が必要である。",

  # Routine
  ['term', 'at0138', 'text'] => "通常",

  # The request does not require prioritised scheduling.
  ['term', 'at0138', 'description'] => "依頼には優先的な予定調整は必要ない。",

  # INSTRUCTION > protocol/ITEM_TREE > items/CLUSTER
  # Requester
  ['term', 'at0141', 'text'] => "依頼者",

  # INSTRUCTION > protocol/ITEM_TREE > items/CLUSTER
  # Details about the clinician or organisation requesting the service.
  ['term', 'at0141', 'description'] => "サービスを依頼する医療従事者または医療機関に関する詳細情報。",

  # INSTRUCTION > protocol/ITEM_TREE > items/CLUSTER
  # Receiver
  ['term', 'at0142', 'text'] => "受領者",

  # INSTRUCTION > protocol/ITEM_TREE > items/CLUSTER
  # Details about the clinician or organisation receiving the request for service.
  ['term', 'at0142', 'description'] => "サービス依頼を受領する医療従事者または医療機関に関する詳細情報。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Service period expiry
  ['term', 'at0144', 'text'] => "サービス期間の終了",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # The date/time that marks the conclusion of the clinically valid period of time for delivery of this service.
  ['term', 'at0144', 'description'] => "このサービスを提供するための臨床的に有効な期間の終了を示す日時。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # This date/time is the equivalent to the latest possible date for service delivery or to the date of expiry for this request. For example: a service may be required to be completed before another event, such as scheduled surgery.
  ['term', 'at0144', 'comment'] => "この日時は、サービス提供が可能な最も遅い日付、またはこの依頼の有効期限に相当する。例：予定手術など他のイベントの前にサービスを完了しなければならない場合がある。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Service period start
  ['term', 'at0145', 'text'] => "サービス期間の開始",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # The date/time that marks the beginning of the valid period of time for delivery of this service.
  ['term', 'at0145', 'description'] => "このサービスを提供するための有効な期間の開始を示す日時。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # This date/time is the equivalent to the earliest possible date for service delivery. For example: sometimes a certain amount of time must pass before a service can be performed, for example some procedures can only be performed once the patient has stopped taking medications for a specific amount of time.
  ['term', 'at0145', 'comment'] => "この日時は、サービス提供が可能な最も早い日付に相当する。例：サービスを実施する前に一定の期間が経過していなければならないことがある。例えば、ある種の処置は患者が薬剤の服用を一定期間中止した後でなければ実施できない。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Indefinite?
  ['term', 'at0147', 'text'] => "無期限？",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # The valid period for this request is open ended and has no date of expiry.
  ['term', 'at0147', 'description'] => "この依頼の有効期間には終わりがなく、有効期限がない。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Record as TRUE to record explicity that the request has no expiry date. For example: commonly required for a referral to a specialist for long-term or lifelong care.
  ['term', 'at0147', 'comment'] => "依頼に有効期限がないことを明示的に記録するには TRUE として記録する。例：長期または生涯にわたるケアのための専門医への紹介で一般に必要となる。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Service type
  ['term', 'at0148', 'text'] => "サービス種別",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Category of service requested.
  ['term', 'at0148', 'description'] => "依頼するサービスの区分。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Coding of the 'Service type' with a coding system is desirable, if available. If the 'Service name' was coded, it is possible for this data point to be derived from the code. For example: biochemistry or microbiology laboratory, ultrasound or CT imaging.
  ['term', 'at0148', 'comment'] => "利用可能であれば、「サービス種別」はコード体系によりコード化することが望ましい。「サービス名」がコード化されていれば、このデータ項目をそのコードから導出できる場合がある。例：生化学または微生物学の検査室、超音波または CT の画像検査。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # Supporting information
  ['term', 'at0149', 'text'] => "参考資料",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # Digital document, image, video or diagram supplied as additional information to support or inform the request.
  ['term', 'at0149', 'description'] => "依頼を裏付け、または補足するための追加情報として提供される電子文書、画像、動画、または図。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Comment
  ['term', 'at0150', 'text'] => "コメント",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Additional narrative about the service request not captured in other fields.
  ['term', 'at0150', 'description'] => "他の項目には収まらないサービス依頼についての追加の記述。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # Complex timing
  ['term', 'at0151', 'text'] => "複雑なタイミング",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # Details about a complex service request requiring a sequence of timings.
  ['term', 'at0151', 'description'] => "一連のタイミングを必要とする複雑なサービス依頼に関する詳細情報。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # For example: 'hourly vital signs observations for 4 hours, then 4 hourly for 20 hours' or 'every third Wednesday for 3 visits'.
  ['term', 'at0151', 'comment'] => "例：「4時間は1時間ごと、その後20時間は4時間ごとのバイタルサイン観察」や「3週間ごとの水曜日に3回の来院」。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Clinical indication
  ['term', 'at0152', 'text'] => "臨床的適応",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # The clinical reason for the ordered service.
  ['term', 'at0152', 'description'] => "オーダーしたサービスの臨床的な理由。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Coding of the clinical indication with a terminology is preferred, where possible. This data element allows multiple occurrences. For example: 'Angina' or 'Type 1 Diabetes mellitus'.
  ['term', 'at0152', 'comment'] => "可能であれば、臨床的適応は用語集によるコード化が望ましい。このデータエレメントは複数回の出現を許容する。例：「狭心症」や「1型糖尿病」。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Order detail
  ['term', 'at0153', 'text'] => "オーダー詳細",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Additional details and instructions about how the services are to be delivered.
  ['term', 'at0153', 'description'] => "サービスをどのように提供すべきかに関する追加の詳細情報と指示。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Coding of the order detail with a terminology is preferred, where possible. This data element allows multiple occurrences. 
  ['term', 'at0153', 'comment'] => "可能であれば、オーダー詳細は用語集によるコード化が望ましい。このデータエレメントは複数回の出現を許容する。",

}.freeze

# note 列に残すメモ。迷った訳語には '要確認: ...' を付ける。
NOTES = {
  ['term', 'at0000', 'text'] => "要確認: 「サービス依頼」（他候補: 診療サービス依頼／サービスリクエスト）。request＝依頼、service＝サービスの規則に従う",
  ['term', 'at0001', 'text'] => "RM の ACTIVITY を指す内部的な名称。「現在のアクティビティ」",
  ['term', 'at0076', 'text'] => "Boolean 項目。\"Supplementary information\"→「補足情報」、at0149 \"Supporting information\"→「参考資料」と区別",
  ['term', 'at0116', 'text'] => "要確認: \"Patient requirements\"→「患者の必要事項」（言語・移動手段など）",
  ['term', 'at0142', 'text'] => "Receiver＝受領者（request.v1 の本文では \"receiving healthcare provider\" を「受け手となる医療従事者」としている）",
  ['term', 'at0152', 'text'] => "Clinical indication＝臨床的適応（FHIR reasonCode に相当）",
}.freeze

src, dst = ARGV
lines = File.readlines(src, chomp: true)
out = [lines.shift]
lines.each do |l|
  c = l.split("\t", -1)
  key = c[1..3]
  c[6] = T.fetch(key).gsub("\n", '\n')
  c[7] = NOTES[key] || ''
  out << c.join("\t")
end
File.write(dst, out.join("\n") + "\n")
