# frozen_string_literal: true
# Japanese translation for openEHR-EHR-CLUSTER.media_file.v1
# Generated by tools/scaffold_fill.rb - fill every empty string, following glossary-ja.md.
# Human proofreading: edit work/openEHR-EHR-CLUSTER.media_file.v1.ja.tsv and run `make import ID=openEHR-EHR-CLUSTER.media_file.v1` (regenerates this file).

T = {
  # To record a media file that is acquired or used as part of the healthcare process, and details about associated metadata.
  ['description', '-', 'purpose'] => "医療プロセスの一環として取得または使用するメディアファイルと、関連するメタデータの詳細情報を記録するため。",

  # Use to record a media file that is acquired or used as part of the healthcare process, and details about associated metadata.
  # 
  # The intent of this archetype is only to hold the media file and the metadata describing its capture. This archetype will be nested within another archetype, usually an OBSERVATION or ACTION that will hold the context and circumstances related to the capture of the media file. For example, details about the modality, view or aspect of a radiographic image and DICOM details will be captured within the OBSERVATION.imaging_exam_result archetype. 
  # 
  # Examples include, but are not limited to:
  # - A photo of an injury;
  # - A diagram of the location of a specific clinical finding;
  # - A radiological image;
  # - An audio or video recording of an interview;
  # - Scanned pathology slide;
  # - Data output from a clinical device, such as an ECG machine; or
  # - A scanned image of paper documentation or hand-written clinical notes.
  # 
  # The 'Content' data element allows for the media file to be captured and stored within the health record using the Multimedia data type. The Multimedia data type has many RM attributes such as the size of file and URI to an external source. See https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_multimedia_class.
  # 
  # If more than one media file has been captured, such as 'before' and 'after' images of a wound, use a separate instance of this archetype to represent each media file.
  # 
  # If a series of media files is represented as a single item, such as a CT scan, one instance of this archetype can be used to represent a URI path to the group.
  ['description', '-', 'use'] => "医療プロセスの一環として取得または使用するメディアファイルと、関連するメタデータの詳細情報を記録するために用いる。\n\n本archetypeは、メディアファイルと、その取得に関するメタデータのみを保持することを意図している。本archetypeは他のarchetype（通常は OBSERVATION または ACTION）の中に入れ子にして用い、メディアファイルの取得に関する背景や状況はその親archetypeに記録する。例：放射線画像の撮影法、撮影方向、観察方向の詳細情報や DICOM の詳細情報は、OBSERVATION.imaging_exam_result archetypeに記録する。 \n\n以下のような使用例があるが、これらに限らない。\n- 外傷の写真を記録する。\n- 特定の臨床所見の位置を示す図を記録する。\n- 放射線画像を記録する。\n- 面談の録音や録画を記録する。\n- 病理標本スライドのスキャン画像を記録する。\n- 心電計などの医療機器から出力されたデータを記録する。\n- 紙の文書や手書きの診療記録のスキャン画像を記録する。\n\n「コンテンツ」データエレメントでは、Multimedia データ型を用いてメディアファイルを健康記録に取り込み、保存できる。Multimedia データ型には、ファイルサイズや外部の参照先を示す URI など、多くの参照モデルの属性がある。https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_multimedia_class を参照。\n\n創傷の「前」と「後」の画像など、複数のメディアファイルを取得した場合は、各ファイルを本archetypeの別々のインスタンスで表す。\n\nCT画像のように一連のメディアファイルを一つの項目として表す場合は、本archetypeの一つのインスタンスを用いて、そのファイル群への URI パスを記録できる。",

  # Not to be used to represent information, instructional or educational material supplied to an individual, or their carer, for example patient education leaflets. Use the CLUSTER.information_resource for this purpose.
  # 
  # Not to be used to record a reference to a knowledge base - use CLUSTER.knowledge_base_reference for this purpose.
  ['description', '-', 'misuse'] => "患者教育用のリーフレットなど、個人やその介護者に提供する情報資料、指導資料、教育資料の記録には、本archetypeではなく CLUSTER.information_resource を用いる。\n\n知識ベースへの参照の記録には、本archetypeではなく CLUSTER.knowledge_base_reference を用いる。",

  # image | audio | text | video | application | file | multimedia | audio | DICOM | digital | document | photo | voice
  ['description', '-', 'keywords'] => "画像 | 音声 | テキスト | 動画 | アプリケーション | ファイル | マルチメディア | 音声 | DICOM | デジタル | 文書 | 写真 | 録音 | メディアファイル",

  # © openEHR Foundation
  ['description', '-', 'copyright'] => "© openEHR Foundation",

  # CLUSTER
  # Media file
  ['term', 'at0000', 'text'] => "メディアファイル",

  # CLUSTER
  # A media file that is acquired or used as part of the healthcare process, and associated metadata.
  ['term', 'at0000', 'description'] => "医療プロセスの一環として取得または使用するメディアファイルと、関連するメタデータ。",

  # CLUSTER > items/ELEMENT
  # Content
  ['term', 'at0001', 'text'] => "コンテンツ",

  # CLUSTER > items/ELEMENT
  # Digital representation of the media file.
  ['term', 'at0001', 'description'] => "メディアファイルのデジタル表現。",

  # CLUSTER > items/ELEMENT
  # If the file is stored locally, the actual content will be captured and stored using the Multimedia data type. For example: RTF or PDF for a document; JPG for an image; MP4 for a video; or WAV for an audio file. Full list of available media types: https://specifications.openehr.org/releases/TERM/latest/SupportTerminology.html#_media_types.  If the file is stored at a location outside of the health record, the detailed path to the file is captured using the URI attribute in the Multimedia data type. The Multimedia data type has many RM attributes such as the size of file and URI to an external source - see https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_multimedia_class.
  ['term', 'at0001', 'comment'] => "ファイルをローカルに保存する場合は、Multimedia データ型を用いてコンテンツの実体を取り込み、保存する。例：文書には RTF または PDF、画像には JPG、動画には MP4、音声ファイルには WAV を用いる。利用可能なメディア種別の一覧は https://specifications.openehr.org/releases/TERM/latest/SupportTerminology.html#_media_types を参照。  ファイルを健康記録の外部に保存する場合は、Multimedia データ型の URI 属性を用いて、ファイルへの詳細なパスを記録する。Multimedia データ型には、ファイルサイズや外部の参照先を示す URI など、多くの参照モデルの属性がある。https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_multimedia_class を参照。",

  # CLUSTER > items/ELEMENT
  # Content name
  ['term', 'at0002', 'text'] => "コンテンツ名",

  # CLUSTER > items/ELEMENT
  # Descriptive name or title for the media file.
  ['term', 'at0002', 'description'] => "メディアファイルの内容を表す名称またはタイトル。",

  # CLUSTER > items/ELEMENT
  # A description of the content of the media file. Use an agreed standardised naming convention, if available. For example: \"Right hand burn #1\" or \"Cardiology video consultation on May 2\".
  ['term', 'at0002', 'comment'] => "メディアファイルの内容を説明する。合意された標準的な命名規則があれば、それを用いること。例：「右手の熱傷 #1」または「5月2日の循環器科のビデオ診察」。",

  # CLUSTER > items/ELEMENT
  # Created
  ['term', 'at0004', 'text'] => "作成日時",

  # CLUSTER > items/ELEMENT
  # The date/time, partial date or period when the media file was generated or authored.
  ['term', 'at0004', 'description'] => "メディアファイルを生成または作成した日時、部分的な日付、または期間。",

  # CLUSTER > items/ELEMENT
  # Description
  ['term', 'at0005', 'text'] => "説明",

  # CLUSTER > items/ELEMENT
  # Narrative description about the media file.
  ['term', 'at0005', 'description'] => "メディアファイルに関する記述。",

  # CLUSTER > items/ELEMENT
  # Comment
  ['term', 'at0007', 'text'] => "コメント",

  # CLUSTER > items/ELEMENT
  # Additional narrative about the media file not captured in other fields.
  ['term', 'at0007', 'description'] => "他の項目には収まらないメディアファイルについての追加の記述。",

  # CLUSTER > items/ELEMENT
  # Identifier
  ['term', 'at0010', 'text'] => "識別子",

  # CLUSTER > items/ELEMENT
  # Unique ID for the media file.
  ['term', 'at0010', 'description'] => "メディアファイルの一意の識別子。",

  # CLUSTER > items/CLUSTER
  # Source device
  ['term', 'at0011', 'text'] => "作成機器",

  # CLUSTER > items/CLUSTER
  # Details about the device used to generate or author the media file.
  ['term', 'at0011', 'description'] => "メディアファイルの生成または作成に用いた機器に関する詳細情報。",

  # CLUSTER > items/CLUSTER
  # For example: the camera used to capture an image.
  ['term', 'at0011', 'comment'] => "例：画像の撮影に用いたカメラ。",

  # CLUSTER > items/CLUSTER
  # Creator
  ['term', 'at0012', 'text'] => "作成者",

  # CLUSTER > items/CLUSTER
  # Details about the individual or organisation who generated or authored the media file.
  ['term', 'at0012', 'description'] => "メディアファイルを生成または作成した個人や組織に関する詳細情報。",

  # CLUSTER > items/CLUSTER
  # Additional details
  ['term', 'at0013', 'text'] => "追加の詳細情報",

  # CLUSTER > items/CLUSTER
  # Additional structured details about the media file.
  ['term', 'at0013', 'description'] => "メディアファイルに関する構造化された追加の詳細情報。",

}.freeze

# note 列に残すメモ。迷った訳語には '要確認: ...' を付ける。
NOTES = {
  ['description', '-', 'purpose'] => "要確認: メタデータ（他候補: 付帯情報）既存の「追加メタデータ」に合わせた。",
  ['description', '-', 'use'] => "要確認: 撮影法 / 撮影方向 / 観察方向（他候補: モダリティ / 撮影像 / 側面）modality / view / aspect を取得方法と方向に分けた。要確認: 病理標本スライドのスキャン画像（他候補: スキャンした病理標本）デジタル画像を保存する文脈に合わせた。要確認: 医療機器 / 心電計（他候補: 臨床機器 / 心電図装置）機器を表す簡潔な語を採用した。要確認: 放射線画像 / 臨床所見（他候補: 放射線診断画像 / 診療所見）原文の範囲を限定しない訳を採用した。要確認: 創傷（他候補: 傷）医療文書の語として採用した。",
  ['description', '-', 'misuse'] => "要確認: 情報資料 / 知識ベースへの参照（他候補: 情報資源 / ナレッジベース参照）個人に提供する資料と知識ベースの参照を区別した。参照先のarchetype名は英字のまま保持した。",
  ['description', '-', 'keywords'] => "要確認: 画像 / 音声 / テキスト / 動画 / アプリケーション / ファイル / マルチメディア / デジタル / 文書 / 声（他候補: video＝映像、voice＝音声）日本語検索語として採用し、audio と voice の対応を保持した。",
  ['term', 'at0001', 'text'] => "要確認: コンテンツ（他候補: 内容）ファイルの実体を格納する項目であることを示す。",
  ['term', 'at0002', 'text'] => "要確認: コンテンツ名（他候補: 内容名）Content＝コンテンツと対応させた。",
  ['term', 'at0002', 'comment'] => "要確認: 熱傷 / ビデオ診察（他候補: やけど / オンライン診察）医療文書の語と、映像を用いる診察という原文の具体性を優先した。",
  ['term', 'at0004', 'text'] => "要確認: 作成日時（他候補: 作成時期）画面ラベルとして簡潔にし、部分的な日付や期間も含むことを description に明記した。",
  ['term', 'at0011', 'text'] => "要確認: 作成機器（他候補: 取得元機器）ファイルの生成または作成に用いた機器という description に合わせた。",
  ['term', 'at0012', 'text'] => "要確認: 作成者（他候補: 制作者）生成と著作の両方を含み、個人にも組織にも使える語を採用した。",
}.freeze

src, dst = ARGV
lines = File.readlines(src, chomp: true)
out = [lines.shift]
lines.each do |l|
  c = l.split("\t", -1)
  key = c[1..3]
  c[6] = T.fetch(key).gsub("\n", '\n')
  c[7] = NOTES[key] || ''
  out << c.join("\t")
end
File.write(dst, out.join("\n") + "\n")
