# frozen_string_literal: true
# Japanese translation for openEHR-EHR-CLUSTER.person.v1
# Generated by tools/scaffold_fill.rb - fill every empty string, following glossary-ja.md.
# Human proofreading: edit work/openEHR-EHR-CLUSTER.person.v1.ja.tsv and run `make import ID=openEHR-EHR-CLUSTER.person.v1` (regenerates this file).

T = {
  # To record details about a person as they are known or understood in the course of clinical documentation.
  ['description', '-', 'purpose'] => "臨床記録の作成に際して取得した、その人に関する詳細情報を記録するため。",

  # Use to record details of a person as they are known or understood in the course of clinical documentation, often ad hoc or when it is not appropriate or possible to use a formal demographic register or index. Examples include:
  # - the copyholder of an advanced care record, using the 'Copyholder' SLOT within the EVALUATION.advance_care_directive archetype;
  # - the role and contact details of a named contact person within an organisation, using the 'Contact person' SLOT within the CLUSTER.organisation archetype;
  # - details about a relative in a family history record, using the 'Family member details' SLOT within the openEHR-EHR-EVALUATION.family_history archetype; 
  # - the name of the person who collected a laboratory specimen from a patient, using the 'Specimen collector details' within the CLUSTER.specimen archetype; or
  # - a witness to a fall or accident, using the 'Witness' SLOT within the CLUSTER.health_event archetype.
  # 
  # In most simple clinical recording use cases, the unstructured 'Name' element within the CLUSTER.person archetype will be sufficient to record the name of a person as part of a health record. However, in circumstances where a structured name is necessary or desirable for clinical recording purposes, nest this archetype within the 'Structured name' SLOT in CLUSTER.person archetype. If the CLUSTER.structured_name archetype is nested within the 'Structured name' SLOT, any or all of the data elements can be combined together as a text string and represented in the 'Name' element, as long as they are consistent.
  # 
  # This archetype could also be used as a proxy for formal demographic data when reviewing a template with domain experts - for example, an assessment where reviewers would expect to see a person's details at the top of the assessment form.
  ['description', '-', 'use'] => "臨床記録の作成に際して取得した、その人に関する詳細情報を記録するために用いる。正式な登録簿や公式の一覧によらずに知り得た情報をその場で記録する場合や、正式な登録簿や一覧の利用が適切でない、または利用できない場合を主に想定している。以下のような使用例がある。\n- EVALUATION.advance_care_directive archetypeの「写し保有者」SLOTを用いて、事前ケア記録の写しを保有する人の情報を記録する。\n- CLUSTER.organisation archetypeの「連絡担当者」SLOTを用いて、組織内の特定の連絡担当者の役割と連絡先を記録する。\n- openEHR-EHR-EVALUATION.family_history archetypeの「家族構成員の詳細」SLOTを用いて、家族歴に登場する親族の詳細情報を記録する。 \n- CLUSTER.specimen archetypeの「検体採取者の詳細」を用いて、患者から検査用の検体を採取した人の氏名を記録する。\n- CLUSTER.health_event archetypeの「目撃者」SLOTを用いて、転倒や事故の目撃者の情報を記録する。\n\n臨床記録に人の氏名を記録するだけであれば、多くの場合、CLUSTER.person archetypeの非構造化の「氏名」要素で十分である。ただし、臨床記録の目的上、氏名を構造化して記録することが必要または望ましい場合は、CLUSTER.person archetypeの「構造化された氏名」SLOTにCLUSTER.structured_name archetypeを組み込む。この場合、各データエレメントの一部またはすべてを一つの文字列にまとめ、「氏名」要素に表示することもできる。ただし、構造化された氏名と「氏名」要素の内容が整合している必要がある。\n\n本archetypeは、対象領域の専門家とテンプレートをレビューする際に、正式なデモグラフィックデータの代用として使用することもできる。例えば、評価票の冒頭にその人の詳細情報が表示されることをレビュー担当者が想定している場合に、その情報を示すために用いる。",

  # Not to be used to represent or replace formal identification management or for the purposes of maintaining an official demographic register or index. Use a formal Master Patient Index or Health Provider Index for this purpose, or archetypes based on the openEHR Demographic Information Model.
  # 
  # Not to be used to represent the subject of care, participants or author of the record and similar data elements that should be represented formally in the health record using the Reference Model attributes.
  # 
  # Not to be used to record the date of birth of an individual - use the 'Date of birth' data element within the EVALUATION.birth_summary for this purpose
  # 
  # Not to be used to record biometric detail or biomarkers about an individual - use a specific ENTRY archetype for this purpose.
  ['description', '-', 'misuse'] => "正式な個人識別情報の管理やその代替、または公式の登録簿や一覧の維持・管理に用いてはならない。これらの目的には、正式な患者マスターインデックス（MPI）や「医療従事者名簿（Health Provider Index）」、またはopenEHRデモグラフィック情報モデルに基づくarchetypeを用いること。\n\nケア対象者、ケアへの参加者、記録の作成者など、参照モデルの属性を用いて健康記録に正式に記録すべき情報を、本archetypeで記録してはならない。\n\n個人の生年月日の記録に用いてはならない。生年月日の記録には、EVALUATION.birth_summaryの「生年月日」データエレメントを用いること。\n\n個人の生体情報やバイオマーカーの記録に用いてはならない。これらの記録には、それぞれの情報に対応したENTRY archetypeを用いること。",

  # provider, carer, staff, healthcare professional, relative, next-of-kin, practitioner, witness, friend, neighbour, child, family, sibling, parent, individual
  ['description', '-', 'keywords'] => "医療提供者 | 介護者 | 職員 | 医療従事者 | 親族 | 近親者 | 医師 | 目撃者 | 友人 | 隣人 | 子 | 家族 | きょうだい | 同胞 | 親 | 個人 | 人 | 氏名 | 連絡先",

  # © openEHR Foundation
  ['description', '-', 'copyright'] => "© openEHR Foundation",

  # CLUSTER
  # Person
  ['term', 'at0000', 'text'] => "人",

  # CLUSTER
  # An individual human being.
  ['term', 'at0000', 'description'] => "一個人。",

  # CLUSTER > items/ELEMENT
  # Name
  ['term', 'at0001', 'text'] => "氏名",

  # CLUSTER > items/ELEMENT
  # The unstructured name for the individual.
  ['term', 'at0001', 'description'] => "個人の氏名（非構造情報）。",

  # CLUSTER > items/ELEMENT
  # The content of this data element may be derived from one or more components from CLUSTER.structured_name combined together as a text string. For example: 'John Markham', 'Professor Sir John Markham', 'John Markham Jnr MP'.
  ['term', 'at0001', 'comment'] => "このデータエレメントの内容は、CLUSTER.structured_name の1つ以上の構成要素をテキスト文字列として結合して導いてもよい。例：「John Markham」、「Professor Sir John Markham」、「John Markham Jnr MP」。",

  # CLUSTER > items/CLUSTER
  # Structured name
  ['term', 'at0002', 'text'] => "構造化された氏名",

  # CLUSTER > items/CLUSTER
  # Alternative representation of an individual's complete name by separation into discrete, structured components.
  ['term', 'at0002', 'description'] => "個人の氏名全体を、姓・名などの独立した構成要素に分けて構造化した表現。非構造情報としての氏名に代わる表現として用いる。",

  # CLUSTER > items/CLUSTER
  # Any or all of the structured name elements can be combined together as a text string and represented in the 'Name' data element in this archetype.
  ['term', 'at0002', 'comment'] => "構造化された氏名の要素の一部またはすべてを一つの文字列にまとめ、本archetypeの「氏名」データエレメントに記録することができる。",

  # CLUSTER > items/ELEMENT
  # Identifier
  ['term', 'at0003', 'text'] => "識別子",

  # CLUSTER > items/ELEMENT
  # Identifier associated with the individual.
  ['term', 'at0003', 'description'] => "個人に関連付けられた識別子。",

  # CLUSTER > items/ELEMENT
  # Occurrences for this data element is set to 0..* to allow for more than one Identifier to be recorded. Note that the DV_IDENTIFIER data type contains multiple subcomponents for recording the ID value, type, issuer and assigned. For example - social security number; driver's license; or passport number.
  ['term', 'at0003', 'comment'] => "このデータエレメントの出現回数は 0..* に設定されており、複数の識別子を記録できる。DV_IDENTIFIER データ型には、ID の値、種類、発行者、割り当て先を記録する複数の下位要素がある点に注意。例：社会保障番号・運転免許証・パスポート番号。",

  # CLUSTER > items/ELEMENT
  # Role
  ['term', 'at0004', 'text'] => "役割",

  # CLUSTER > items/ELEMENT
  # The relationship or role of the individual to the subject of the health record.
  ['term', 'at0004', 'description'] => "健康記録の対象者に対する個人の関係または役割。",

  # CLUSTER > items/ELEMENT
  # For example - the copyholder of an advance care record; contact person in an organisation; relative in a family history entry; specimen collector; or witness to a fall or accident. If the individual being described using this archetype is the subject of the health record, then this data element is redundant.
  ['term', 'at0004', 'comment'] => "例：事前ケア記録の写し保有者、組織の連絡担当者、家族歴の項目における親族、検体採取者、または転倒や事故の目撃者。本archetypeで記述する人が健康記録の対象者自身である場合、このデータエレメントは冗長になる。",

  # CLUSTER > items/CLUSTER
  # Address
  ['term', 'at0005', 'text'] => "住所",

  # CLUSTER > items/CLUSTER
  # Details about an address for the individual.
  ['term', 'at0005', 'description'] => "個人の詳細な住所。",

  # CLUSTER > items/CLUSTER
  # Electronic communication
  ['term', 'at0006', 'text'] => "電子的な連絡先",

  # CLUSTER > items/CLUSTER
  # Details about one or more types of electronic communication for the individual.
  ['term', 'at0006', 'description'] => "個人の電子的な連絡先（1種類以上）の詳細情報。",

  # CLUSTER > items/CLUSTER
  # Organisation
  ['term', 'at0007', 'text'] => "組織",

  # CLUSTER > items/CLUSTER
  # Details about the organisational context for the individual.
  ['term', 'at0007', 'description'] => "個人の所属など、組織との関わりに関する詳細情報。",

  # CLUSTER > items/CLUSTER
  # For example: identifying the business or community organisation associated with the 'Role' of the individual.
  ['term', 'at0007', 'comment'] => "例：個人の「役割」に関連する企業や地域団体がどこなのかを示す。",

  # CLUSTER > items/CLUSTER
  # Additional details
  ['term', 'at0008', 'text'] => "追加の詳細情報",

  # CLUSTER > items/CLUSTER
  # Additional details about the individual.
  ['term', 'at0008', 'description'] => "個人に関する追加の詳細情報。",

  # CLUSTER > items/CLUSTER
  # Photo
  ['term', 'at0009', 'text'] => "写真",

  # CLUSTER > items/CLUSTER
  # Photograph of the individual.
  ['term', 'at0009', 'description'] => "個人の写真。",

  # CLUSTER > items/ELEMENT
  # Comment
  ['term', 'at0010', 'text'] => "コメント",

  # CLUSTER > items/ELEMENT
  # Additional narrative about the individual not captured in other fields.
  ['term', 'at0010', 'description'] => "他の項目には収まらない個人についての追加の記述。",

  # CLUSTER > items/ELEMENT
  # Label
  ['term', 'at0011', 'text'] => "ラベル（識別用の説明）",

  # CLUSTER > items/ELEMENT
  # A label for the individual.
  ['term', 'at0011', 'description'] => "その人を識別するための説明。",

  # CLUSTER > items/ELEMENT
  # For example: 'Neighbour in the house with the red door'.
  ['term', 'at0011', 'comment'] => "例：「赤い扉の家に住む近所の人」。",

}.freeze

# note 列に残すメモ。迷った訳語には '要確認: ...' を付ける。
NOTES = {
  # ['term', 'at0000', 'text'] => '要確認: ...',
}.freeze

src, dst = ARGV
lines = File.readlines(src, chomp: true)
out = [lines.shift]
lines.each do |l|
  c = l.split("\t", -1)
  key = c[1..3]
  c[6] = T.fetch(key).gsub("\n", '\n')
  c[7] = NOTES[key] || ''
  out << c.join("\t")
end
File.write(dst, out.join("\n") + "\n")
