# frozen_string_literal: true
# Japanese translation for openEHR-EHR-CLUSTER.structured_name.v1
# Generated by tools/scaffold_fill.rb - fill every empty string, following glossary-ja.md.
# Human proofreading: edit work/openEHR-EHR-CLUSTER.structured_name.v1.ja.tsv and run `make import ID=openEHR-EHR-CLUSTER.structured_name.v1` (regenerates this file).

T = {
  # To record details about the structured name of an individual as they are known or understood in the course of clinical documentation.
  ['description', '-', 'purpose'] => "臨床記録の作成に際して取得した、個人の構造化された氏名に関する詳細情報を記録するため。",

  # Use to record details about the structured name of an individual as they are known or understood in the course of clinical documentation, often ad hoc or when it is not appropriate or possible to use a formal demographic register or index.
  # 
  # In most simple clinical recording use cases, the unstructured 'Name' element within the CLUSTER.person archetype will be sufficient to record the name of an individual as part of a health record. However, in circumstances where a structured name is necessary or desirable for clinical recording purposes, nest this archetype within the 'Structured name' SLOT in CLUSTER.person archetype.
  # 
  # Each data element can be entered as a string of free text - for example, 'Prof Dr', 'Sonja Jane', 'Smith-Brown', 'MP'. Alternatively, as each data element is repeatable within a template:
  # - 'Title' could be cloned to 'Title 1' for the value 'Prof' and 'Title 2' for the value 'Dr'; and
  # -  'Given name' could be cloned and renamed to 'First name' for the value 'Sonja' and 'Middle name' for the value 'Jane'.
  # 
  # While this archetype has been aligned with ISO 22220, preferred name, name usage, valid dates and the repeating Name component/Order grouping has intentionally not been replicated due to the reduced scope of this archetype.
  # 
  # It is anticipated that in most use cases for which this archetype has been designed, complex family names will simply be recorded as a string. However, it is possible to record them with more granularity and within this structured name pattern using guidance and examples from ISO 22220:2007 (Annex F), including:
  # - Family name first, given name/s last;
  # - Family names with prefixes eg El Haddad or van der Heyden; and
  # - Names containing both father's and mother's family names.
  ['description', '-', 'use'] => "臨床記録の作成に際して取得した、個人の構造化された氏名に関する詳細情報を記録するために用いる。必要に応じて情報を記録する場合や、正式なデモグラフィック登録簿やインデックスの利用が適切でない、または利用できない場合を主に想定している。\n\n臨床記録に個人の氏名を記録するだけであれば、多くの場合、CLUSTER.person archetypeの非構造化の「氏名」要素で十分である。ただし、臨床記録の目的上、氏名を構造化して記録することが必要または望ましい場合は、CLUSTER.person archetypeの「構造化された氏名」SLOTに本archetypeを組み込む。\n\n各データエレメントには自由記述の文字列を入力できる。例：「Prof Dr」、「Sonja Jane」、「Smith-Brown」、「MP」。あるいは、各データエレメントはテンプレート内で繰り返せるため、次のように分けて記録することもできる。\n- 「敬称」を複製して「敬称 1」と「敬称 2」とし、それぞれに「Prof」と「Dr」を記録する。\n-  「名」を複製して「ファーストネーム」と「ミドルネーム」に名前を変更し、それぞれに「Sonja」と「Jane」を記録する。\n\n本archetypeは ISO 22220 に合わせているが、通称（preferred name）、氏名の用途、有効期間、および繰り返しの氏名構成要素／順序のグループ化は、本archetypeの範囲が限定されているため意図的に再現していない。\n\n本archetypeが設計されたほとんどのユースケースでは、複雑な姓は単に文字列として記録されると想定している。しかし、ISO 22220:2007（Annex F）の指針と例に従い、この構造化された氏名のパターンの中でより細かく記録することもできる。例えば、以下のように記録できる。\n- 姓を先に、名を後に記録する。\n- El Haddad や van der Heyden のように、接頭辞の付いた姓を記録する。\n- 父方と母方の両方の姓を含む氏名を記録する。",

  # Not to be used if an unstructured text string representing the individual's name is adequate for the purpose. Use the 'Name' data element within the CLUSTER.person for this purpose.
  # 
  # Not to be used for complex name representation or management, such as preferred names, name usage or valid dates of usage. Use a formal Master Patient Index or Health Provider Index for this purpose, or archetypes based on the openEHR Demographic Information Model.
  # 
  # Not to be used to represent or replace formal identification management or for the purposes of maintaining an official demographic register or index. Use a formal Master Patient Index or Health Provider Index for this purpose, or archetypes based on the openEHR Demographic Information Model.
  # 
  # Not to be used to represent the subject of care, participants or author of the record and similar data elements that should be represented formally in the health record using the Reference Model attributes.
  ['description', '-', 'misuse'] => "個人の氏名を非構造化のテキスト文字列で表せば足りる場合には、本archetypeではなく CLUSTER.person の「氏名」データエレメントを用いる。\n\n通称や氏名の用途、使用の有効期間など、氏名を複雑に表現・管理するために用いてはならない。これらの目的には、正式な患者マスターインデックス（MPI）や「医療従事者名簿（Health Provider Index）」、またはopenEHRデモグラフィック情報モデルに基づくarchetypeを用いること。\n\n正式な個人識別情報の管理やその代替、または公式のデモグラフィック登録簿やインデックスの維持・管理に用いてはならない。これらの目的には、正式な患者マスターインデックス（MPI）や「医療従事者名簿（Health Provider Index）」、またはopenEHRデモグラフィック情報モデルに基づくarchetypeを用いること。\n\nケア対象者、ケアへの参加者、記録の作成者など、参照モデルの属性を用いて健康記録に正式に記録すべき情報を、本archetypeで記録してはならない。",

  # person, individual, name
  ['description', '-', 'keywords'] => "人 | 個人 | 氏名 | 姓 | 名 | 構造化された氏名 | ふりがな",

  # © openEHR Foundation
  ['description', '-', 'copyright'] => "© openEHR Foundation",

  # CLUSTER
  # Structured name of a person
  ['term', 'at0000', 'text'] => "人の構造化された氏名",

  # CLUSTER
  # Discrete components of an individual's name.
  ['term', 'at0000', 'description'] => "個人の氏名の個別の構成要素。",

  # CLUSTER > items/ELEMENT
  # Title
  ['term', 'at0001', 'text'] => "敬称",

  # CLUSTER > items/ELEMENT
  # One or more honorific form(s) of address commencing a name.
  ['term', 'at0001', 'description'] => "氏名の先頭に置く1つ以上の敬称や肩書き。",

  # CLUSTER > items/ELEMENT
  # Occurrences for this data element are set to 0..* to allow for more than one Title to be recorded. Coding with an external terminology is preferred, where possible. For example: 'Doctor'; 'Ms'; 'Mx'; or 'Professor Dr'.
  ['term', 'at0001', 'comment'] => "このデータエレメントの出現回数は 0..* に設定されており、複数の敬称を記録できる。可能であれば、外部用語集によりコード化することが望ましい。例：「Doctor」、「Ms」、「Mx」、「Professor Dr」。",

  # CLUSTER > items/ELEMENT
  # Given name
  ['term', 'at0002', 'text'] => "名",

  # CLUSTER > items/ELEMENT
  # One or more unique name(s) used to identify an individual within a family group.
  ['term', 'at0002', 'description'] => "家族集団の中で個人を識別するために用いる1つ以上の固有の名前。",

  # CLUSTER > items/ELEMENT
  # Occurrences for this data element are set to 0..* to allow for more than one Given name to be recorded. In addition, this data element may be cloned and renamed within a template to allow discrete recording of different types of Given name - for example 'First name', 'Middle name', 'Preferred name' or 'Nickname', as required for a specific use case.
  ['term', 'at0002', 'comment'] => "このデータエレメントの出現回数は 0..* に設定されており、複数の名を記録できる。加えて、特定のユースケースの必要に応じて、テンプレート内でこのデータエレメントを複製して名前を変更し、「ファーストネーム」「ミドルネーム」「通称」「ニックネーム」のように種類の異なる名を個別に記録できる。日本語の氏名では「名」に当たる。ふりがな（カナ表記）を記録する場合は、テンプレートで本 CLUSTER をもう1つ占有して「氏名（カナ）」などと改名する。",

  # CLUSTER > items/ELEMENT
  # Family name
  ['term', 'at0005', 'text'] => "姓",

  # CLUSTER > items/ELEMENT
  # One or more name(s) that an individual has in common with a family group.
  ['term', 'at0005', 'description'] => "個人が家族集団と共有する1つ以上の名前。",

  # CLUSTER > items/ELEMENT
  # Also known as 'Last name' or 'Surname'. Occurrences for this data element are set to 0..* to allow for more than one Family name to be recorded. Complex names such as 'El Haddad' or 'van der Heyden' can be recorded using this naming pattern, as identified in ISO 22220 (Annex F), but for the intended use case for this archetype it is most likely that the full family name will be recorded as a string.
  ['term', 'at0005', 'comment'] => "「ラストネーム」または「サーネーム」とも呼ばれる。このデータエレメントの出現回数は 0..* に設定されており、複数の姓を記録できる。「El Haddad」や「van der Heyden」のような複雑な姓は、ISO 22220（Annex F）に示されるこの命名パターンで記録できるが、本archetypeが意図するユースケースでは、姓全体を文字列として記録することが最も多いと考えられる。日本語の氏名では「姓」に当たる。",

  # CLUSTER > items/ELEMENT
  # Suffix
  ['term', 'at0006', 'text'] => "接尾辞",

  # CLUSTER > items/ELEMENT
  # One or more term(s) placed after all other name components, usually to differentiate an individual from a family member with identical Given and Family name components.
  ['term', 'at0006', 'description'] => "他のすべての氏名構成要素の後に置く1つ以上の語。通常は、名と姓の構成要素が同一の家族構成員と個人を区別するために用いる。",

  # CLUSTER > items/ELEMENT
  # Occurrences for this data element are set to 0..* to allow for more than one Suffix to be recorded. Coding with an external terminology is preferred, where possible. For example: 'Junior (Jr)'; 'Senior (Sr)'; 'Second (II)'.
  ['term', 'at0006', 'comment'] => "このデータエレメントの出現回数は 0..* に設定されており、複数の接尾辞を記録できる。可能であれば、外部用語集によりコード化することが望ましい。例：「Junior (Jr)」、「Senior (Sr)」、「Second (II)」。",

}.freeze

# note 列に残すメモ。迷った訳語には '要確認: ...' を付ける。
NOTES = {
  ['description', '-', 'use'] => "要確認: preferred name＝通称、name usage＝氏名の用途、First name／Middle name＝ファーストネーム／ミドルネーム（MML4 middle＝ミドルネーム）",
  ['description', '-', 'keywords'] => "要確認: 原文 3 語（person, individual, name）に「姓」「名」「構造化された氏名」「ふりがな」を追加（CKM 検索用）",
  ['term', 'at0000', 'text'] => "要確認: 概念名「人の構造化された氏名」を採用（用語集 structured name＝構造化された氏名、person＝人。他候補: 構造化氏名（targets.tsv の案）、構造化された人名）",
  ['term', 'at0001', 'text'] => "要確認: Title＝「敬称」を採用（MML4 人名表現形式 prefix＝肩書き。他候補: 肩書き、称号）。Ms / Mx を含むので「敬称」",
  ['term', 'at0002', 'text'] => "要確認: Given name＝「名」、Family name＝「姓」（MML4 人名表現形式に合わせた。他候補: 名前／姓名）。comment 末尾にふりがなの扱い（テンプレートで本 CLUSTER をもう1つ占有）を日本向けの例示として追加（localisation-ja.md の翻訳層方針）",
  ['term', 'at0006', 'text'] => "要確認: Suffix＝「接尾辞」（他候補: サフィックス、接尾語）。MML4 の degree（学位）は Suffix で表す",
}.freeze

src, dst = ARGV
lines = File.readlines(src, chomp: true)
out = [lines.shift]
lines.each do |l|
  c = l.split("\t", -1)
  key = c[1..3]
  c[6] = T.fetch(key).gsub("\n", '\n')
  c[7] = NOTES[key] || ''
  out << c.join("\t")
end
File.write(dst, out.join("\n") + "\n")
