# frozen_string_literal: true
# Japanese translation for openEHR-EHR-CLUSTER.electronic_communication.v1
# Generated by tools/scaffold_fill.rb - fill every empty string, following glossary-ja.md.
# Human proofreading: edit work/openEHR-EHR-CLUSTER.electronic_communication.v1.ja.tsv and run `make import ID=openEHR-EHR-CLUSTER.electronic_communication.v1` (regenerates this file).

T = {
  # To record details about a specified type of electronic communication as it is known or understood in the course of clinical documentation.
  ['description', '-', 'purpose'] => "臨床記録の作成に際して取得した、特定の種別の電子的な連絡先に関する詳細情報を記録するため。",

  # Use to record details about a specified type of electronic communication for an individual or an organisation as it is known or understood in the course of clinical documentation. This is commonly ad hoc or when it is not appropriate or possible to use a formal register or index.
  ['description', '-', 'use'] => "臨床記録の作成に際して取得した、個人または組織の特定の種別の電子的な連絡先に関する詳細情報を記録するために用いる。正式な登録簿や公式の一覧によらずに知り得た連絡先をその場で記録する場合や、正式な登録簿や一覧を利用することが適切でない、または利用できない場合が主に想定されている。",

  # Not to be used for complex communication representation or management, such as preferred phone numbers or valid dates of usage. Use a formal Master Patient Index or Health Provider Index for this purpose, or archetypes based on the openEHR Demographic Information Model.
  # 
  # Not to be used to represent or replace formal identification management or for the purposes of maintaining an official demographic register or index. Use a formal Master Patient Index or Health Provider Index for this purpose, or archetypes based on the openEHR Demographic Information Model.
  ['description', '-', 'misuse'] => "優先して使う電話番号や利用できる期間など、連絡先を複雑に表現・管理するために用いてはならない。これらの目的には、正式な患者マスターインデックス（MPI）や「医療従事者名簿（Health Provider Index）」、またはopenEHRデモグラフィック情報モデルに基づくarchetypeを用いること。\n\n正式な個人識別情報の管理やその代替、または公式の登録簿や一覧の維持・管理に用いてはならない。これらの目的には、正式な患者マスターインデックス（MPI）や「医療従事者名簿（Health Provider Index）」、またはopenEHRデモグラフィック情報モデルに基づくarchetypeを用いること。",

  # telephone, phone, mobile, email, fax, pager, chat, social media, asynchronous, communication, SoMe
  ['description', '-', 'keywords'] => "電話 | 携帯電話 | 電子メール | ファクシミリ | ポケットベル | チャット | ソーシャルメディア | 非同期 | 通信 | SoMe | 電子的な連絡先",

  # CLUSTER
  # Electronic communication
  ['term', 'at0000', 'text'] => "電子的な連絡先",

  # CLUSTER
  # Details about a specified type of electronic communication.
  ['term', 'at0000', 'description'] => "特定の種別の電子的な連絡先に関する詳細情報。",

  # CLUSTER > items/ELEMENT
  # Type
  ['term', 'at0001', 'text'] => "種別",

  # CLUSTER > items/ELEMENT
  # The type or form of electronic communication.
  ['term', 'at0001', 'description'] => "電子的な連絡先の種別または形式。",

  # CLUSTER > items/ELEMENT
  # The DV_CODED_TEXT value set supports recording of the most common electronic communications used in health. If other alternatives are required the DV_TEXT data type can be used to record other types of electronic communication such as social media or video conferencing URLs within a template.
  ['term', 'at0001', 'comment'] => "DV_CODED_TEXT の値セットを用いて、医療でよく使われる電子的な連絡先を記録できる。それ以外の種別が必要な場合は、テンプレート内で DV_TEXT データ型を用いる。ソーシャルメディアやビデオ会議の URL なども記録できる。",

  # CLUSTER > items/ELEMENT
  # Value
  ['term', 'at0002', 'text'] => "値",

  # CLUSTER > items/ELEMENT
  # The unique combination of alphanumeric characters, relevant for representation of 'Type'.
  ['term', 'at0002', 'description'] => "「種別」に応じて連絡先を一意に表す英数字の組み合わせ。",

  # CLUSTER > items/ELEMENT
  # For example: area code + landline phone/pager number; country code + mobile phone number; or email address.
  ['term', 'at0002', 'comment'] => "例：市外局番と固定電話番号またはポケットベル番号の組み合わせ、国番号と携帯電話番号の組み合わせ、電子メールアドレス。",

  # CLUSTER > items/ELEMENT
  # Purpose
  ['term', 'at0003', 'text'] => "用途",

  # CLUSTER > items/ELEMENT
  # The purpose or use for the identified type of electronic communication.
  ['term', 'at0003', 'description'] => "指定した種別の電子的な連絡先を何のために使うかを示す。",

  # CLUSTER > items/ELEMENT
  # Comment
  ['term', 'at0004', 'text'] => "コメント",

  # CLUSTER > items/ELEMENT
  # Additional narrative about the electronic communication not captured in other fields.
  ['term', 'at0004', 'description'] => "他の項目には収まらない電子的な連絡先についての追加の記述。",

  # Mobile (cellular) telephone
  ['term', 'at0005', 'text'] => "携帯電話",

  # For SMS or voice calls.
  ['term', 'at0005', 'description'] => "SMS または音声通話に用いる。",

  # Telephone (excluding mobile telephone)
  ['term', 'at0006', 'text'] => "固定電話",


  ['term', 'at0006', 'description'] => '',

  # Email
  ['term', 'at0007', 'text'] => "電子メール",


  ['term', 'at0007', 'description'] => '',

  # Pager
  ['term', 'at0008', 'text'] => "ポケットベル",


  ['term', 'at0008', 'description'] => '',

  # Fax
  ['term', 'at0009', 'text'] => "ファクシミリ",


  ['term', 'at0009', 'description'] => '',

  # Business use
  ['term', 'at0010', 'text'] => "業務用",


  ['term', 'at0010', 'description'] => '',

  # Personal use
  ['term', 'at0011', 'text'] => "個人用",


  ['term', 'at0011', 'description'] => '',

  # Both business and personal use
  ['term', 'at0012', 'text'] => "業務用・個人用の両方",


  ['term', 'at0012', 'description'] => '',

  # CLUSTER > items/CLUSTER
  # Additional details
  ['term', 'at0013', 'text'] => "追加の詳細情報",

  # CLUSTER > items/CLUSTER
  # Additional details about the electronic communication.
  ['term', 'at0013', 'description'] => "電子的な連絡先に関する追加の詳細情報。",

}.freeze

# note 列に残すメモ。迷った訳語には '要確認: ...' を付ける。
NOTES = {
  ['term', 'at0002', 'text'] => "要確認: 値（他候補: 連絡先の値）原文の汎用的なラベルを保ち、電話番号や電子メールアドレスなどを含められる訳を採用。",
}.freeze

src, dst = ARGV
lines = File.readlines(src, chomp: true)
out = [lines.shift]
lines.each do |l|
  c = l.split("\t", -1)
  key = c[1..3]
  c[6] = T.fetch(key).gsub("\n", '\n')
  c[7] = NOTES[key] || ''
  out << c.join("\t")
end
File.write(dst, out.join("\n") + "\n")
