# frozen_string_literal: true
# Japanese translation for openEHR-EHR-CLUSTER.anatomical_location.v1
# Generated by tools/scaffold_fill.rb - fill every empty string, following glossary-ja.md.
# Human proofreading: edit work/openEHR-EHR-CLUSTER.anatomical_location.v1.ja.tsv and run `make import ID=openEHR-EHR-CLUSTER.anatomical_location.v1` (regenerates this file).

T = {
  # To identify and record structured details about a single physical site on, or within, the human body using macroscopic anatomical terms.
  ['description', '-', 'purpose'] => "肉眼解剖学の用語を用いて、人体の体表または体内の単一の部位を特定し、構造化された詳細情報を記録するため。",

  # Use to record structured details about a single identified physical site on or within the human body.
  # 
  # In many situations, a simple data element such as ‘Location of measurement’ or ‘Body site’ will be sufficient and practical when the value set is straightforward. This archetype is intended for cases where a more detailed or structured representation of an anatomical site is required, including precise or compound descriptions. It can be nested within relevant ENTRY or CLUSTER archetypes such as those for symptoms, findings, or interventions to support multiaxial or postcoordinated anatomical expressions. Examples include documenting pain in the lower limb, tenderness at McBurney’s point, or a laceration on the palmar aspect of the proximal right thumb.
  # 
  # The ‘Laterality' data element may be used to qualify whether a paired structure or region is affected on the left, right, or both sides. When involvement is symmetrical and equivalent on both sides, for example the same cancer in both lungs or similar pain in both legs, record 'Left and right’. However, when the clinical characteristics differ between sides, two separate instances should be used:
  # 
  # - Two parallel instances of this archetype within the same SLOT, each with its own laterality and specific details. For example, documenting equal tumours in the lower left lung lobe and the upper right lung lobe.
  # - Two parallel instances of the parent archetype, each containing an instance of this archetype, when there are clinically significant differences such as tumour type, size, or severity in each lung.
  # 
  # The 'Alternative structure' SLOT allows inclusion of additional archetypes that provide an alternative structure for describing the same body site, such as CLUSTER.anatomical_location_relative or CLUSTER.anatomical_location_clock, should this be required. In situations where this archetype is used to name a large or non-specific body part, the additional use of the CLUSTER.anatomical_location_relative archetype will support recording of a more precise location, for example, 2 cm anterior to the cubital fossa of the left forearm or 4 cm below the right costal margin on the chest wall in the mid-clavicular line.
  # 
  # If this archetype is used within other archetypes where the specified subject of care is not the individual for whom the record is being created, for example a fetus in utero, then the anatomical location will be identifying a body site on or within the fetus.
  ['description', '-', 'use'] => "人体の体表または体内の、特定された単一の部位について、構造化された詳細情報を記録するために用いる。\n\n多くの場合、値セットが単純であれば、「計測部位」や「身体部位」のような単一のデータエレメントで十分であり、実用的である。本archetypeは、正確な記述や複数の情報を組み合わせた記述など、解剖学的部位をより詳細に、または構造化して表現する必要がある場合を想定している。症状、所見、介入などを扱う関連する ENTRY または CLUSTER archetypeの中に入れ子にして、多軸または事後調整された解剖学的表現を記録できる。例：下肢の疼痛、マックバーニー点の圧痛、右母指近位の掌側にある裂傷を記録する。\n\n「側性」データエレメントは、対をなす構造や領域の左側、右側、両側のどこが影響を受けているかを示すために用いる。両肺の同じがんや両下肢の同様の疼痛など、左右対称で同等の所見がある場合は「両側」と記録する。一方、臨床的な特徴が左右で異なる場合は、次のように2つの別々のインスタンスを用いる。\n\n- 同じ SLOT 内に本archetypeのインスタンスを2つ並べ、それぞれに側性と詳細情報を記録する。例：左肺下葉と右肺上葉にある同等の腫瘍を記録する。\n- 左右の肺で腫瘍の種類、大きさ、重症度などに臨床的に重要な違いがある場合は、親archetypeのインスタンスを2つ並べ、それぞれに本archetypeのインスタンスを含めて記録する。\n\n「代替の構造化表現」SLOT には、必要に応じて CLUSTER.anatomical_location_relative や CLUSTER.anatomical_location_clock などのarchetypeを追加できる。これにより、同じ身体部位を別の構造で表現できる。本archetypeで広い範囲の身体部位や具体的に特定されていない身体部位の名称を記録する場合、CLUSTER.anatomical_location_relative archetypeを併用することで、より正確な位置を記録できる。例：左前腕の肘窩より 2 cm 前方、鎖骨中線上の胸壁で右肋骨弓より 4 cm 下方。\n\n本archetypeを他のarchetype内で用い、指定されたケア対象者が記録の対象者本人ではなく、例えば子宮内の胎児である場合、解剖学的部位は胎児の体表または体内の身体部位を示す。",

  # Not to be used to describe involvement of both sides of a paired structure when the clinical findings differ significantly between sides. In such cases, each side should be documented using a separate instance of this archetype with side-specific detail.
  ['description', '-', 'misuse'] => "対をなす構造の両側で臨床所見が大きく異なる場合の記録には、本archetypeの単一のインスタンスではなく、左右別々のインスタンスを用いる。それぞれに左右固有の詳細情報を記録する。",

  # location | site | anatomical | anatomic region | topographic anatomy | macroscopic | anatomic | anatomy
  ['description', '-', 'keywords'] => "位置 | 部位 | 解剖学的 | 解剖学的領域 | 局所解剖学 | 肉眼的 | 解剖学的 | 解剖学 | 解剖学的部位 | 身体部位 | 局所解剖",

  # © openEHR Foundation
  ['description', '-', 'copyright'] => "© openEHR Foundation",

  # CLUSTER
  # Anatomical location
  ['term', 'at0000', 'text'] => "解剖学的部位",

  # CLUSTER
  # A physical site on or within the human body.
  ['term', 'at0000', 'description'] => "人体の体表または体内の部位。",

  # CLUSTER > items/ELEMENT
  # Body site name
  ['term', 'at0001', 'text'] => "身体部位名",

  # CLUSTER > items/ELEMENT
  # Identification of a single physical site either on, or within, the human body.
  ['term', 'at0001', 'description'] => "人体の体表または体内の単一の部位を示す。",

  # CLUSTER > items/ELEMENT
  # This data element is the only mandated data point in this archetype and should be used as the primary data point to record an anatomical location with a commonly used name. It is strongly recommended that 'Body site name' be recorded as specifically as is anatomically possible. For example: record 'upper eyelid' rather than recording 'eyelid' with 'upper' as a qualifier; 'fifth rib' rather than 'rib' with a numeric qualifier. Use the other data elements for laterality, aspect, region and anatomical line to provide more detail.
  # 
  # This data element should be coded with a terminology capable of triggering decision support, where possible - an appropriate termset for use here could comprise individual concepts or a list of precoordinated terms. Free text should be used only if there is no appropriate terminology available.
  # 
  # If 'Body site name' is already identified in an archetype in which this Anatomical location archetype has been nested, then this data element may be redundant. However, it might be reasonable to duplicate 'Body site name' in this archetype to support semantic querying using this archetype, instead of the archetype in which it has been nested.
  ['term', 'at0001', 'comment'] => "このデータエレメントは、本archetypeで唯一の必須データ項目である。一般に用いられる名称で解剖学的部位を記録するための主要なデータ項目として用いる。「身体部位名」は、解剖学的に可能な限り具体的に記録することを強く推奨する。例：「眼瞼」に「上」という修飾語を付けるのではなく「上眼瞼」と記録する。「肋骨」に数字の修飾語を付けるのではなく「第 5 肋骨」と記録する。さらに詳しく記録するには、側性、方向、領域、解剖学的基準線を表す他のデータエレメントを用いる。\n\n可能であれば、このデータエレメントは臨床意思決定支援を作動させることができる用語集によりコード化する。ここで用いる用語セットは、個々の概念、または事前調整された用語の一覧で構成できる。適切な用語集が利用できない場合に限り、自由記述を用いる。\n\n本archetypeを他のarchetypeの中に入れ子にして使用し、そのarchetypeですでに「身体部位名」が示されている場合、このデータエレメントは冗長になることがある。ただし、入れ子先のarchetypeではなく本archetypeを用いて意味に基づく検索を行うために、本archetypeにも「身体部位名」を重複して記録することが妥当な場合もある。",

  # CLUSTER > items/ELEMENT
  # Laterality
  ['term', 'at0002', 'text'] => "側性",

  # CLUSTER > items/ELEMENT
  # The side of the body on which the identified body site is located.
  ['term', 'at0002', 'description'] => "特定された身体部位が身体のどちら側にあるかを示す。",

  # CLUSTER > items/ELEMENT
  # If the 'Body site name' includes a pre-coordinated term that already specifies laterality, this data element may be redundant. If the findings require documentation of a body site on both the left and right sides of the body, or involving both sides of a paired structure or region, use 'Left and right' only when the same anatomical site is affected on both sides and side-specific detail is not required. If the findings differ significantly between sides, each should be recorded as a separate instance of this archetype with the appropriate laterality.
  ['term', 'at0002', 'comment'] => "「身体部位名」に側性を含む事前調整された用語を用いる場合、このデータエレメントは冗長になることがある。身体の左右両側にある部位や、対をなす構造または領域の両側について所見を記録する際には、両側の同じ解剖学的部位が影響を受け、左右それぞれの詳細情報が不要な場合に限り「両側」を用いる。左右で所見が大きく異なる場合は、本archetypeの別々のインスタンスを用い、それぞれに適切な側性を記録する。",

  # Left
  ['term', 'at0003', 'text'] => "左",

  # Left side of the body.
  ['term', 'at0003', 'description'] => "身体の左側。",

  # Right
  ['term', 'at0004', 'text'] => "右",

  # Right side of the body.
  ['term', 'at0004', 'description'] => "身体の右側。",

  # CLUSTER > items/ELEMENT
  # Description
  ['term', 'at0023', 'text'] => "説明",

  # CLUSTER > items/ELEMENT
  # Narrative description that can be used to further refine and support the 'Body site name'.
  ['term', 'at0023', 'description'] => "「身体部位名」をさらに詳しく説明し、補足するための叙述的な説明。",

  # CLUSTER > items/ELEMENT
  # For example: adjacent to the vermilion border; a tattoo covers the bottom half of this area.
  ['term', 'at0023', 'comment'] => "例：赤唇縁に隣接する、この領域の下半分を入れ墨が覆っている。",

  # CLUSTER > items/CLUSTER
  # Alternative structure
  ['term', 'at0053', 'text'] => "代替の構造化表現",

  # CLUSTER > items/CLUSTER
  # Additional detail about the anatomical site using alternative approaches to describe the same body site.
  ['term', 'at0053', 'description'] => "同じ身体部位を別の方法で表現するための、解剖学的部位に関する追加の詳細情報。",

  # CLUSTER > items/CLUSTER
  # For example, relative location or precise locations using coordinates.
  ['term', 'at0053', 'comment'] => "例：相対的な位置や、座標を用いた正確な位置。",

  # CLUSTER > items/CLUSTER
  # Multimedia representation
  ['term', 'at0054', 'text'] => "マルチメディア表現",

  # CLUSTER > items/CLUSTER
  # Image or other media used to support identification of the body site.
  ['term', 'at0054', 'description'] => "身体部位を特定するための補助となる画像やその他のメディア。",

  # CLUSTER > items/ELEMENT
  # Anatomical Line
  ['term', 'at0055', 'text'] => "解剖学的基準線",

  # CLUSTER > items/ELEMENT
  # Additional detail using theoretical lines drawn through anatomical structures used to provide a consistent reference point on the human body.
  ['term', 'at0055', 'description'] => "人体上の共通の基準となる、解剖学的構造を通る仮想の線を用いた追加の詳細情報。",

  # CLUSTER > items/ELEMENT
  # Common anatomical lines have been included as a value set, which can be extended over time, plus a free text option. The additional use of this data element allows for recording of the typical position of the heart's apex beat at 5th intercostal space, left side, and mid-clavicular line. If the 'Body site name' data element uses pre-coordinated terms that include anatomical line, then this data element is redundant.
  ['term', 'at0055', 'comment'] => "一般的な解剖学的基準線を値セットとして含み、自由記述も選択できる。値セットは今後拡張できる。このデータエレメントを追加で用いることで、心尖拍動の典型的な位置を、左側の第 5 肋間、鎖骨中線上として記録できる。「身体部位名」データエレメントに解剖学的基準線を含む事前調整された用語を用いる場合、このデータエレメントを使用する必要はない。",

  # Midaxillary line
  ['term', 'at0056', 'text'] => "中腋窩線",

  # Line running vertically down the surface of the body, passing through the apex of the axilla.
  ['term', 'at0056', 'description'] => "腋窩の頂点を通り、体表を垂直に下る線。",

  # Anterior axillary line
  ['term', 'at0057', 'text'] => "前腋窩線",

  # Line running vertically down the surface of the body, passing through the anterior axillary skinfold.
  ['term', 'at0057', 'description'] => "前腋窩ひだを通り、体表を垂直に下る線。",

  # Posterior axillary line
  ['term', 'at0058', 'text'] => "後腋窩線",

  # Line running vertically down the surface of the body, passing through the posterior axillary skinfold.
  ['term', 'at0058', 'description'] => "後腋窩ひだを通り、体表を垂直に下る線。",

  # Mid-clavicular line
  ['term', 'at0059', 'text'] => "鎖骨中線",

  # Line running vertically down the surface of the body, parallel to the midline and passing through the midpoint of the clavicle.
  ['term', 'at0059', 'description'] => "鎖骨の中点を通り、正中線と平行に体表を垂直に下る線。",

  # Mid-pupillary line
  ['term', 'at0060', 'text'] => "瞳孔中心線",

  # Line running vertically down the face through the midpoint of the pupil when looking directly forward.
  ['term', 'at0060', 'description'] => "正面を向いたときの瞳孔の中心を通り、顔面を垂直に下る線。",

  # Midline
  ['term', 'at0062', 'text'] => "正中線",

  # Line running vertically which divides the body into left and right portions, passing through the head, spinal cord, and umbilicus. Alternatively it can refer to a line dividing a body part into two equal portions, for example a digit.
  ['term', 'at0062', 'description'] => "頭部、脊髄、臍を通り、身体を左右に分ける垂直な線。また、指（手指・足趾）などの身体の一部を等しく二分する線を指すこともある。",

  # Mid-scapular line
  ['term', 'at0063', 'text'] => "肩甲線",

  # Line running vertically down the posterior surface of the body, parallel to the midline and passing through the inferior point of the scapula.
  ['term', 'at0063', 'description'] => "肩甲骨の下角を通り、正中線と平行に身体の後面を垂直に下る線。",

  # CLUSTER > items/ELEMENT
  # Aspect
  ['term', 'at0064', 'text'] => "方向",

  # CLUSTER > items/ELEMENT
  # Qualifying detail about the specific aspect of the identified body site.
  ['term', 'at0064', 'description'] => "特定された身体部位の方向を詳しく示す情報。",

  # CLUSTER > items/ELEMENT
  # Use to increase precision of identification of the body site, if required. Common aspects have been included as a value set, which can be extended over time, plus a free text option. Assumes that the body is being described while in the anatomical position. For example: proximal urethra; plantar aspect of the left thumb. Multiple aspects can also be described, if required, by allowing for 0..2 occurrences. For example: a lesion may be on the left anterior/lateral (ie anterolateral) chest wall. If the 'Body site name' data element uses pre-coordinated terms that include the aspect, then this data element is redundant.
  ['term', 'at0064', 'comment'] => "必要に応じて、身体部位をより正確に示すために用いる。一般的な方向を値セットとして含み、自由記述も選択できる。値セットは今後拡張できる。身体が解剖学的正位にあることを前提として記述する。例：尿道の近位、左母指の足底側。必要に応じて出現回数を 0..2 とすることで、複数の方向も記述できる。例：左胸壁の前方と外側（すなわち前外側）にある病変。「身体部位名」データエレメントに方向を含む事前調整された用語を用いる場合、このデータエレメントを使用する必要はない。",

  # CLUSTER > items/ELEMENT
  # Specific site
  ['term', 'at0065', 'text'] => "特定部位",

  # CLUSTER > items/ELEMENT
  # Additional detail using a specific region or a point on, or within, the identified body site.
  ['term', 'at0065', 'description'] => "特定された身体部位の表面または内部にある、特定の領域や点を用いた追加の詳細情報。",

  # CLUSTER > items/ELEMENT
  # Use to increase precision of identification of the body site, if required. For example, the upper right quadrant or McBurney's point on the abdominal wall or interphalangeal joint of the great toe. If the 'Body site name' data element uses pre-coordinated terms that include the specific site, then this data element is redundant.
  # In most situations this will be a single specific site. This data element has multiple occurrences to support less common use cases which need to identify a single anatomical location involving two or more adjacent and continuous specific sites. For example, to describe the specific site of a single tumour extending across the 2nd, 3rd and 4th ribs.
  ['term', 'at0065', 'comment'] => "必要に応じて、身体部位をより正確に示すために用いる。例：腹壁の右上腹部やマックバーニー点、母趾の趾節間関節。「身体部位名」データエレメントに特定部位を含む事前調整された用語を用いる場合、このデータエレメントを使用する必要はない。\n通常は単一の特定部位を記録する。まれに、隣接して連続する2つ以上の特定部位にまたがる単一の解剖学的部位を示す必要があるため、このデータエレメントは複数回の出現を許容する。例：第 2、第 3、第 4 肋骨にまたがる単一の腫瘍の特定部位を記述する。",

  # Medial
  ['term', 'at0067', 'text'] => "内側",

  # Towards the midline of the body site.
  ['term', 'at0067', 'description'] => "身体部位の正中線に向かう方向。",

  # Lateral
  ['term', 'at0068', 'text'] => "外側",

  # Towards the side, or edge, of the body site.
  ['term', 'at0068', 'description'] => "身体部位の側方または縁に向かう方向。",

  # Superior
  ['term', 'at0069', 'text'] => "上方",

  # Above the body site, often meaning towards the head.
  ['term', 'at0069', 'description'] => "身体部位より上の方向。多くの場合、頭部に向かう方向を意味する。",

  # Inferior
  ['term', 'at0070', 'text'] => "下方",

  # Below the body site, often meaning towards the feet.
  ['term', 'at0070', 'description'] => "身体部位より下の方向。多くの場合、足に向かう方向を意味する。",

  # Anterior
  ['term', 'at0071', 'text'] => "前方",

  # Towards the front, or ventral surface, of the body site.
  ['term', 'at0071', 'description'] => "身体部位の前面、すなわち腹側面に向かう方向。",

  # Posterior
  ['term', 'at0072', 'text'] => "後方",

  # Towards the back, or dorsal surface, of the body site.
  ['term', 'at0072', 'description'] => "身体部位の後面、すなわち背側面に向かう方向。",

  # Proximal
  ['term', 'at0073', 'text'] => "近位",

  # More central or closer to the point of attachment, and usually describing part of a limb, digit or appendage.
  ['term', 'at0073', 'description'] => "より中心に近い、または付着部に近い側。通常は四肢、指（手指・足趾）、付属肢の一部を表す際に用いる。",

  # Distal
  ['term', 'at0074', 'text'] => "遠位",

  # More peripheral, or further from the point of attachment, and usually describing part of a limb, digit or appendage.
  ['term', 'at0074', 'description'] => "より末梢にある、または付着部から遠い側。通常は四肢、指（手指・足趾）、付属肢の一部を表す際に用いる。",

  # Palmar
  ['term', 'at0075', 'text'] => "掌側",

  # Towards the palm of the hand.
  ['term', 'at0075', 'description'] => "手掌に向かう方向。",

  # Plantar
  ['term', 'at0076', 'text'] => "足底側",

  # Towards the sole of the foot.
  ['term', 'at0076', 'description'] => "足底に向かう方向。",

  # Mid
  ['term', 'at0077', 'text'] => "中央",

  # In the middle of the body site.
  ['term', 'at0077', 'description'] => "身体部位の中央。",

  # Oral
  ['term', 'at0078', 'text'] => "口側",

  # Towards the mouth. Usually used to describe locations within the digestive system.
  ['term', 'at0078', 'description'] => "口に向かう方向。通常は消化管内の部位を表す際に用いる。",

  # Anal
  ['term', 'at0079', 'text'] => "肛門側",

  # Towards the anus. Usually used to describe locations within the digestive system.
  ['term', 'at0079', 'description'] => "肛門に向かう方向。通常は消化管内の部位を表す際に用いる。",

  # Deep
  ['term', 'at0080', 'text'] => "深部",

  # Away from the surface of the body site.
  ['term', 'at0080', 'description'] => "身体部位の表面から離れる方向。",

  # Superficial
  ['term', 'at0081', 'text'] => "浅部",

  # Towards the surface of the body site.
  ['term', 'at0081', 'description'] => "身体部位の表面に向かう方向。",

  # Dorsal
  ['term', 'at0082', 'text'] => "背側",

  # Towards the back of the hand or top of the foot. To be used as opposites of palmar or plantar, not as a synonym of posterior.
  ['term', 'at0082', 'description'] => "手背または足背に向かう方向。掌側または足底側の対語として用い、後方の同義語としては用いない。",

  # Right and left
  ['term', 'at0083', 'text'] => "両側",

  # Both the right and left sides of the body, or involving both sides of a paired organ, body structure, or anatomical region.
  ['term', 'at0083', 'description'] => "身体の左右両側、または対をなす臓器、身体構造、解剖学的領域の両側。",

}.freeze

# note 列に残すメモ。迷った訳語には '要確認: ...' を付ける。
NOTES = {
  ['term', 'at0002', 'text'] => "要確認: 側性（他候補: 左右）院内がん登録・画像レポートの用語に合わせる。",
  ['term', 'at0083', 'text'] => "要確認: 両側（他候補: 左右）両側に及ぶことを明確にする。本文の Left and right も同じ値として訳す。",
  ['term', 'at0064', 'text'] => "要確認: 方向（他候補: 面）値セットが近位・遠位・上方などの方向用語であるため。media_file の観察方向とは区別する。",
  ['term', 'at0065', 'text'] => "要確認: 特定部位（他候補: 詳細部位）身体部位内の特定の領域や点を示すため。",
  ['term', 'at0069', 'text'] => "要確認: 上方（他候補: 上）方向を示す値であることを明確にする。",
  ['term', 'at0070', 'text'] => "要確認: 下方（他候補: 下）方向を示す値であることを明確にする。",
  ['term', 'at0071', 'text'] => "要確認: 前方（他候補: 前）方向を示す値であることを明確にする。",
  ['term', 'at0072', 'text'] => "要確認: 後方（他候補: 後）方向を示す値であることを明確にする。",
  ['term', 'at0075', 'text'] => "要確認: 掌側（他候補: 手掌側）指定案を採用し、足底側・背側と対になる方向を表す。",
  ['term', 'at0076', 'text'] => "要確認: 足底側（他候補: 底側）足底を指すことを明確にする。",
  ['term', 'at0080', 'text'] => "要確認: 深部（他候補: 深層）層ではなく表面から離れる方向を示すため。",
  ['term', 'at0081', 'text'] => "要確認: 浅部（他候補: 浅層）層ではなく表面に向かう方向を示すため。",
  ['term', 'at0077', 'text'] => "要確認: 中央（他候補: 中間）身体部位の中央を示すため。",
  ['term', 'at0055', 'text'] => "要確認: 解剖学的基準線（他候補: 基準線、体表基準線）解剖学的構造を基準とする線であることを明確にする。",
  ['term', 'at0060', 'text'] => "要確認: 瞳孔中心線（他候補: 瞳孔中線、瞳孔線）正面視で瞳孔の中心を通るという定義に合わせる。",
  ['term', 'at0063', 'text'] => "要確認: 肩甲線（他候補: 肩甲骨中線）肩甲骨下角を通る垂線という定義に合わせ、指定された scapular line の訳を採用する。",
  ['term', 'at0053', 'text'] => "要確認: 代替の構造化表現（他候補: 代替構造）構造化された身体部位表現と語感を揃える。",
  ['term', 'at0073', 'description'] => "要確認: 付属肢（他候補: 付属器）指定案を採用する。limb、digit と並列される appendage の範囲は確認が必要。",
  ['term', 'at0074', 'description'] => "要確認: 付属肢（他候補: 付属器）指定案を採用する。limb、digit と並列される appendage の範囲は確認が必要。",
  ['term', 'at0064', 'comment'] => "要確認: 左母指の足底側（他候補: 左母指の掌側）原文 plantar aspect of the left thumb を保持した。母指と足底側の不整合は原文の確認が必要。",
  ['description', '-', 'use'] => "要確認: 多軸／事後調整された（他候補: 複数の軸による／後から組み合わせた）multiaxial／postcoordinated の訳。事前調整されたとの対応を優先する。",
  ['term', 'at0001', 'comment'] => "要確認: 用語セット／意味に基づく検索（他候補: 用語集合／意味的照会）termset／semantic querying の訳。用語セットは値セットと区別し、検索は日本語としての読みやすさを優先する。",
}.freeze

src, dst = ARGV
lines = File.readlines(src, chomp: true)
out = [lines.shift]
lines.each do |l|
  c = l.split("\t", -1)
  key = c[1..3]
  c[6] = T.fetch(key).gsub("\n", '\n')
  c[7] = NOTES[key] || ''
  out << c.join("\t")
end
File.write(dst, out.join("\n") + "\n")
