# frozen_string_literal: true
# Japanese translation for openEHR-EHR-SECTION.adhoc.v1
# Generated by tools/scaffold_fill.rb - fill every empty string, following glossary-ja.md.
# Human proofreading: edit work/openEHR-EHR-SECTION.adhoc.v1.ja.tsv and run `make import ID=openEHR-EHR-SECTION.adhoc.v1` (regenerates this file).

T = {
  # To provide a generic section header which will be renamed in a template to suit a specific clinical context.
  ['description', '-', 'purpose'] => "テンプレート内で特定の臨床的文脈に合わせて名前を変更して使う、汎用のセクション見出しを提供するため。",

  # Use to construct a section heading in a template that will be renamed to suit the specific clinical context. For example: \"Ad hoc heading\" renamed to \"Examination findings\".
  ['description', '-', 'use'] => "テンプレート内で、特定の臨床的文脈に合わせて名前を変更するセクション見出しを構成するために用いる。例：「仮見出し」を「診察所見」に変更する。",

  # Not to be left unchanged in a template.
  ['description', '-', 'misuse'] => "テンプレート内で名前を変更せずにそのまま残してはならない。",

  # © openEHR Foundation
  ['description', '-', 'copyright'] => "© openEHR Foundation",

  # SECTION
  # Ad hoc heading
  ['term', 'at0000', 'text'] => "仮見出し",

  # SECTION
  # A generic section header which should be renamed in a template to suit a specific clinical context.
  ['term', 'at0000', 'description'] => "テンプレート内で特定の臨床的文脈に合わせて名前を変更すべき、汎用のセクション見出し。",

}.freeze

# note 列に残すメモ。迷った訳語には '要確認: ...' を付ける。
NOTES = {
  ['term', 'at0000', 'text'] => "校正（2026-09-13）で「仮見出し」に決定（旧: 任意見出し。他候補: アドホック見出し、汎用見出し）",
}.freeze

src, dst = ARGV
lines = File.readlines(src, chomp: true)
out = [lines.shift]
lines.each do |l|
  c = l.split("\t", -1)
  key = c[1..3]
  c[6] = T.fetch(key).gsub("\n", '\n')
  c[7] = NOTES[key] || ''
  out << c.join("\t")
end
File.write(dst, out.join("\n") + "\n")
