# frozen_string_literal: true
# Japanese translation for openEHR-EHR-CLUSTER.symptom_sign.v2
# Generated by tools/scaffold_fill.rb - fill every empty string, following glossary-ja.md.
# Human proofreading: edit work/openEHR-EHR-CLUSTER.symptom_sign.v2.ja.tsv and run `make import ID=openEHR-EHR-CLUSTER.symptom_sign.v2` (regenerates this file).

T = {
  # To record details about a single episode of a reported symptom or sign including context, but not details, of previous episodes if appropriate.
  ['description', '-', 'purpose'] => "報告された症状または徴候の単一のエピソードについて詳細に記録するため。必要に応じて過去のエピソードの（詳細ではない）文脈を含める。",

  # Use to record details about a single episode of a symptom or reported sign in an individual, as reported by the individual, parent, care-giver or other party. It may be recorded by a clinician as part of a clinical history record as reported to them, observed by the clinician or self-recorded as part of a clinical questionnaire or personal health record. A complete clinical history or patient story may include varying level of details about multiple episodes of an identified symptom or reported sign, as well as multiple symptoms/signs.
  # 
  # This archetype has been designed to record the positive presence of the symptom or sign as part of history taking using OBSERVATION.story, or in conjunction with a positive response to OBSERVATION.symptom_sign_screening.
  # 
  # In the purest sense, symptoms are subjective observations of a physical or mental disturbance and signs are objective observations of the same, as experienced by an individual and reported to the history taker by the same individual or another party. From this logic it follows that we will need two archetypes to record clinical history - one for reported symptoms and another for reported signs. In reality this is impractical as it will require clinical data entry into either one of these models which adds signficant overheads to modellers and those entering data. In addition, there is often overlap in clinical concepts - for example, is previous vomiting or bleeding to be categorised as a symptom or reported sign? In response, this archetype has been specifically designed to provide a single information model that allows for recording of the entire continuum between clearly identifiable symptoms and reported signs.
  # 
  # This archetype has been intended to be used as a generic pattern for all symptoms and reported signs. The 'Specific details' SLOT can be used to extend the archetype to include additional, specific data elements for more complex symptoms or signs. 
  # 
  # This archetype has been specifically designed to be used in the 'Structured detail' SLOT within the OBSERVATION.story archetype, but can also be used within other OBSERVATION or CLUSTER archetypes and in the 'Associated symptom/sign' or 'Previous episode' SLOT within other instances of this CLUSTER.symptom_sign archetype.
  ['description', '-', 'use'] => "本人、親、介護者、その他の関係者から報告された症状や徴候について、単一のエピソードを詳細に記録するために用いる。臨床医が聴取した内容や自ら観察した内容を病歴として記録する場合にも、本人が問診票や個人健康記録に記入する場合にも使用できる。病歴全体や患者の語りには、複数の異なる症状・徴候だけでなく、同じ症状・徴候に関する複数のエピソードが含まれることがあり、それぞれの記述の詳しさも異なる。\n\n本archetypeは、症状や徴候がある場合に、その内容を詳しく記録するために設計されている。OBSERVATION.storyを用いた病歴聴取の一部として、またはOBSERVATION.symptom_sign_screeningでの「症状・徴候あり」という回答と組み合わせて使用する。\n\n厳密には、症状は心身の変調に関する主観的な観察に基づくものであり、徴候は客観的な観察に基づくものである。いずれも本人が経験したこととして、本人または他者から病歴の聴取者に伝えられる。この区別に従えば、病歴の記録には、報告された症状を記録するarchetypeと、報告された徴候を記録するarchetypeの二つが必要になる。しかし、実際には、臨床データをどちらのモデルに入力するかを判断して使い分けなければならず、モデルの設計者とデータの入力者の双方に大きな負担が生じるため、現実的ではない。また、症状と徴候には、明確に区別しにくい臨床概念もある。例えば、過去に起きた嘔吐や出血は、症状と報告された徴候のどちらに分類すべきだろうか。そこで本archetypeは、明らかな症状から報告された徴候まで、両者の境界に位置するものも含めて、一つの情報モデルで記録できるように設計されている。\n\n本archetypeは、あらゆる症状や報告された徴候を記録するための汎用的なモデルとして用いることを想定している。より複雑な症状や徴候を扱う場合には、「詳細記録」SLOTを用いて、それぞれに特有のデータエレメントを追加し、archetypeを拡張できる。 \n\n本archetypeは、OBSERVATION.story archetypeの「構造化された詳細記録」SLOTで使用することを想定して設計されている。他のOBSERVATIONやCLUSTER archetype内でも使用でき、同じCLUSTER.symptom_sign archetypeの別のインスタンスにある「随伴症状・徴候」SLOTや「過去のエピソード」SLOTにも組み込むことができる。",

  # Not to be used to record screening questionnaire responses about the presence or absence of specific symptoms - use the OBSERVATION.symptom_sign_screening archetype for this purpose. However, this CLUSTER.symptom_sign archetype may be nested within the 'Screening details' SLOT in the OBSERVATION.symptom_sign_screening archetype if it is necessary to extend the questionnaire by recording details about symptom or sign.
  # 
  # Not to be used to record that a symptom or sign was explicitly reported as not present - use CLUSTER.exclusion_symptom_sign carefully for specific purposes where the overheads of recording in this way warrant the additional complexity.
  # 
  # Not to be used for recording objective findings as part of a physical examination - use OBSERVATION.exam and related examination CLUSTER archetypes for this purpose.
  # 
  # Not to be used for diagnoses and problems that form part of a persisting Problem List - use EVALUATION.problem_diagnosis.
  # 
  # Not to be used to record a formal and repeatable severity scale such as VAS or NRS. Use appropriate OBSERVATION archetypes for this purpose.
  ['description', '-', 'misuse'] => "特定の症状の有無を尋ねるスクリーニング問診票への回答は、本archetypeではなく、OBSERVATION.symptom_sign_screening archetypeを用いて記録する。ただし、症状や徴候について詳しく記録できるように問診票を拡張する必要がある場合には、OBSERVATION.symptom_sign_screening archetypeの「スクリーニングの詳細」SLOTに、本CLUSTER.symptom_sign archetypeを組み込むことができる。\n\n症状や徴候がないと明確に伝えられたことを記録する場合には、本archetypeではなく、CLUSTER.exclusion_symptom_signを用いる。ただし、記録の負担や複雑さが増すことを考慮し、それに見合う必要性がある用途に限って慎重に使用する。\n\n身体診察で得られた客観的所見は、本archetypeではなく、OBSERVATION.examと関連する診察用のCLUSTER archetypeを用いて記録する。\n\n継続的に管理するプロブレムリストに含まれる診断やプロブレムは、本archetypeではなく、EVALUATION.problem_diagnosisを用いて記録する。\n\nVASやNRSなど、所定の方法で繰り返し評価できる重症度尺度による評価結果は、本archetypeではなく、適切なOBSERVATION archetypeを用いて記録する。",

  # complaint | symptom | disturbance | problem | discomfort | presenting complaint | presenting symptom | sign
  ['description', '-', 'keywords'] => "訴え | 症状 | 変調 | プロブレム | 不快 | 主訴 | 受診時の症状 | 徴候 | 症候 | 自覚症状",

  # © openEHR Foundation
  ['description', '-', 'copyright'] => "© openEHR Foundation",

  # CLUSTER
  # Symptom/Sign
  ['term', 'at0000', 'text'] => "症状・徴候",

  # CLUSTER
  # Reported observation of a physical or mental disturbance in an individual.
  ['term', 'at0000', 'description'] => "本人の心身の変調について、本人または他者が捉え、伝えた観察内容。",

  # CLUSTER > items/ELEMENT
  # Symptom/Sign name
  ['term', 'at0001', 'text'] => "症状・徴候の名称",

  # CLUSTER > items/ELEMENT
  # The name of the reported symptom or sign.
  ['term', 'at0001', 'description'] => "報告された症状または徴候の名称。",

  # CLUSTER > items/ELEMENT
  # Symptom name should be coded with a terminology, where possible.
  ['term', 'at0001', 'comment'] => "可能であれば、症状の名称は用語集によりコード化すべきである。",

  # CLUSTER > items/ELEMENT
  # Description
  ['term', 'at0002', 'text'] => "説明",

  # CLUSTER > items/ELEMENT
  # Narrative description about the reported symptom or sign.
  ['term', 'at0002', 'description'] => "報告された症状または徴候についての叙述的な記述。",

  # CLUSTER > items/ELEMENT
  # Pattern
  ['term', 'at0003', 'text'] => "パターン",

  # CLUSTER > items/ELEMENT
  # Narrative description about the pattern of the symptom or sign during this episode.
  ['term', 'at0003', 'description'] => "このエピソードにおける症状または徴候のパターンについての叙述的な記述。",

  # CLUSTER > items/ELEMENT
  # For example: pain could be described as constant or intermittent.
  ['term', 'at0003', 'comment'] => "例：疼痛は持続性または間欠性と記述されうる。",

  # CLUSTER > items/CLUSTER > items/ELEMENT
  # Effect
  ['term', 'at0017', 'text'] => "影響",

  # CLUSTER > items/CLUSTER > items/ELEMENT
  # Perceived effect of the modifying factor on the symptom or sign.
  ['term', 'at0017', 'description'] => "修飾因子が症状または徴候に及ぼすと認識された影響。",

  # CLUSTER > items/CLUSTER
  # Modifying factor
  ['term', 'at0018', 'text'] => "修飾因子",

  # CLUSTER > items/CLUSTER
  # Detail about how a specific factor effects the identified symptom or sign during this episode.
  ['term', 'at0018', 'description'] => "このエピソードにおいて、特定の因子が特定された症状または徴候にどのように影響するかについての詳細。",

  # CLUSTER > items/CLUSTER > items/ELEMENT
  # Factor
  ['term', 'at0019', 'text'] => "因子",

  # CLUSTER > items/CLUSTER > items/ELEMENT
  # Name of the modifying factor.
  ['term', 'at0019', 'description'] => "修飾因子の名称。",

  # CLUSTER > items/CLUSTER > items/ELEMENT
  # Examples of modifying factor: lying on multiple pillows, eating or administration of a specific medication.
  ['term', 'at0019', 'comment'] => "修飾因子の例：枕を複数重ねて横になること、食事、または特定の薬剤の投与。",

  # CLUSTER > items/ELEMENT
  # Severity category
  ['term', 'at0021', 'text'] => "重症度",

  # CLUSTER > items/ELEMENT
  # Category representing the overall severity of the symptom or sign.
  ['term', 'at0021', 'description'] => "症状または徴候の全体的な重症度を表す区分。",

  # CLUSTER > items/ELEMENT
  # Defining values such as mild, moderate or severe in such a way that is applicable to multiple symptoms or signs plus allows multiple users to interpret and record them consistently is not easy. Some organisations extend the value set further with inclusion of additional values such as 'Trivial' and 'Very severe', and/or 'Mild-Moderate' and 'Moderate-Severe', adds to the definitional difficulty and may also worsen inter-recorder reliability issues. Use of 'Life-threatening' and 'Fatal' is also often considered as part of this value set, although from a pure point of view it may actually reflect an outcome rather than a severity. In view of the above, keeping to a well-defined but smaller list is preferred and so the mild/moderate/severe value set is offered, however the choice of other text allows for other value sets to be included at this data element in a template.
  ['term', 'at0021', 'comment'] => "「軽症」「中等症」「重症」などの値を、さまざまな症状や徴候に適用でき、複数の利用者が一貫した基準で解釈・記録できるように定義するのは容易ではない。組織によっては、「ごく軽症」「非常に重症」や「軽症〜中等症」「中等症〜重症」などを加えて値セットを拡張している。しかし、選択肢を増やすと各値の定義がさらに難しくなり、記録者間で評価が一致しにくくなるおそれもある。「生命を脅かす」や「致死的」をこの値セットに含めることもよく検討されるが、厳密には、これらは重症度ではなく転帰を表している可能性がある。以上を踏まえ、各値の定義を明確にし、選択肢を少数に絞ることが望ましいため、本archetypeでは「軽症」「中等症」「重症」の値セットを用意している。ただし、これら以外のテキストも使用できるため、テンプレートではこのデータエレメントに別の値セットを設定することもできる。",

  # Mild
  ['term', 'at0023', 'text'] => "軽症",

  # The intensity of the symptom or sign does not cause interference with normal activity.
  ['term', 'at0023', 'description'] => "症状または徴候の強さは通常の活動を妨げない。",

  # Moderate
  ['term', 'at0024', 'text'] => "中等症",

  # The intensity of the symptom or sign causes interference with normal activity.
  ['term', 'at0024', 'description'] => "症状または徴候の強さは通常の活動を妨げる。",

  # Severe
  ['term', 'at0025', 'text'] => "重症",

  # The intensity of the symptom or sign causes prevents normal activity.
  ['term', 'at0025', 'description'] => "症状または徴候の強さは通常の活動を不可能にする。",

  # CLUSTER > items/ELEMENT
  # Episode duration
  ['term', 'at0028', 'text'] => "エピソードの持続期間",

  # CLUSTER > items/ELEMENT
  # The duration of this episode of the symptom or sign since initial onset.
  ['term', 'at0028', 'description'] => "症状または徴候の今回のエピソードにおける、発症からの持続期間。",

  # CLUSTER > items/ELEMENT
  # If 'Date/time of onset' and 'Date/time of resolution' are used in systems, this data element may be calculated, or alternatively, be considered redundant in this scenario. The text data type is used for recording preset duration intervals such as '0-7 days, 1-2 weeks, 2 weeks or more'.
  ['term', 'at0028', 'comment'] => "システムで「発症日時」と「消失日時」を使用している場合、このデータエレメントの値は両者から算出できる。そのため、冗長とみられることもある。テキストデータ型は、「0〜7日」「1〜2週」「2週以上」など、あらかじめ設定された期間区分を記録するために用いる。",

  # CLUSTER > items/ELEMENT
  # Number of previous episodes
  ['term', 'at0031', 'text'] => "過去のエピソードの回数",

  # CLUSTER > items/ELEMENT
  # The number of times this symptom or sign has previously occurred.
  ['term', 'at0031', 'description'] => "この症状または徴候が過去に生じた回数。",

  # CLUSTER > items/ELEMENT
  # Episode description
  ['term', 'at0037', 'text'] => "エピソードの説明",

  # CLUSTER > items/ELEMENT
  # Narrative description about the course of the symptom or sign during this episode.
  ['term', 'at0037', 'description'] => "このエピソードにおける症状または徴候の経過についての叙述的な記述。",

  # CLUSTER > items/ELEMENT
  # For example: a text description of the immediate onset of the symptom, activities that worsened or relieved the symptom, whether it is improving or worsening and how it resolved over weeks.
  ['term', 'at0037', 'comment'] => "例：発症直後の様子、症状を悪化または軽減させた活動、改善しているか悪化しているか、数週間かけてどのように消失したかについてのテキスト記述。",

  # CLUSTER > items/CLUSTER > items/ELEMENT
  # Description
  ['term', 'at0056', 'text'] => "説明",

  # CLUSTER > items/CLUSTER > items/ELEMENT
  # Narrative description of the effect of the modifying factor on the symptom or sign.
  ['term', 'at0056', 'description'] => "修飾因子が症状または徴候に及ぼす影響の叙述的な記述。",

  # CLUSTER > items/ELEMENT
  # Description of previous episodes
  ['term', 'at0057', 'text'] => "過去のエピソードの説明",

  # CLUSTER > items/ELEMENT
  # Narrative description of any or all previous episodes.
  ['term', 'at0057', 'description'] => "過去のエピソードのいずれかまたはすべてについての叙述的な記述。",

  # CLUSTER > items/ELEMENT
  # For example: frequency/periodicity - per hour, day, week, month, year; and regularity. May include a comparison to this episode.
  ['term', 'at0057', 'comment'] => "例：頻度／周期性 - 1時間、1日、1週、1か月、1年あたり；および規則性。このエピソードとの比較を含めてもよい。",

  # CLUSTER > items/CLUSTER
  # Associated symptom/sign
  ['term', 'at0063', 'text'] => "随伴症状・徴候",

  # CLUSTER > items/CLUSTER
  # Structured details about any associated symptoms or signs that are concurrent.
  ['term', 'at0063', 'description'] => "同時に生じている随伴症状または徴候についての構造化された詳細記録。",

  # CLUSTER > items/CLUSTER
  # In linked clinical systems, it is possible that associated symptoms or signs are already recorded within the EHR. Systems can allow the clinician to LINK to relevant associated symptoms/signs. However in a system or message without LINKs to existing data or with a new patient, additional instances of the symptom archetype could be included here to represent associated symptoms/signs.
  ['term', 'at0063', 'comment'] => "連携された臨床システムでは、随伴する症状や徴候がすでに EHR 内に記録されていることがある。システムは、臨床医が関連する随伴症状・徴候に LINK できるようにしてよい。しかし、既存データへの LINK を持たないシステムやメッセージ、あるいは新規の患者の場合には、随伴症状・徴候を表すために symptom archetypeの追加のインスタンスをここに含めることができる。",

  # CLUSTER > items/CLUSTER
  # Previous episodes
  ['term', 'at0146', 'text'] => "過去のエピソード",

  # CLUSTER > items/CLUSTER
  # Structured details of the symptom or sign during a previous episode.
  ['term', 'at0146', 'description'] => "過去のエピソードにおける症状または徴候の構造化された詳細記録。",

  # CLUSTER > items/CLUSTER
  # In linked clinical systems, it is possible that previous episodes are already recorded within the EHR. Systems can allow the clinician to LINK to relevant previous episodes. However in a system or message without LINKs to existing data or with a new patient, additional instances of the symptom archetype could be included here to represent previous episodes. It is recommended that new instances of the Symptom archetype inserted in this SLOT represent one or many previous episodes to this Symptom instance only.
  ['term', 'at0146', 'comment'] => "連携している臨床システムでは、過去のエピソードがすでに EHR 内に記録されていることがある。その場合、システムは、臨床医が関連する過去のエピソードへの LINK を設定する機能を提供できる。一方、既存データへの LINK がないシステムやメッセージ、あるいは新規患者の場合には、この SLOT に Symptom archetypeのインスタンスを追加して、過去のエピソードを記録できる。追加するインスタンスには、この SLOT を含む Symptom インスタンスに関連する過去のエピソードのみを、1つまたは複数記録することを推奨する。",

  # CLUSTER > items/CLUSTER
  # Structured body site
  ['term', 'at0147', 'text'] => "構造化された身体部位表現",

  # CLUSTER > items/CLUSTER
  # Structured body site where the symptom or sign was reported.
  ['term', 'at0147', 'description'] => "症状または徴候が報告された身体部位の構造化された表現。",

  # CLUSTER > items/CLUSTER
  # If the anatomical location is included in the Symptom name via precoordinated codes, use of this SLOT becomes redundant. If the anatomical location is recorded using the 'Body site' data element, then use of CLUSTER archetypes in this SLOT is not allowed - record only the simple 'Body site' OR 'Structured body site', but not both.
  ['term', 'at0147', 'comment'] => "解剖学的部位が事前調整されたコードによって症状の名称に含まれている場合、この SLOT を使用する必要はない。解剖学的部位を「身体部位」データエレメントで記録する場合、この SLOT での CLUSTER archetypeの使用は許可されない。単純な「身体部位」または「構造化された身体部位表現」のどちらか一方だけを記録し、両方は記録しない。",

  # CLUSTER > items/ELEMENT
  # Body site
  ['term', 'at0151', 'text'] => "身体部位",

  # CLUSTER > items/ELEMENT
  # Simple body site where the symptom or sign was reported.
  ['term', 'at0151', 'description'] => "症状または徴候があると報告された身体部位の簡潔な記述。",

  # CLUSTER > items/ELEMENT
  # Occurrences of this data element are set to 0..* to allow multiple body sites to be separated out in a template if desired. This allows for representation of clinical scenarios where a symptom or sign needs to be recorded in multiple locations or identifying both the originating and distal site in pain radiation, but where all of the other attributes such as impact and duration are identical. If the requirements for recording the body site are determined at run-time by the application or require more complex modelling such as relative locations then use the CLUSTER.anatomical_location or CLUSTER.relative_location within the Detailed anatomical location' SLOT in this archetype. 
  # If the anatomical location is included in the Symptom name via precoordinated codes, this data element becomes redundant. If the anatomical location is recorded using the 'Structured body site' SLOT, then use of this data element is not allowed - record only the simple 'Body site' OR 'Structured body site', but not both.
  ['term', 'at0151', 'comment'] => "このデータエレメントの出現回数は 0..* に設定されており、必要に応じてテンプレートで複数の身体部位を分けて表せる。これにより、症状や徴候を複数の部位に記録する必要がある臨床シナリオや、放散痛の起始部位と遠位部位の両方を特定するが、影響や持続期間などの他の属性はすべて同一であるシナリオを表現できる。身体部位の記録要件がアプリケーションによって実行時に決定される場合や、相対的な位置関係などより複雑なモデリングが必要な場合は、本archetypeの「詳細な解剖学的部位」SLOT 内で CLUSTER.anatomical_location または CLUSTER.relative_location を用いること。 \n解剖学的部位が事前調整されたコードによって症状の名称に含まれている場合、このデータエレメントは冗長になる。解剖学的部位を「構造化された身体部位表現」SLOT で記録する場合、このデータエレメントの使用は許可されない。単純な「身体部位」または「構造化された身体部位表現」のどちらか一方だけを記録し、両方は記録しない。",

  # CLUSTER > items/ELEMENT
  # Episode onset
  ['term', 'at0152', 'text'] => "エピソードの発症日時",

  # CLUSTER > items/ELEMENT
  # The onset for this episode of the symptom or sign.
  ['term', 'at0152', 'description'] => "症状または徴候のこのエピソードの発症。",

  # CLUSTER > items/ELEMENT
  # While partial dates are permitted, the exact date and time of onset can be recorded, if appropriate. If this symptom or sign is experienced for the first time or is a re-occurrence, this date is used to represent the onset of this episode. If this symptom or sign is ongoing, this data element may be redundant if it has been recorded previously.
  ['term', 'at0152', 'comment'] => "部分的な日付も記録できるが、適切であれば発症の正確な日時を記録できる。初発・再発のいずれの場合も、この日付は今回のエピソードの発症時点を表す。症状または徴候が継続しており、発症日時がすでに記録されている場合、このデータエレメントは冗長とみられることがある。",

  # CLUSTER > items/CLUSTER
  # Specific details
  ['term', 'at0153', 'text'] => "詳細記録",

  # CLUSTER > items/CLUSTER
  # Specific data elements that are additionally required to record as unique attributes of the identified symptom or sign.
  ['term', 'at0153', 'description'] => "特定された症状または徴候に固有の属性として、追加で記録する必要がある特定のデータエレメント。",

  # CLUSTER > items/CLUSTER
  # For example: CTCAE grading.
  ['term', 'at0153', 'comment'] => "例：CTCAE のグレード分類。",

  # CLUSTER > items/CLUSTER > items/CLUSTER
  # Factor detail
  ['term', 'at0154', 'text'] => "因子の詳細",

  # CLUSTER > items/CLUSTER > items/CLUSTER
  # Structured detail about the factor associated with the identified symptom or sign.
  ['term', 'at0154', 'description'] => "特定された症状または徴候に関連する因子についての構造化された詳細記録。",

  # CLUSTER > items/ELEMENT
  # Impact
  ['term', 'at0155', 'text'] => "影響",

  # CLUSTER > items/ELEMENT
  # Description of the impact of this symptom or sign.
  ['term', 'at0155', 'description'] => "この症状または徴候の影響の記述。",

  # CLUSTER > items/ELEMENT
  # Assessment of impact could consider the severity, duration and frequency of the symptom as well as the type of impact including, but not limited to, functional, social and emotional impact. Occurrences of this data element are set to 0..* to allow multiple types of impact to be separated out in a template if desired. Examples for functional impact from hearing loss may include: 'Difficulty Hearing in Quiet Environment'; 'Difficulty Hearing the TV or Radio'; 'Difficulty Hearing Group Conversation'; and 'Difficulty Hearing on Phone'.
  ['term', 'at0155', 'comment'] => "影響の評価では、症状の重症度、持続期間、頻度に加え、機能面、社会面、情緒面など、影響が及ぶ側面も考慮できる。必要に応じてテンプレート内で影響を種類ごとに分けて表せるよう、このデータエレメントの出現回数は 0..* に設定されている。難聴による機能面への影響の例としては、「静かな環境で聞き取りにくい」「テレビやラジオの音声を聞き取りにくい」「複数人での会話を聞き取りにくい」「電話で聞き取りにくい」などが挙げられる。",

  # No effect
  ['term', 'at0156', 'text'] => "影響なし",

  # The factor has no impact on the symptom or sign.
  ['term', 'at0156', 'description'] => "その因子は症状または徴候に影響を及ぼさない。",

  # Worsens
  ['term', 'at0158', 'text'] => "増悪",

  # The factor increases the severity or impact of the symptom or sign.
  ['term', 'at0158', 'description'] => "その因子は症状または徴候の重症度または影響を増大させる。",

  # Relieves
  ['term', 'at0159', 'text'] => "軽減",

  # The factor decreases the severity or impact of the symptom or sign, but does not fully resolve it.
  ['term', 'at0159', 'description'] => "その因子は症状または徴候の重症度または影響を軽減させるが、完全には消失させない。",

  # CLUSTER > items/ELEMENT
  # Resolution date/time
  ['term', 'at0161', 'text'] => "消失日時",

  # CLUSTER > items/ELEMENT
  # The timing of the cessation of this episode of the symptom or sign.
  ['term', 'at0161', 'description'] => "症状または徴候のこのエピソードが消失した時期。",

  # CLUSTER > items/ELEMENT
  # If 'Date/time of onset' and 'Duration' are used in systems, this data element may be calculated, or alternatively, considered redundant. While partial dates are permitted, the exact date and time of resolution can be recorded, if appropriate.
  ['term', 'at0161', 'comment'] => "システムで「発症日時」と「持続期間」を使う場合、このデータエレメントは計算で求められるか、あるいは冗長とみられることがある。部分的な日付も許容されるが、適切であれば消失の正確な日時を記録できる。",

  # CLUSTER > items/ELEMENT
  # Comment
  ['term', 'at0163', 'text'] => "コメント",

  # CLUSTER > items/ELEMENT
  # Additional narrative about the symptom or sign not captured in other fields.
  ['term', 'at0163', 'description'] => "他の項目では捉えられない、症状または徴候についての追加の記述。",

  # CLUSTER > items/ELEMENT
  # Onset timing
  ['term', 'at0164', 'text'] => "発症時期",

  # CLUSTER > items/ELEMENT
  # Timing of the onset and development of the symptom or sign.
  ['term', 'at0164', 'description'] => "症状または徴候の発症と進展のタイミング。",

  # CLUSTER > items/ELEMENT
  # The type of the onset can be coded with a terminology, if desired. For example: gradual; or sudden.
  ['term', 'at0164', 'comment'] => "発症の型は、必要に応じて用語集によりコード化できる。例：緩徐；または突発。",

  # CLUSTER > items/CLUSTER
  # Precipitating factor
  ['term', 'at0165', 'text'] => "誘発因子",

  # CLUSTER > items/CLUSTER
  # Details about specified factors that are associated with the precipitation of the symptom or sign.
  ['term', 'at0165', 'description'] => "症状または徴候の誘発に関連する特定の因子についての詳細。",

  # CLUSTER > items/CLUSTER
  # For example: lying down leads to heartburn; or walking up a hill leads to claudication.
  ['term', 'at0165', 'comment'] => "例：横になると胸やけが生じる；または坂を上ると跛行が生じる。",

  # CLUSTER > items/CLUSTER > items/ELEMENT
  # Factor
  ['term', 'at0170', 'text'] => "因子",

  # CLUSTER > items/CLUSTER > items/ELEMENT
  # Name of the health event, symptom, reported sign or other factor.
  ['term', 'at0170', 'description'] => "健康イベント、症状、報告された徴候、またはその他の因子の名称。",

  # CLUSTER > items/CLUSTER > items/ELEMENT
  # For example: onset of another symptom; lying down; or walking up a hill.
  ['term', 'at0170', 'comment'] => "例：別の症状の発症；横になること；または坂を上ること。",

  # CLUSTER > items/CLUSTER > items/ELEMENT
  # Time interval
  ['term', 'at0171', 'text'] => "時間間隔",

  # CLUSTER > items/CLUSTER > items/ELEMENT
  # The interval of time between the occurrence or onset of the factor and onset of the symptom or sign.
  ['term', 'at0171', 'description'] => "因子の発生または発症から、症状または徴候の発症までの時間間隔。",

  # CLUSTER > items/ELEMENT
  # Episodicity
  ['term', 'at0175', 'text'] => "エピソード区分",

  # CLUSTER > items/ELEMENT
  # Category of this episode for the identified symptom or sign.
  ['term', 'at0175', 'description'] => "特定された症状または徴候における、このエピソードの区分。",

  # New
  ['term', 'at0176', 'text'] => "新規",

  # A new episode of the symptom or sign - either the first ever occurrence or a reoccurrence where the previous episode had completely resolved.
  ['term', 'at0176', 'description'] => "症状または徴候の新しいエピソード。初発、または以前のエピソードが完全に消失した後の再発のいずれか。",

  # Indeterminate
  ['term', 'at0177', 'text'] => "判定不能",

  # It is not possible to determine if this occurrence of the symptom or sign is new or ongoing.
  ['term', 'at0177', 'description'] => "この症状または徴候の今回の発生が新規か継続中かを判定できない。",

  # Ongoing
  ['term', 'at0178', 'text'] => "継続中",

  # This symptom or sign is ongoing, effectively a single, continuous episode.
  ['term', 'at0178', 'description'] => "この症状または徴候は継続しており、実質的に単一の連続したエピソードである。",

  # CLUSTER > items/ELEMENT
  # Progression
  ['term', 'at0180', 'text'] => "進行状況",

  # CLUSTER > items/ELEMENT
  # Description progression of the symptom or sign at the time of reporting.
  ['term', 'at0180', 'description'] => "報告時点における症状または徴候の進行状況の記述。",

  # CLUSTER > items/ELEMENT
  # Occurrences of this data element are set to 0..* to allow multiple types of progression to be separated out in a template if desired - for example, severity or frequency. The Text data type is added as an option, to support other value sets than the ones included in the archetype.
  ['term', 'at0180', 'comment'] => "このデータエレメントの出現回数は 0..* に設定されており、必要に応じてテンプレートで複数の種類の進行状況（例えば重症度や頻度）を分けて表せる。archetypeに含まれる値セット以外の値セットに対応するため、テキストデータ型が選択肢として追加されている。",

  # Improving
  ['term', 'at0181', 'text'] => "改善",

  # The severity of the symptom or sign has improved overall during this episode.
  ['term', 'at0181', 'description'] => "このエピソードの間に、症状または徴候の重症度は全体として改善した。",

  # Unchanged
  ['term', 'at0182', 'text'] => "不変",

  # The severity of the symptom or sign has not changed overall during this episode.
  ['term', 'at0182', 'description'] => "このエピソードの間に、症状または徴候の重症度は全体として変化していない。",

  # Worsening
  ['term', 'at0183', 'text'] => "悪化",

  # The severity of the symptom or sign has worsened overall during this episode.
  ['term', 'at0183', 'description'] => "このエピソードの間に、症状または徴候の重症度は全体として悪化した。",

  # Resolved
  ['term', 'at0184', 'text'] => "消失",

  # The severity of the symptom or sign has resolved.
  ['term', 'at0184', 'description'] => "症状または徴候は消失した。",

  # CLUSTER > items/CLUSTER > items/ELEMENT
  # Description
  ['term', 'at0185', 'text'] => "説明",

  # CLUSTER > items/CLUSTER > items/ELEMENT
  # Narrative description about the effect of the factor on the identified symptom or sign.
  ['term', 'at0185', 'description'] => "因子が特定された症状または徴候に及ぼす影響についての叙述的な記述。",

  # CLUSTER > items/ELEMENT
  # Occurrence
  ['term', 'at0186', 'text'] => "発生区分",

  # CLUSTER > items/ELEMENT
  # Type of occurrence for this symptom or sign?
  ['term', 'at0186', 'description'] => "この症状または徴候の発生の種類。",

  # First occurrence
  ['term', 'at0187', 'text'] => "初発",

  # This is the first ever occurrence of this symptom or sign.
  ['term', 'at0187', 'description'] => "この症状または徴候の、初めての発生である。",

  # Recurrence
  ['term', 'at0188', 'text'] => "再発",

  # New occurrence of the same symptom or sign after a previous episode was resolved.
  ['term', 'at0188', 'description'] => "以前のエピソードが消失した後の、同じ症状または徴候の新たな発生。",

  # CLUSTER > items/ELEMENT
  # Character
  ['term', 'at0189', 'text'] => "性状",

  # CLUSTER > items/ELEMENT
  # Word or short phrase describing the nature of the symptom or sign.
  ['term', 'at0189', 'description'] => "症状または徴候の性質を表す語または短い句。",

  # CLUSTER > items/ELEMENT
  # For example: pain could be described as 'gnawing', 'burning', or 'like an electric shock'; a headache could be 'throbbing' or 'constant'. Coding with an external terminology is preferred, where possible.
  ['term', 'at0189', 'comment'] => "例：疼痛は「うずくような」「灼けるような」「電気が走るような」と記述されうる；頭痛は「拍動性」または「持続性」でありうる。可能であれば、外部用語集によりコード化することが望ましい。",

  # CLUSTER > items/CLUSTER
  # Resolving factor
  ['term', 'at0190', 'text'] => "寛解因子",

  # CLUSTER > items/CLUSTER
  # Details about specified factors that are associated with the resolution of the symptom or sign.
  ['term', 'at0190', 'description'] => "症状または徴候の消失に関連する特定の因子についての詳細。",

  # CLUSTER > items/CLUSTER
  # For example: upright posture stops heartburn; or resting stops claudication.
  ['term', 'at0190', 'comment'] => "例：直立姿勢で胸やけが止まる；または休息で跛行が止まる。",

  # CLUSTER > items/CLUSTER > items/ELEMENT
  # Factor
  ['term', 'at0193', 'text'] => "因子",

  # CLUSTER > items/CLUSTER > items/ELEMENT
  # Name of the health event, symptom, reported sign or other factor.
  ['term', 'at0193', 'description'] => "健康イベント、症状、報告された徴候、またはその他の因子の名称。",

  # CLUSTER > items/CLUSTER > items/ELEMENT
  # For example: upright posture; or resting.
  ['term', 'at0193', 'comment'] => "例：直立姿勢；または休息。",

  # CLUSTER > items/CLUSTER > items/CLUSTER
  # Factor detail
  ['term', 'at0194', 'text'] => "因子の詳細",

  # CLUSTER > items/CLUSTER > items/CLUSTER
  # Structured detail about the factor associated with the identified symptom or sign.
  ['term', 'at0194', 'description'] => "特定された症状または徴候に関連する因子についての構造化された詳細記録。",

  # CLUSTER > items/CLUSTER > items/ELEMENT
  # Time interval
  ['term', 'at0195', 'text'] => "時間間隔",

  # CLUSTER > items/CLUSTER > items/ELEMENT
  # The interval of time between the occurrence or onset of the factor and resolution of the symptom or sign.
  ['term', 'at0195', 'description'] => "因子の発生または発症から、症状または徴候の消失までの時間間隔。",

  # CLUSTER > items/CLUSTER > items/ELEMENT
  # Description
  ['term', 'at0196', 'text'] => "説明",

  # CLUSTER > items/CLUSTER > items/ELEMENT
  # Narrative description about the effect of the factor on the identified symptom or sign.
  ['term', 'at0196', 'description'] => "因子が特定された症状または徴候に及ぼす影響についての叙述的な記述。",

  # CLUSTER > items/CLUSTER > items/CLUSTER
  # Factor detail
  ['term', 'at0197', 'text'] => "因子の詳細",

  # CLUSTER > items/CLUSTER > items/CLUSTER
  # Structured detail about the factor associated with the identified symptom or sign.
  ['term', 'at0197', 'description'] => "特定された症状または徴候に関連する因子についての構造化された詳細記録。",

  # CLUSTER > items/CLUSTER
  # Severity rating
  ['term', 'at0198', 'text'] => "重症度評価",

  # CLUSTER > items/CLUSTER
  # Numerical rating scale representing the overall severity of the symptom or sign.
  ['term', 'at0198', 'description'] => "症状または徴候の全体的な重症度を表す数値評価スケール。",

  # CLUSTER > items/CLUSTER
  # Symptom severity can be rated by the individual by recording a score for example from 0 (ie symptom not present) to 10 (ie symptom is as severe as the individual can imagine).
  ['term', 'at0198', 'comment'] => "症状の重症度は、例えば 0（症状なし）から 10（本人が想像しうる最も重い症状）までのスコアを記録することで、本人が評価できる。",

  # CLUSTER > items/ELEMENT
  # Nadir
  ['term', 'at0200', 'text'] => "最悪時",

  # CLUSTER > items/ELEMENT
  # Date/time when a monophasic, progressive symptom or sign reached its' maximal intensity or functional impact.
  ['term', 'at0200', 'description'] => "単相性で進行性の症状または徴候が、最大の強さまたは機能的に最悪の影響に達した日時。",

  # CLUSTER > items/ELEMENT
  # For example: the date when neurological signs in Guillain-Barre disease was at its worst.
  ['term', 'at0200', 'comment'] => "例：ギラン・バレー症候群の神経学的徴候が最も悪化した日。",

}.freeze

# note 列に残すメモ。迷った訳語には '要確認: ...' を付ける。
NOTES = {
  ['term', 'at0164', 'text'] => "要確認: 「発症時期」（指示の候補。他候補: 発症のタイミング）",
  ['term', 'at0165', 'text'] => "要確認: Precipitating factor＝「誘発因子」",
  ['term', 'at0182', 'text'] => "要確認: Unchanged＝「不変」（qualifier の Stable＝安定 とは別語）",
  ['term', 'at0189', 'text'] => "要確認: 「性状」（指示の候補）",
  ['term', 'at0190', 'text'] => "要確認: Resolving factor＝「寛解因子」を採用（OPQRST の増悪・寛解因子の慣用。他候補: 解消因子、治癒因子）。description では resolution＝消失",
  ['term', 'at0198', 'text'] => "要確認: 「重症度評価」を採用（他候補: 重症度スコア、重症度スケール）",
}.freeze

src, dst = ARGV
lines = File.readlines(src, chomp: true)
out = [lines.shift]
lines.each do |l|
  c = l.split("\t", -1)
  key = c[1..3]
  c[6] = T.fetch(key).gsub("\n", '\n')
  c[7] = NOTES[key] || ''
  out << c.join("\t")
end
File.write(dst, out.join("\n") + "\n")
