# frozen_string_literal: true
# Japanese translation for openEHR-EHR-CLUSTER.organisation.v1
# Generated by tools/scaffold_fill.rb - fill every empty string, following glossary-ja.md.
# Human proofreading: edit work/openEHR-EHR-CLUSTER.organisation.v1.ja.tsv and run `make import ID=openEHR-EHR-CLUSTER.organisation.v1` (regenerates this file).

T = {
  # To record details about an organisation as they are known or understood in the course of clinical documentation.
  ['description', '-', 'purpose'] => "臨床記録の作成に際して取得した、組織に関する詳細情報を記録するため。",

  # Use to record details of an organisation as they are known or understood in the course of clinical documentation, often ad hoc or when it is not appropriate or possible to use a formal demographic register or index. Examples include:
  # - the copyholder of an advanced care record, using the 'Copyholder' SLOT within the EVALUATION.advance_care_directive archetype; or
  # - the name and contact details of an organisation providing home care to an individual.
  # 
  # This archetype has been designed to carry details of formally recognised entities, such as a registered business, a hospital and its recognised 'sub-organisations', such as an operationally separate or specialised satellite clinic or home care service. It may also be used to carry contact information about more informal networks or groups, such as a local community support group.
  # 
  # This archetype could also be used as a proxy for formal demographic data when reviewing a template with domain experts - for example, an assessment where reviewers would expect to see an organisations' details on an assessment form.
  ['description', '-', 'use'] => "臨床記録の作成に際して取得した、組織に関する詳細情報を記録するために用いる。主に、必要に応じて情報を記録する場合や、正式なデモグラフィック登録簿やインデックスの利用が適切でない、または利用できない場合を想定している。以下のような使用例がある。\n- EVALUATION.advance_care_directive archetypeの「写し保有者」SLOTを用いて、事前ケア記録の写しを保有する組織の情報を記録する；または\n- 個人に在宅ケアを提供する組織の名称と連絡先を記録する。\n\n本archetypeは、登録された事業者や病院、病院の正式な「下部組織」など、正式に認められた組織の詳細情報を記録するために設計されている。下部組織には、運営上独立した分院や専門分野に特化した分院、在宅ケアサービスなどがある。また、地域の支援団体など、より非公式なネットワークや集団の連絡先情報を記録するためにも使用できる。\n\n本archetypeは、対象領域の専門家とテンプレートをレビューする際に、正式なデモグラフィックデータの代用として使用することもできる。例えば、評価票の冒頭に組織の詳細情報が表示されることをレビュー担当者が想定している場合に、その情報を示すために用いる。",

  # Not to be used to represent, replace or maintain an official register or index. Use a formal Health Provider Index for this purpose, or archetypes based on the openEHR Demographic Information Model.
  # 
  # Not to be used to represent the location of care and similar data elements that should be represented formally in the health record using the Reference Model attributes.
  ['description', '-', 'misuse'] => "公式の登録簿やインデックスの表現やその代替、または維持・管理に用いてはならない。これらの目的には、正式な「医療従事者名簿（Health Provider Index）」、またはopenEHRデモグラフィック情報モデルに基づくarchetypeを用いること。\n\nケアの実施場所など、参照モデルの属性を用いて健康記録に正式に記録すべき情報を、本archetypeで記録してはならない。",

  # organisation, organization, provider, carer, network, group
  ['description', '-', 'keywords'] => "組織 | 医療提供者 | 介護者 | ネットワーク | 集団",

  # © openEHR Foundation
  ['description', '-', 'copyright'] => "© openEHR Foundation",

  # CLUSTER
  # Organisation
  ['term', 'at0000', 'text'] => "組織",

  # CLUSTER
  # An entity comprising one or more people and having a particular purpose.
  ['term', 'at0000', 'description'] => "1人以上で構成され、特定の目的を持つ組織。",

  # CLUSTER
  # For example: a company, institution, association, network, department, community group, healthcare practice group, payer/insurer, care team, or a group of neighbours who provide care or support.
  ['term', 'at0000', 'comment'] => "例：企業、機関、協会、ネットワーク、部門、地域団体、診療グループ、支払者・保険者、ケアチーム、またはケアや支援を提供する近隣住民の集まり。",

  # CLUSTER > items/ELEMENT
  # Name
  ['term', 'at0001', 'text'] => "名称",

  # CLUSTER > items/ELEMENT
  # The unstructured name or label for the organisation.
  ['term', 'at0001', 'description'] => "組織の名称またはラベル（非構造情報）。",

  # CLUSTER > items/ELEMENT
  # For example: 'Royal Children's Hospital'; 'ABC District Nursing Service'; 'YNWA Oslo' or 'JB Smith Lawyers'.
  ['term', 'at0001', 'comment'] => "例：「Royal Children's Hospital」、「ABC District Nursing Service」、「YNWA Oslo」、または「JB Smith Lawyers」。",

  # CLUSTER > items/CLUSTER
  # Contact person
  ['term', 'at0002', 'text'] => "連絡担当者",

  # CLUSTER > items/CLUSTER
  # Details about one or more people within the organisation.
  ['term', 'at0002', 'description'] => "組織内の1人以上の人に関する詳細情報。",

  # CLUSTER > items/ELEMENT
  # Identifier
  ['term', 'at0003', 'text'] => "識別子",

  # CLUSTER > items/ELEMENT
  # Identifier associated with the organisation.
  ['term', 'at0003', 'description'] => "組織に関連付けられた識別子。",

  # CLUSTER > items/ELEMENT
  # Occurrences for this data element is set to 0..* to allow for more than one Identifier to be recorded. Note that the ID data type contains multiple subcomponents for recording the ID value, type, issuer and assigner.
  ['term', 'at0003', 'comment'] => "このデータエレメントの出現回数は 0..* に設定されており、複数の識別子を記録できる。ID データ型には、ID の値、種類、発行者、割り当て先を記録する複数の下位要素がある点に注意。",

  # CLUSTER > items/ELEMENT
  # Role
  ['term', 'at0004', 'text'] => "役割",

  # CLUSTER > items/ELEMENT
  # The relationship or role of the organisation to the individual or subject of care.
  ['term', 'at0004', 'description'] => "個人またはケア対象者に対する組織の関係または役割。",

  # CLUSTER > items/ELEMENT
  # For example: oncologist; palliative care home nursing service; or informal support network.
  ['term', 'at0004', 'comment'] => "例：腫瘍専門医、緩和ケアの訪問看護サービス、または非公式な支援ネットワーク。",

  # CLUSTER > items/CLUSTER
  # Address
  ['term', 'at0005', 'text'] => "住所",

  # CLUSTER > items/CLUSTER
  # Details about an address for the organisation.
  ['term', 'at0005', 'description'] => "組織の詳細な住所。",

  # CLUSTER > items/CLUSTER
  # Additional details
  ['term', 'at0017', 'text'] => "追加の詳細情報",

  # CLUSTER > items/CLUSTER
  # Additional details about the organisation.
  ['term', 'at0017', 'description'] => "組織に関する追加の詳細情報。",

  # CLUSTER > items/ELEMENT
  # Comment
  ['term', 'at0019', 'text'] => "コメント",

  # CLUSTER > items/ELEMENT
  # Additional narrative about the organisation not captured in other fields.
  ['term', 'at0019', 'description'] => "他の項目には収まらない組織についての追加の記述。",

  # CLUSTER > items/CLUSTER
  # Parent organisation
  ['term', 'at0021', 'text'] => "親組織",

  # CLUSTER > items/CLUSTER
  # A larger organisation of which this organisation is a child or subsidiary.
  ['term', 'at0021', 'description'] => "この組織を下部組織または子会社として含む、より大きな組織。",

  # CLUSTER > items/CLUSTER
  # Electronic communication
  ['term', 'at0022', 'text'] => "電子的な連絡先",

  # CLUSTER > items/CLUSTER
  # Details about one or more types of electronic communication for the organisation.
  ['term', 'at0022', 'description'] => "組織の電子的な連絡先（1種類以上）の詳細情報。",

}.freeze

# note 列に残すメモ。迷った訳語には '要確認: ...' を付ける。
NOTES = {
  ['term', 'at0021', 'text'] => "要確認: 親組織（他候補: 上位組織）企業に限らず、部門やケアチーム等の上位にある組織も含むため。",
  ['description', '-', 'use'] => "要確認: 下部組織、分院、登録された事業者、地域の支援団体（他候補: 傘下組織、サテライト診療所、登記事業者、地域の相互扶助団体）正式な組織と非公式な集まりの両方を含め、特定の法人形態に限定しない訳を採用。",
  ['term', 'at0000', 'comment'] => "要確認: 診療グループ、支払者、保険者（他候補: 診療団体、費用負担者、保険事業者）組織の例示として、日本の特定の法人形態や支払制度に限定しない訳を採用。",
  ['term', 'at0004', 'comment'] => "要確認: 腫瘍専門医、緩和ケアの訪問看護サービス、非公式な支援ネットワーク（他候補: 腫瘍医、緩和ケアの在宅看護サービス、インフォーマルな支援ネットワーク）oncologist は組織の役割の例示としては人の呼称だが原文を保持。home nursing は訪問看護と解釈。",
  ['description', '-', 'misuse'] => "要確認: ケアの実施場所（他候補: ケア提供場所）参照モデルの属性で表す場所を指す。person.v1 と異なり、原文には患者マスターインデックスやケア対象者等の例示はないため含めない。",
  ['description', '-', 'keywords'] => "要確認: ネットワーク、集団（他候補: つながり、グループ）正式な組織に限らない人のつながりや集まりも含むため。",
}.freeze

src, dst = ARGV
lines = File.readlines(src, chomp: true)
out = [lines.shift]
lines.each do |l|
  c = l.split("\t", -1)
  key = c[1..3]
  c[6] = T.fetch(key).gsub("\n", '\n')
  c[7] = NOTES[key] || ''
  out << c.join("\t")
end
File.write(dst, out.join("\n") + "\n")
