# frozen_string_literal: true
# Japanese translation for openEHR-EHR-INSTRUCTION.medication_order.v3
# Generated by tools/scaffold_fill.rb - fill every empty string, following glossary-ja.md.
# Human proofreading: edit work/openEHR-EHR-INSTRUCTION.medication_order.v3.ja.tsv and run `make import ID=openEHR-EHR-INSTRUCTION.medication_order.v3` (regenerates this file).

T = {
  # To record all aspects of an order of a medication, vaccine, nutritional product or other therapeutic item for an identified individual.
  ['description', '-', 'purpose'] => "特定された本人に対する薬剤、ワクチン、栄養製品、その他の治療用品のオーダーについて、すべての側面を記録するため。",

  # Use to record all aspects of an order of a medication, vaccine, nutritional product or other therapeutic item for an identified individual.
  # 
  # It is intended to be used for any type of medication and related order, whether prescribed by a health professional or available for purchase 'over the counter'. The scope of this medication archetype also includes orders for vaccinations, parenteral fluids or other therapeutic goods, such as bandages, nutritional products or other items that are applied or administered to have a therapeutic effect and which have a common pattern for data recording.
  # 
  # This archetype is designed to be used in a number of clinical contexts, including but not limited to:
  # - a record in a clinical consultation (COMPOSITION.encounter);
  # - a written prescription by a physician, dentist, nurse practitioner, or other designated health professional for a medication or nutritional product to be dispensed and administered (within a COMPOSITION.prescription);
  # - an item in a current medication list, prescription or drug chart (within COMPOSITION.medication_list); and
  # - an item in a summary document such as transfer of care (COMPOSITION.transfer_summary) or a referral (COMPOSITION.request).
  # 
  # In many cases a medication order will be simple – typically for a single medication item with uncomplicated instructions for dispensing and administration. However this archetype is also designed to allow for more complex therapeutic orders. For example:
  # 
  # - a reducing dose of prednisolone over a period of weeks;
  # - titration of insulin, with dosing dependent on test results;
  # - multiple medications prescribed simultaneously as part of a single drug regimen, such as a triple therapy for peptic ulcer; and
  # - intravenous administration of medications or nutrition supplements, including parenteral nutrition.
  # 
  # The archetype has therefore been designed to allow for a range of complexity, from:
  # - simple narrative instructions for orders like 'furosemide 40mg two tablets in the morning and one at lunch' to ensure compatibility with existing systems; and
  # - the amount of medication is usually represented in terms of a number and corresponding dose unit, however there can alternatively be a narrative statement to ensure compatibility with existing systems and coverage of all clinical scenarios; through to
  # - structured detail for dose, route and timing to represent a fully computable specification.
  # 
  # It has also been designed so that a single medication order structure can represent:
  # - complex sequential medication orders using the same preparation strength to be supported within a single order structure; and
  # - multiple medication orders can be chained in circumstances where different medications or preparations need to be given sequentially.
  # 
  # This archetype is also suitable for ordering parenteral fluids, in care settings where it is normal practice to make these 'prescribable' items. In other settings a separate 'parenteral fluid order' may be appropriate.
  # 
  # SLOTs containing CLUSTER archetypes have been used to represent some of the content for three reasons:
  # - To ensure a core archetype that can be used for all the above use cases, yet allow flexibility where it is required, for example the ‘Preparation details’ SLOT where additional structured detail can be added. A candidate archetype has been suggested for Medications. It is possible that other CLUSTER archetypes may be required in future for other purposes such as complex parenteral nutrition orders;
  # - to support archetype re-use in situations where the content has been identified as being also used in other clinical contexts, in particular the paired ACTION.medication archetype for recording actual dispensing, administration etc; and
  # - to remove less commonly used content from the core archetype framework.
  # 
  # Multiple orders can be represented as separate activities within this single archetype instance to carry tightly bound orders of different medications, for example, H. pylori therapy when this is not prescribed as a single pack.
  # 
  # It should be noted that these uses subsume both the FHIR Medication Order and Medication Statement use cases. i.e this archetype is a match for both FHIR resources, used in the appropriate context.
  ['description', '-', 'use'] => "特定された本人に対する薬剤、ワクチン、栄養製品、その他の治療用品のオーダーについて、すべての側面を記録するために用いる。\n\n医療従事者が処方するものから一般用医薬品（OTC）として購入できるものまで、あらゆる種類の薬剤と関連するオーダーに用いることを想定している。本archetypeの対象には、ワクチン接種、非経口輸液、その他の治療用品のオーダーも含まれる。治療用品には包帯や栄養製品などがあり、治療効果を得るために使用または投与され、共通のデータ記録パターンを持つものを扱う。\n\n本archetypeは、以下を含むさまざまな臨床の文脈で使うよう設計されている：\n- 診察時の記録（COMPOSITION.encounter）に用いる。\n- 医師、歯科医師、ナースプラクティショナー、その他の指定された医療従事者が、調剤・投与する薬剤や栄養製品について書く処方箋（COMPOSITION.prescription 内）に用いる。\n- 現在の薬剤リスト、処方箋、投薬指示簿の項目（COMPOSITION.medication_list 内）に用いる。\n- 診療の引き継ぎ（COMPOSITION.transfer_summary）や紹介（COMPOSITION.request）などのサマリー文書の項目に用いる。\n\n薬剤オーダーの多くは単純であり、通常は単一の薬剤に対する簡単な調剤・投与の指示である。ただし、本archetypeはより複雑な治療のオーダーにも対応できるよう設計されている。例：\n\n- 数週間かけてプレドニゾロンを漸減する。\n- 検査結果に応じて投与量を決め、インスリンの用量調節（漸増）を行う。\n- 消化性潰瘍の三剤併用療法のように、単一の薬剤レジメンの一部として複数の薬剤を同時に処方する。\n- 経静脈栄養を含め、薬剤や栄養補助製品を静脈内に投与する。\n\nこのため、本archetypeは以下のように、単純な記述から複雑な構造化表現まで扱えるよう設計されている：\n- 既存システムとの互換性を確保するため、「フロセミド40mg錠を朝2錠、昼1錠」のようなオーダーの指示を簡単な文章で記録する。\n- 薬剤の量は通常、数値と対応する用量単位で表すが、既存システムとの互換性を確保し、あらゆる臨床シナリオに対応するため、文章で記録することもできる。\n- 用量、投与経路、タイミングを構造化して詳しく記録し、すべてをコンピュータで処理できる仕様として表す。\n\nまた、単一の薬剤オーダー構造で、以下を表せるよう設計されている：\n- 同じ含量の製剤を用いる複雑な一連の薬剤オーダーを、単一のオーダー構造内で扱う。\n- 異なる薬剤や製剤を順次投与する必要がある場合に、複数の薬剤オーダーを連結する。\n\n非経口輸液を「処方可能」なものとして扱うのが通常の診療現場では、本archetypeはそのオーダーにも適している。それ以外の現場では、別の「非経口輸液オーダー」が適切な場合もある。\n\n内容の一部を CLUSTER archetypeを含む SLOT で表している理由は、以下の3点である：\n- 上記のすべてのユースケースに使える中核となるarchetypeを保ちつつ、必要な部分では柔軟に拡張できるようにする。例：「製剤の詳細」SLOT では、構造化された詳細情報を追加できる。薬剤については候補となるarchetypeが提案されている。今後、複雑な経静脈栄養のオーダーなど、別の目的には他の CLUSTER archetypeが必要になる可能性がある。\n- 他の臨床の文脈でも使う内容を、archetypeとして再利用できるようにする。特に、実際の調剤や投与などを記録する、対となる ACTION.medication archetypeでの再利用を支援する。\n- 使用頻度の低い内容を、中核となるarchetypeの枠組みから切り離す。\n\n単一のarchetypeインスタンス内で、複数のオーダーを別々のアクティビティとして表せる。これにより、密接に結び付いた異なる薬剤のオーダーをまとめて扱える。例：単一のパックとして処方しない場合の H. pylori 治療。\n\nこれらの用途には、FHIR Medication Order と Medication Statement の両方のユースケースが含まれる。つまり、適切な文脈で用いれば、本archetypeは両方の FHIR リソースに対応する。",

  # Not to be used to record the activities related to carrying out the order for medication, vaccine, nutritional product or therapeutic item, such as details about actual administration or dispensing. Use the ACTION.medication for this purpose.
  # 
  # Not to be used to record the ordering of blood products, which involves a fundamentally different clinical process and is likely to require different supporting information Use the INSTRUCTION.transfusion for this purpose.
  # 
  # Not to be used to record the order for insertion of implants or medical devices such as pacemakers and defibrillators. Use the INSTRUCTION.procedure for this purpose.
  ['description', '-', 'misuse'] => "実際の投与や調剤の詳細など、薬剤、ワクチン、栄養製品、治療用品のオーダーを実施する活動の記録には、本archetypeではなく ACTION.medication を用いる。\n\n血液製剤のオーダーの記録には、本archetypeではなく INSTRUCTION.transfusion を用いる。血液製剤では臨床プロセスが根本的に異なり、別の参考資料が必要になると考えられる。\n\nインプラントや、ペースメーカー・除細動器などの医療機器の挿入オーダーの記録には、本archetypeではなく INSTRUCTION.procedure を用いる。",

  # medication | order | prescribe | therapy | substance | drug | therapeutic | otc | therapeutic good | pharmaceutical | product | posology | treatment | fluid | nutrition | CPOE | medicine
  ['description', '-', 'keywords'] => "薬剤 | オーダー | 処方 | 療法 | 物質 | 薬物 | 治療用 | 一般用医薬品（OTC） | 治療用品 | 医薬品 | 製品 | 用量学 | 治療 | 輸液 | 栄養 | CPOE | 薬 | 処方箋 | 投薬 | 薬剤オーダー",

  # © openEHR Foundation
  ['description', '-', 'copyright'] => "© openEHR Foundation",

  # INSTRUCTION
  # Medication order
  ['term', 'at0000', 'text'] => "薬剤オーダー",

  # INSTRUCTION
  # An order for a medication, vaccine, nutritional product or other therapeutic item for an identified individual.
  ['term', 'at0000', 'description'] => "特定された本人に対する薬剤、ワクチン、栄養製品、その他の治療用品のオーダー。",

  # INSTRUCTION > activities/ACTIVITY
  # Order
  ['term', 'at0001', 'text'] => "オーダー",

  # INSTRUCTION > activities/ACTIVITY
  # Details of the requested order.
  ['term', 'at0001', 'description'] => "依頼されたオーダーに関する詳細情報。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE
  # Tree
  ['term', 'at0002', 'text'] => "Tree",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE
  # @ internal @
  ['term', 'at0002', 'description'] => "@ internal @",

  # INSTRUCTION > protocol/ITEM_TREE > items/ELEMENT
  # Order identifier
  ['term', 'at0004', 'text'] => "オーダー識別子",

  # INSTRUCTION > protocol/ITEM_TREE > items/ELEMENT
  # Unique identifier for the medication order.
  ['term', 'at0004', 'description'] => "薬剤オーダーの一意な識別子。",

  # INSTRUCTION > protocol/ITEM_TREE > items/ELEMENT
  # This data element allows for multiple occurrences to be defined more explicitly at run-time, if required.
  ['term', 'at0004', 'comment'] => "このデータエレメントは複数回の出現を許容し、必要に応じて実行時にそれぞれをより明確に定義できる。",

  # INSTRUCTION > protocol/ITEM_TREE
  # Tree
  ['term', 'at0005', 'text'] => "Tree",

  # INSTRUCTION > protocol/ITEM_TREE
  # @ internal @
  ['term', 'at0005', 'description'] => "@ internal @",

  # INSTRUCTION > protocol/ITEM_TREE > items/CLUSTER
  # Extension
  ['term', 'at0008', 'text'] => "Extension",

  # INSTRUCTION > protocol/ITEM_TREE > items/CLUSTER
  # Additional information required to capture local content or to align with other reference models/formalisms.
  ['term', 'at0008', 'description'] => "ローカルコンテンツを捕捉するため、あるいは他の参照モデルや形式手法と整合させるために必要な追加情報。",

  # INSTRUCTION > protocol/ITEM_TREE > items/CLUSTER
  # For example: local information requirements or additional metadata to align with FHIR or CIMI equivalents.
  ['term', 'at0008', 'comment'] => "例：ローカルな情報要件や、FHIR または CIMI の相当するものに適合させるための追加メタデータ。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Overall directions description
  ['term', 'at0009', 'text'] => "用法・用量の記述",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Complete narrative description about how the ordered item is to be used.
  ['term', 'at0009', 'description'] => "オーダーした薬剤等をどのように使用するかについての、全体を網羅した叙述的な説明。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # This narrative should normally subsume data captured in 'Dose amount', 'Dose timing' and any additional instructions for use. Where the medication dose directions are fully carried by the structured, computable dose directions, this element should carry the narrative equivalent, generally auto-generated. If it is not possible to represent the intended 'Dose direction' fully in computable form, partial representation is not recommended, and the directions should be only recorded in narrative form using this data element.
  ['term', 'at0009', 'comment'] => "通常、この記述には「用量」「投与タイミング」と、使用に関する追加の指示をすべて含める。用量の指示が、構造化されコンピュータで処理できる指示ですべて表されている場合、このデータエレメントには同じ内容の文章を記録する。一般には、その文章は自動生成する。意図した「用量の指示」をすべてコンピュータで処理できる形に表せない場合、一部だけを表すことは推奨しない。このデータエレメントを用い、文章だけで指示を記録する。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # Order start criterion
  ['term', 'at0011', 'text'] => "オーダー開始基準",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # A condition which, when met, requires the commencement of administration or use.
  ['term', 'at0011', 'description'] => "満たされたときに投与または使用を開始する条件。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # For example: 'Start if symptoms recur'. This is intended for a general pre-condition which should trigger the whole medication course to be started, and not for 'as required' administrations of an ongoing order.
  ['term', 'at0011', 'comment'] => "例：「症状が再発したら開始する」。薬剤の全治療コースを開始するきっかけとなる、全般的な前提条件を記録するためのものである。継続中のオーダーにおける「必要時」の投与を記録するためのものではない。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # Order start date/time
  ['term', 'at0012', 'text'] => "オーダー開始日時",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # The date and optional time to commence use of the ordered item.
  ['term', 'at0012', 'description'] => "オーダーした薬剤等の使用を開始する日付と、任意で記録する時刻。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # Order stop date/time
  ['term', 'at0013', 'text'] => "オーダー終了日時",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # The date and optional time when it is planned to cease use of the ordered item.
  ['term', 'at0013', 'description'] => "オーダーした薬剤等の使用を終了する予定の日付と、任意で記録する時刻。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # Order stop criterion
  ['term', 'at0016', 'text'] => "オーダー終了基準",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # A condition which, when met, requires the cessation of administration or use.
  ['term', 'at0016', 'description'] => "満たされたときに投与または使用を終了する条件。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # For example: 'Stop after symptoms disappear''.
  ['term', 'at0016', 'comment'] => "例：「症状が消失したら終了する」。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Clinical indication
  ['term', 'at0018', 'text'] => "臨床的適応",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # The clinical reason for use of the ordered item.
  ['term', 'at0018', 'description'] => "オーダーした薬剤等を使用する臨床的な理由。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # For example: 'Angina'. Coding of the clinical indication with a terminology is preferred, where possible. This data element allows multiple occurrences. It is not intended to carry an indication for administrative authorisation purposes.
  ['term', 'at0018', 'comment'] => "例：「狭心症」。可能であれば、臨床的適応は用語集によるコード化が望ましい。このデータエレメントは複数回の出現を許容する。管理上の承認を得るための適応を記録することは想定していない。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Additional instruction
  ['term', 'at0044', 'text'] => "追加の指示",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # An additional instruction on how to use or store the ordered item.
  ['term', 'at0044', 'description'] => "オーダーした薬剤等の使用方法や保管方法に関する追加の指示。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # For example: precautions as 'take with food', 'Avoid grapefruit', 'Dissolve in water', 'store in a cool, dry place'. This data element allows multiple occurrences and should be coded with a reference terminology, where possible.
  ['term', 'at0044', 'comment'] => "例：「食事とともに服用する」「グレープフルーツを避ける」「水に溶かす」「涼しく乾燥した場所に保管する」などの注意事項。このデータエレメントは複数回の出現を許容し、可能であれば参照用語集によりコード化する。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Parsable directions
  ['term', 'at0047', 'text'] => "構文化された用法",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # A parsable, computable text representation of the directions.
  ['term', 'at0047', 'description'] => "構文解析が可能で、コンピュータで処理できる、指示のテキスト表現。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Generally this is only used when passing information between legacy systems. For example: '10mg bd; 20mg n' as used by the NHS Dose syntax (in development).
  ['term', 'at0047', 'comment'] => "一般には、旧来のシステム間で情報を受け渡す場合にのみ用いる。例：NHS Dose syntax（開発中）で用いられる「10mg bd; 20mg n」。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # Duration of order completed
  ['term', 'at0050', 'text'] => "完了したオーダー期間",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # The time period during which the individual/patient has already been using the ordered item as a part of the intended whole order but prior to the issuance of this order.
  ['term', 'at0050', 'description'] => "予定されたオーダー全体の一部として、本人がこのオーダーの発行前に、すでにオーダーした薬剤等を使用していた期間。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # For example: To record that the patient had been taking antibiotics 3 days prior to hospital admission, in the context of a 7 day course.
  ['term', 'at0050', 'comment'] => "例：7日間の抗菌薬の治療コースのうち、本人が入院前にすでに3日間服用していたことを記録する。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER
  # Maximum dose
  ['term', 'at0051', 'text'] => "最大用量",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER
  # Details about the maximum, cumulative dose allowed over a defined period for the ordered item.
  ['term', 'at0051', 'description'] => "オーダーした薬剤等について、定められた期間内に許容される最大の累積用量に関する詳細情報。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER
  # For example: 'up to 1gram per day'. This cluster allows multiple occurrences to enable representation of multiple maximum doses that apply to different time periods. Lifetime maximum dose should not be carried here as it refers to multiple orders over time.
  ['term', 'at0051', 'comment'] => "例：「1日1グラムまで」。この CLUSTER は複数回の出現を許容し、異なる期間に適用される複数の最大用量を表せる。生涯の最大用量は、時間を隔てた複数のオーダーに関わるため、ここには記録しない。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER > items/ELEMENT
  # Allowed period
  ['term', 'at0053', 'text'] => "許容期間",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER > items/ELEMENT
  # The period of time during which the maximum dose is calculated.
  ['term', 'at0053', 'description'] => "最大用量を計算する対象の期間。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER > items/ELEMENT
  # Example: 24 hours.
  ['term', 'at0053', 'comment'] => "例：24時間。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # Administrations completed
  ['term', 'at0060', 'text'] => "完了した投与回数",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # The number of administrations of the ordered item that have been completed, as part of the intended whole order but prior to the issuance of this order.
  ['term', 'at0060', 'description'] => "予定されたオーダー全体の一部として、このオーダーの発行前に完了した、オーダーした薬剤等の投与回数。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # For example: To record that the patient has taken the two first antibiotic tablets of a three day course, prior to discharge from the hospital to a nursing home.
  ['term', 'at0060', 'comment'] => "例：3日間の治療コースのうち、本人が病院からナーシングホームへ退院する前に、抗菌薬の最初の2錠を服用したことを記録する。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # Medication safety
  ['term', 'at0062', 'text'] => "薬剤安全性",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # Details about medication safety for the ordered item.
  ['term', 'at0062', 'description'] => "オーダーした薬剤等の薬剤安全性に関する詳細情報。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # Exceptional safety override?
  ['term', 'at0064', 'text'] => "例外的な安全性オーバーライド",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # Confirmation by the prescriber that the normal dose or other safety limit has been overridden due to exceptional circumstances.
  ['term', 'at0064', 'description'] => "例外的な状況のため、通常の用量やその他の安全性の上限をオーバーライドしたことを、処方者が確認した旨。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER
  # Dispense amount
  ['term', 'at0065', 'text'] => "調剤量",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER
  # Details about the amount of the ordered item to be dispensed.
  ['term', 'at0065', 'description'] => "調剤する薬剤等の量に関する詳細情報。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER
  # This SLOT allows for local variation in the different jurisdictions regarding medication dispensing amount to be managed.
  ['term', 'at0065', 'comment'] => "この SLOT を用いて、薬剤の調剤量に関する国や地域ごとの違いに対応できる。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # Authorisation directions
  ['term', 'at0069', 'text'] => "承認の指示",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # Details of authorisation of the ordered item, including supporting local self-administration, issue and endorsement policies.
  ['term', 'at0069', 'description'] => "オーダーした薬剤等の承認に関する詳細情報。ローカルな自己投与、発行、承認の方針への対応を含む。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # For example: details of repeat/refill supply. This SLOT allows for local variation in the different jurisdictions regarding medication authorisation and re-authorisation to be managed.
  ['term', 'at0069', 'comment'] => "例：反復・リフィル供給に関する詳細情報。この SLOT を用いて、薬剤の承認と再承認に関する国や地域ごとの違いに対応できる。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Medication item
  ['term', 'at0070', 'text'] => "薬剤名",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Name of the medication, vaccine or other therapeutic/prescribable item being ordered.
  ['term', 'at0070', 'description'] => "オーダーする薬剤、ワクチン、その他の治療用品や処方可能な品目の名称。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Depending on the prescribing context this field could be used for either generic- or product-based prescribing. This data field can be used to record tightly bound orders of different medications when they are prescribed as a single pack. It is strongly recommended that the 'Medication item' be coded with a terminology capable of triggering decision support, where possible. The extent of coding may vary from the simple name of the medication item through to structured details about the actual medication pack to be used. Free text entry should only be used if there is no appropriate terminology available.
  ['term', 'at0070', 'comment'] => "処方の文脈に応じて、この項目は一般名による処方にも製品名による処方にも用いることができる。異なる薬剤を単一のパックとして処方する場合には、密接に結び付いたオーダーをこの項目で記録できる。可能であれば、「薬剤名」は臨床意思決定支援を起動できる用語集によりコード化することを強く推奨する。コード化の範囲は、薬剤等の単純な名称から、実際に使用する薬剤パックの構造化された詳細情報まで、さまざまである。自由記述は、適切な用語集を利用できない場合に限って用いる。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Route
  ['term', 'at0091', 'text'] => "投与経路",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # The route by which the ordered item is to be administered into the subject's body.
  ['term', 'at0091', 'description'] => "オーダーした薬剤等をケア対象者の体内に投与する経路。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # For example: 'oral', 'intravenous', or 'topical'.
  # Coding of the route with a terminology is preferred, where possible. Multiple potential routes may be specified.
  ['term', 'at0091', 'comment'] => "例：「経口」「静脈内」「局所」。\n可能であれば、投与経路は用語集によるコード化が望ましい。選択可能な投与経路を複数指定できる。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Body site
  ['term', 'at0092', 'text'] => "身体部位",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Name of the site of administration of the ordered item.
  ['term', 'at0092', 'description'] => "オーダーした薬剤等を投与する部位の名称。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # For example: 'left upper arm', 'intravenous catheter right hand'.
  #  Coding of the body site with a terminology is preferred, where possible.
  ['term', 'at0092', 'comment'] => "例：「左上腕」「右手の静脈内カテーテル」。\n 可能であれば、身体部位は用語集によるコード化が望ましい。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # Structured body site
  ['term', 'at0093', 'text'] => "構造化された身体部位表現",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # Structured description of the site of administration of the ordered item.
  ['term', 'at0093', 'description'] => "オーダーした薬剤等を投与する部位の構造化された記述。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Administration method
  ['term', 'at0094', 'text'] => "投与方法",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # The technique or device by which the ordered item is to be administered.
  ['term', 'at0094', 'description'] => "オーダーした薬剤等の投与に用いる手技または器具。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # For example: ' via Z-track injection'; 'via nebuliser'. Coding of the method with a terminology is preferred, where possible.
  ['term', 'at0094', 'comment'] => "例：「Z-track法による注射」「ネブライザーによる投与」。可能であれば、投与方法は用語集によるコード化が望ましい。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # Administration device
  ['term', 'at0095', 'text'] => "投与器具",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # Details of the medical device used to assist administration of the ordered item.
  ['term', 'at0095', 'description'] => "オーダーした薬剤等の投与を補助する医療機器に関する詳細情報。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Patient information
  ['term', 'at0105', 'text'] => "患者への情報",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # An additional instruction directed primarily at the individual/patient or carers.
  ['term', 'at0105', 'description'] => "主に本人や介護者に向けた追加の指示。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # For example: 'To reduce your blood pressure', 'To thin your blood'. This data element allows multiple occurrences and should be coded with a reference terminology, where possible. If required it is possible to use a LINK attribute to associate this element with, for example, the 'original diagnosis' in a separate Problem list composition but the indication should be explicitly recorded here, as the link target may change over time.
  ['term', 'at0105', 'comment'] => "例：「血圧を下げるため」「血液を固まりにくくするため」。このデータエレメントは複数回の出現を許容し、可能であれば参照用語集によりコード化する。必要に応じて LINK 属性を使い、例えば別のプロブレムリストの COMPOSITION にある「元の診断」とこのデータエレメントを関連付けることができる。ただし、リンク先は時間とともに変わる可能性があるため、適応はここに明示的に記録する。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # Dispense instruction
  ['term', 'at0106', 'text'] => "調剤者への指示",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # An additional instruction directed primarily at the person dispensing the ordered item.
  ['term', 'at0106', 'description'] => "主にオーダーした薬剤等を調剤する人に向けた追加の指示。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # Example: Detailed instructions for phased dispensing of opiates.
  ['term', 'at0106', 'comment'] => "例：アヘン系薬剤の段階的な調剤に関する詳しい指示。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Monitoring instruction
  ['term', 'at0107', 'text'] => "モニタリングの指示",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # An additional instruction which gives advice on recommended or required monitoring of the ordered item.
  ['term', 'at0107', 'description'] => "オーダーした薬剤等について、推奨される、または必要なモニタリングに関する追加の指示。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # For example: 'Please check renal function in 2 weeks'. This data element allows multiple occurrences.
  ['term', 'at0107', 'comment'] => "例：「2週間後に腎機能を確認する」。このデータエレメントは複数回の出現を許容する。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER
  # Order summary
  ['term', 'at0112', 'text'] => "オーダー要約",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER
  # Summary information about use of the ordered item, such as current status or key dates, generally used in non-prescription contexts.
  ['term', 'at0112', 'description'] => "オーダーした薬剤等の使用について、現在の状態や主要な日付などをまとめた情報。一般には処方箋以外の文脈で用いる。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER
  # Course summary may be required when transmitting medication information between systems or representing a FHIR Medication statement. For example: as part of a referral, emergency patient summary or discharge communication.
  ['term', 'at0112', 'comment'] => "システム間で薬剤情報を伝達する場合や、FHIR Medication statement を表す場合には、治療コースの要約が必要になることがある。例：紹介、救急時の患者サマリー、退院時の情報伝達の一部として用いる。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # Order details
  ['term', 'at0113', 'text'] => "オーダー詳細",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # Details about the whole medication order.
  ['term', 'at0113', 'description'] => "薬剤オーダー全体に関する詳細情報。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # Dispense directions
  ['term', 'at0129', 'text'] => "調剤の指示",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # Directions about the dispensing of the ordered item.
  ['term', 'at0129', 'description'] => "オーダーした薬剤等の調剤に関する指示。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER > items/ELEMENT
  # Maximum amount
  ['term', 'at0130', 'text'] => "最大量",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER > items/ELEMENT
  # The maximum, cumulative amount of medication which should be administered within the allowed period.
  ['term', 'at0130', 'description'] => "許容期間内に投与できる薬剤の最大の累積量。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER > items/ELEMENT
  # For example: 1 ml, 1.5 mg, 0.125 g.
  ['term', 'at0130', 'comment'] => "例：1 ml、1.5 mg、0.125 g。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # Substitution direction
  ['term', 'at0132', 'text'] => "代替の指示",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # Permission for substitution with a bioequivalent item.
  ['term', 'at0132', 'description'] => "生物学的同等な製品への代替を許可するかどうか。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # In many jurisdictions, substitution of an ordered item as a generic form or with a different brand name, which has been determined as bioequivalent, is allowed at the point of dispense or supply. In other cases substitution is assumed and the clinician has to explicitly request non-substitution.
  ['term', 'at0132', 'comment'] => "多くの国や地域では、調剤または供給の際に、生物学的同等と判断された後発医薬品や別の銘柄の製品に代替することが認められている。代替を前提とし、代替しない場合には医療従事者が明示的に指示しなければならない国や地域もある。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # Priority
  ['term', 'at0139', 'text'] => "優先度",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # An indicator of the urgency with which the ordered item should be dispensed.
  ['term', 'at0139', 'description'] => "オーダーした薬剤等を調剤する際の緊急度を示す指標。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # For example 'Urgent'. This is left to be templated or specialised according to local valuesets. Some jurisdictions allow instructions to dispense to be marked as 'urgent' so that the dispensary handles them quickly.
  ['term', 'at0139', 'comment'] => "例：「至急」。ローカルな値セットに従って、テンプレート化または特殊化することを想定している。国や地域によっては、調剤部門が迅速に対応できるよう、調剤の指示に「至急」と記載できる。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # Medication details
  ['term', 'at0143', 'text'] => "薬剤詳細",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # Structured details about the overall medication including strength, form and constituent substances.
  ['term', 'at0143', 'description'] => "含量、剤形、構成物質を含む、薬剤全体に関する構造化された詳細情報。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # Use this SLOT where the detailed description of the ordered item needs to be explicitly stated. For example: the form, strength, any diluents or mixture of ingredients.
  ['term', 'at0143', 'comment'] => "オーダーした薬剤等の詳しい説明を明示する必要がある場合に、この SLOT を用いる。例：剤形、含量、希釈液、成分の混合。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Therapeutic intent
  ['term', 'at0148', 'text'] => "治療意図",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # The overall therapeutic intent of the ordered item.
  ['term', 'at0148', 'description'] => "オーダーした薬剤等の全体的な治療意図。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # For example: 'pain relief'; 'palliative care'; 'low-dose prophylaxis'; 'rehydration'; 'nutritional infusion'.
  ['term', 'at0148', 'comment'] => "例：「疼痛緩和」「緩和ケア」「低用量での予防」「水分補給」「栄養輸液」。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER
  # Total daily effective dose
  ['term', 'at0150', 'text'] => "1 日実効総用量",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER
  # Details about the total daily amount of the ordered item expected to be administered.
  ['term', 'at0150', 'description'] => "オーダーした薬剤等について、投与が見込まれる1 日総量に関する詳細情報。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER
  # The total daily dose records the expected effective dose, and thus support titration of an initial low dose towards the effective dose over a period of time. This is not itself the target dose or goal but the actual effective daily dose against that goal. In some circumstances the Total daily dose will be calcuable from computable directions, in others it may need to be manually entered.
  ['term', 'at0150', 'comment'] => "1 日総用量には、見込まれる実効用量を記録する。これにより、初期の低用量から実効用量に向け、一定期間にわたる用量調節（漸増）を支援する。この値は目標用量や目標そのものではなく、その目標に対する実際の1 日実効用量である。1 日総用量は、コンピュータで処理できる指示から計算できる場合もあれば、手入力が必要な場合もある。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER > items/ELEMENT
  # Total daily amount
  ['term', 'at0151', 'text'] => "1 日総量",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER > items/ELEMENT
  # The amount of ordered item which will be taken each day if administered as intended.
  ['term', 'at0151', 'description'] => "意図どおりに投与した場合に、1日あたりに使用する薬剤等の量。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER > items/ELEMENT
  # For example '20 mg'.
  ['term', 'at0151', 'comment'] => "例：「20 mg」。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # Non-substitution reason
  ['term', 'at0154', 'text'] => "代替不可の理由",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # The reason why an ordered item should not be substituted at dispense.
  ['term', 'at0154', 'description'] => "調剤時にオーダーした薬剤等を代替してはならない理由。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # For example 'Generic preparation not bio-equivalent'.
  ['term', 'at0154', 'comment'] => "例：「後発医薬品が生物学的同等ではない」。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # Dispensing start date
  ['term', 'at0155', 'text'] => "調剤開始日",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # The date from which the ordered item is permitted to be dispensed for the first time.
  ['term', 'at0155', 'description'] => "オーダーした薬剤等の初回の調剤が許可される開始日。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # May be used to control the time of dispensing of medications with potential for abuse. For example: benzodiazepines or analgesics.
  ['term', 'at0155', 'comment'] => "乱用のおそれがある薬剤の調剤時期を管理するために用いることができる。例：ベンゾジアゼピン系薬剤や鎮痛薬。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # Dispensing expiry date
  ['term', 'at0161', 'text'] => "調剤有効期限",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # The date after which the ordered item is no longer valid to be legally dispensed.
  ['term', 'at0161', 'description'] => "オーダーした薬剤等を法的に調剤できる期限の日付。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/ELEMENT
  # In some jurisdictions, orders to dispense may have an expiry date after which the prescription may not be dispensed.
  ['term', 'at0161', 'comment'] => "国や地域によっては、調剤のオーダーに有効期限があり、期限を過ぎるとその処方箋に基づく調剤ができなくなる。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER > items/ELEMENT
  # Override reason
  ['term', 'at0162', 'text'] => "オーバーライドの理由",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER > items/ELEMENT
  # The reason for a clinical safety or maximum dose override.
  ['term', 'at0162', 'description'] => "臨床的な安全性または最大用量をオーバーライドする理由。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER > items/ELEMENT
  # For example: 'Not responsive at maximum recommended dose. Critical situation.', 'Peniciilin is only valid treatment, likelihood of true penicillin allergy is low'.
  ['term', 'at0162', 'comment'] => "例：「推奨される最大用量でも反応がなく、危機的な状況である」「ペニシリンだけが有効な治療であり、真のペニシリンアレルギーである可能性は低い」。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER > items/ELEMENT
  # Purpose
  ['term', 'at0165', 'text'] => "目的",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER > items/ELEMENT
  # Description of the reason for recording a total daily effective dose.
  ['term', 'at0165', 'description'] => "1 日実効総用量を記録する理由の説明。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER > items/ELEMENT
  # For example: 'Hypertension control', 'Target dose 20mg daily'. The description could be used to identify a name, phrase or paragraph about the purpose for recording total daily effective dose, commonly to allow to titration towards a specific target dose.
  # The goal or target dose might be recorded here or more commonly as part of a linked EVALUATION 'Goal' archetype.
  ['term', 'at0165', 'comment'] => "例：「高血圧のコントロール」「目標用量は1日20mg」。1 日実効総用量を記録する目的を、名称、語句、または文章で示すために用いる。一般には、特定の目標用量に向けた用量調節（漸増）を可能にするために記録する。\n目標や目標用量はここに記録してもよいが、通常はリンクされた EVALUATION「Goal」archetypeの一部として記録する。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # Additional details
  ['term', 'at0166', 'text'] => "追加の詳細情報",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # Additional structured details about the ordered item not captured in other fields.
  ['term', 'at0166', 'description'] => "他の項目には収まらない、オーダーした薬剤等に関する追加の構造化された詳細情報。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Comment
  ['term', 'at0167', 'text'] => "コメント",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Additional narrative about the medication order not captured in other fields.
  ['term', 'at0167', 'description'] => "他の項目には収まらない薬剤オーダーについての追加の記述。",

  # Permitted
  ['term', 'at0168', 'text'] => "許可",

  # Substitution of the medication with a bioequivalent medication is allowed.
  ['term', 'at0168', 'description'] => "生物学的同等な薬剤への代替を許可する。",

  # Not permitted
  ['term', 'at0169', 'text'] => "不許可",

  # Substitution of the medication with a bioequivalent medication is not allowed.
  ['term', 'at0169', 'description'] => "生物学的同等な薬剤への代替を許可しない。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER
  # Dispense details
  ['term', 'at0170', 'text'] => "調剤の詳細",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER
  # Further details related to dispense directions.
  ['term', 'at0170', 'description'] => "調剤の指示に関する追加の詳細情報。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER
  # This SLOT allows for local variation in the different jurisdictions regarding medication dispensing.
  ['term', 'at0170', 'comment'] => "この SLOT を用いて、薬剤の調剤に関する国や地域ごとの違いに対応できる。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER > items/ELEMENT
  # Overriden safety advice
  ['term', 'at0171', 'text'] => "オーバーライドした安全性警告",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER > items/ELEMENT
  # A known or recognised safety issue which applies to this subject and the ordered item, such as an allergy, drug duplication warning or contraindication. This element is normally only recorded when this safety advice is overridden.
  ['term', 'at0171', 'description'] => "アレルギー、薬剤重複の警告、禁忌など、このケア対象者とオーダーした薬剤等に該当する、既知または認識された安全性の問題。通常、このデータエレメントは、その安全性警告をオーバーライドする場合にのみ記録する。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER > items/ELEMENT
  # For example: 'Allergic to penicillin', 'Atenolol duplicated'.
  ['term', 'at0171', 'comment'] => "例：「ペニシリンアレルギーあり」「アテノロールが重複している」。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Specific directions description
  ['term', 'at0173', 'text'] => "用法・用量の個別記述",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # A narrative description of a specific part of overall directions.
  ['term', 'at0173', 'description'] => "全体の指示のうち、特定の部分についての叙述的な説明。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # In some settings, it is common to split overall narrative directions into more specific segments of narrative. For example in hospital settings, it can be common to split the overall directions into 'Dose amount' and 'Dose timing', both as narrative text. These terms can be applied at template or run-time.
  ['term', 'at0173', 'comment'] => "全体の指示を記した文章を、より具体的な部分に分けることが一般的な現場もある。例：病院では、全体の指示を「用量」と「投与タイミング」に分け、いずれも文章で記録することがある。これらの名称は、テンプレートまたは実行時に設定できる。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Dosage justification
  ['term', 'at0174', 'text'] => "用量の根拠",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # A description of the justification used to calculate a dose amount or administration rate where this is dependent on some other factor.
  ['term', 'at0174', 'description'] => "用量や投与速度が他の因子に依存する場合に、その計算に用いた根拠の説明。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # For example: 'Adjusted for amputation'.
  ['term', 'at0174', 'comment'] => "例：「切断を考慮して調整した」。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # Structured dose and timing directions
  ['term', 'at0177', 'text'] => "構造化された用量・タイミングの指示",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # Details of structured dose and timing directions.
  ['term', 'at0177', 'description'] => "構造化された用量・タイミングの指示に関する詳細情報。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER
  # This SLOT has been designed to be used with the CLUSTER.therapeutic_direction archetype to enable recording of a complex set of dosage and timing directions. While it's possible to use other CLUSTER archetypes within this SLOT, it's strongly advised to do so only when predictable queryability is not a priority.
  ['term', 'at0177', 'comment'] => "この SLOT は、複雑な用量・タイミングの指示をまとめて記録できるよう、CLUSTER.therapeutic_direction archetypeと組み合わせて使うことを想定している。他の CLUSTER archetypeもこの SLOT 内で使用できるが、予測可能な検索が優先事項ではない場合に限ることを強く推奨する。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER
  # Safety override
  ['term', 'at0178', 'text'] => "安全性オーバーライド",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/CLUSTER > items/CLUSTER
  # Overriding of a known or recognised safety issue which applies to this subject and the ordered item, such as an allergy, drug duplication warning or contraindication.
  ['term', 'at0178', 'description'] => "アレルギー、薬剤重複の警告、禁忌など、このケア対象者とオーダーした薬剤等に該当する、既知または認識された安全性の問題のオーバーライド。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Clinician guidance
  ['term', 'at0179', 'text'] => "医療従事者向けの指針",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # Advice to future prescribers/dispensers about the ongoing, long term order.
  ['term', 'at0179', 'description'] => "継続中の長期オーダーについて、今後の処方者や調剤者に向けた助言。",

  # INSTRUCTION > activities/ACTIVITY > description/ITEM_TREE > items/ELEMENT
  # For example: 'don't allow brand substitution' or advice regarding using a specific brand to avoid fillers that cause reactions.
  ['term', 'at0179', 'comment'] => "例：「銘柄の代替を認めない」という指示や、反応を引き起こす賦形剤を避けるために特定の銘柄を用いるよう勧める助言。",

}.freeze

# note 列に残すメモ。迷った訳語には '要確認: ...' を付ける。
NOTES = {
  ['term', 'at0000', 'text'] => "要確認: 薬剤オーダー（他候補: 処方オーダー）ワクチン・栄養製品・治療用品も含むため、処方より広い語を採用する。",
  ['term', 'at0070', 'text'] => "要確認: 薬剤名（他候補: 薬剤、医薬品）画面ラベルとして簡潔にし、名称を記録する項目であることを示す。",
  ['term', 'at0095', 'text'] => "要確認: 投与器具（他候補: 投与デバイス）投与を補助する器具を示す指定案を採用する。",
  ['term', 'at0009', 'text'] => "要確認: 用法・用量の記述（他候補: 用法の全体記述）用量とタイミングを含む全体の指示を示す画面ラベルとする。",
  ['term', 'at0173', 'text'] => "要確認: 用法・用量の個別記述（他候補: 用法の個別記述）テンプレートで「用量」「用法」に分けて2回出現させる想定に合わせる。",
  ['term', 'at0047', 'text'] => "要確認: 構文化された用法（他候補: 機械可読な用法）構文解析できるテキストを表し、構造化された指示のSLOTと区別する。",
  ['term', 'at0062', 'text'] => "要確認: 薬剤安全性（他候補: 投薬の安全性）薬剤オーダーの安全性に関する情報をまとめる指定案を採用する。",
  ['term', 'at0064', 'text'] => "要確認: 例外的な安全性オーバーライド（他候補: 安全性警告の例外的解除）overrideはオーバーライドに統一し、指定のラベルを採用する。",
  ['term', 'at0150', 'text'] => "要確認: 1 日実効総用量（他候補: 1 日総用量）目標用量そのものではなく、目標に対する実効用量を表す。",
  ['term', 'at0151', 'text'] => "要確認: 1 日総量（他候補: 1 日総用量）at0150の内部で日ごとの量を記録する項目として、指定案を採用する。",
  ['term', 'at0165', 'text'] => "要確認: 目的（他候補: 記録目的）1 日実効総用量を記録する理由であることは説明文で示し、ラベルは指定の「目的」とする。",
  ['term', 'at0148', 'text'] => "要確認: 治療意図（他候補: 治療目的）用量記録の「目的」と区別し、治療全体の意図を示す。",
  ['term', 'at0179', 'text'] => "要確認: 医療従事者向けの指針（他候補: 処方者への申し送り）将来の処方者と調剤者の双方への助言を含むため。",
  ['term', 'at0060', 'text'] => "要確認: 完了した投与回数（他候補: 投与済み回数）このオーダーの発行前に完了した回数を含む指定案を採用する。",
  ['term', 'at0050', 'text'] => "要確認: 完了したオーダー期間（他候補: 実施済みのオーダー期間）全体の治療期間のうち、このオーダーの発行前に完了した期間を表す。",
  ['term', 'at0069', 'text'] => "要確認: 承認の指示（他候補: 承認に関する指示）自己投与、発行、承認、再承認の地域差を扱うSLOTの指定案を採用する。",
  ['term', 'at0132', 'text'] => "要確認: 代替の指示（他候補: 変更の指示）生物学的同等な製品への代替を指し、後発医薬品への変更だけに限定しない。",
  ['term', 'at0168', 'text'] => "要確認: 許可（他候補: 変更可）代替の許可を示す指定案を採用し、国内の処方箋の表現との対応はレビューで確認する。",
  ['term', 'at0169', 'text'] => "要確認: 不許可（他候補: 変更不可）代替の不許可を示す指定案を採用し、国内の処方箋の表現との対応はレビューで確認する。",
  ['term', 'at0154', 'text'] => "要確認: 代替不可の理由（他候補: 変更不可の理由）「代替の指示」と用語を揃える。",
  ['term', 'at0177', 'text'] => "要確認: 構造化された用量・タイミングの指示（他候補: 構造化された用量・投与時期の指示）timing_dailyの服用タイミングとの整合を保つため、タイミングを採用する。",
  ['description', '-', 'use'] => "要確認: 投薬指示簿（他候補: 薬剤投与記録表）drug chartはオーダーを記載する文脈のため、指示簿を採用する。",
  ['term', 'at0069', 'comment'] => "要確認: 反復・リフィル供給（他候補: 繰り返しの供給）各国の再供給制度を含むため、国内のリフィル処方箋に限定しない。",
  ['term', 'at0106', 'comment'] => "要確認: 段階的な調剤（他候補: 分割調剤）国内制度の分割調剤に限定しない。",
}.freeze

src, dst = ARGV
lines = File.readlines(src, chomp: true)
out = [lines.shift]
lines.each do |l|
  c = l.split("\t", -1)
  key = c[1..3]
  c[6] = T.fetch(key).gsub("\n", '\n')
  c[7] = NOTES[key] || ''
  out << c.join("\t")
end
File.write(dst, out.join("\n") + "\n")
