# frozen_string_literal: true
# Japanese translation for openEHR-EHR-OBSERVATION.story.v1
# Generated by tools/scaffold_fill.rb - fill every empty string, following glossary-ja.md.
# Human proofreading: edit work/openEHR-EHR-OBSERVATION.story.v1.ja.tsv and run `make import ID=openEHR-EHR-OBSERVATION.story.v1` (regenerates this file).

T = {
  # To record a narrative description of the clinical history of the subject of care and to provide a framework in which to nest detailed CLUSTER archetypes, each of which will support the narrative with additional structured detail for symptoms, health events and related topics.
  # 
  # Use to record detail about the clinical history as reported by an individual, parent, care-giver or other party. It may be recorded by a clinician as part of a clinical history record as reported to them, or self-recorded as part of a clinical questionnaire or personal health record.
  ['description', '-', 'purpose'] => "ケア対象者の病歴を叙述的に記録するため。叙述を詳細な記録で補うため、症状、健康イベント、および関連する話題について構造化された CLUSTER archetype群を入れ子にするための枠組みを提供する。\n\n本人、親、介護者、またはその他の関係者から報告された病歴の詳細を記録するために用いる。臨床医が報告を受けた病歴の記録の一部として記録することも、臨床問診票や個人健康記録の一部として本人が自ら記録することもある。",

  # Use to record a description about subjective health-related observations or impressions from the point of view of the subject of care. 
  # 
  # When recorded by a clinician within the context of healthcare provision the story can be used for capturing the clinical history, as reported by the subject themselves, a parent, care-giver or other related party. If recorded by the subject, it can be used as an account of their 'story' of symptoms and health experiences, which might be used to share with healthcare providers or to document within their own personal health record.
  # 
  # Use:
  # - to record a simple narrative; and/or 
  # - as a container archetype to enable recording of a detailed structured history by inclusion of relevant CLUSTER archetypes within the 'Detail' SLOT. For example: CLUSTER.symptom, CLUSTER.issue or CLUSTER.health_event archetypes can be appropriately used in this SLOT.
  # 
  # Use to incorporate the narrative descriptions of clinical history captured from existing or legacy clinical systems into an archetyped format, using the 'Story' text data element.
  ['description', '-', 'use'] => "ケア対象者の視点からの、健康に関する主観的な観察や印象についての記述を記録するために用いる。 \n\n医療実務の文脈で臨床医が記録する場合、病歴は、本人、親、介護者、またはその他の関係者から報告された病歴を捉えるために使える。本人が記録する場合は、症状や健康上の経験についての本人が語る「病歴」の記述として使え、医療従事者と共有したり、本人の個人健康記録に残したりするために用いることができる。\n\n用途：\n- 単純な叙述を記録する；および／または \n- 「詳細」SLOT に関連する CLUSTER archetypeを含めることで、詳細な構造化された病歴を記録できるようにするコンテナarchetypeとして。例：CLUSTER.symptom、CLUSTER.issue、CLUSTER.health_event の各archetypeをこの SLOT で適切に使用できる。\n\n既存または旧来の臨床システムから取り込んだ病歴の叙述的な記述を、「病歴の記述」（Story）テキストデータエレメントを用いて archetype化された形式に組み込むために用いる。",

  # Not to be used to record formal assessments by clinicians which would usually be recorded using the EVALUATION class of archetypes.
  ['description', '-', 'misuse'] => "臨床医による正式な評価を記録するために用いてはならない。それらは通常、EVALUATION クラスのarchetypeを用いて記録する。",

  # history | presenting | complaint | story | symptom | health | record | presenting complaint | anamnesis
  ['description', '-', 'keywords'] => "病歴 | 現病歴 | 主訴 | ストーリー | 症状 | 健康 | 記録 | 既往歴 | アナムネーゼ | 問診",

  # © openEHR Foundation
  ['description', '-', 'copyright'] => "© openEHR Foundation",

  # OBSERVATION
  # Story/History
  ['term', 'at0000', 'text'] => "病歴",

  # OBSERVATION
  # The subjective clinical history of the subject of care as recorded directly by the subject, or reported to a clinician by the subject or a carer.
  ['term', 'at0000', 'description'] => "ケア対象者の主観的な病歴で、本人が直接記録したもの、または本人や介護者から臨床医に報告されたもの。",

  # OBSERVATION > data/HISTORY
  # Event Series
  ['term', 'at0001', 'text'] => "Event Series",

  # OBSERVATION > data/HISTORY
  # @ internal @
  ['term', 'at0001', 'description'] => "@ internal @",

  # OBSERVATION > data/HISTORY > events/EVENT
  # Any event
  ['term', 'at0002', 'text'] => "任意のイベント",

  # OBSERVATION > data/HISTORY > events/EVENT
  # Default, unspecified point in time or interval event which may be explicitly defined in a template or at run-time.
  ['term', 'at0002', 'description'] => "既定の、特定されていない時点または期間のイベント。テンプレートまたは実行時に明示的に定義できる。",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE
  # Tree
  ['term', 'at0003', 'text'] => "Tree",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE
  # @ internal @
  ['term', 'at0003', 'description'] => "@ internal @",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE > items/ELEMENT
  # Story
  ['term', 'at0004', 'text'] => "病歴の記述",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE > items/ELEMENT
  # Narrative description of the story or clinical history for the subject of care.
  ['term', 'at0004', 'description'] => "ケア対象者の語り、または臨床家が聴取した病歴の叙述的な記述。",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE > items/CLUSTER
  # Structured detail
  ['term', 'at0006', 'text'] => "構造化された詳細記録",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE > items/CLUSTER
  # Structured detail about the individual's story or patient's history.
  ['term', 'at0006', 'description'] => "本人の語りまたは臨床家が聴取した病歴についての構造化された詳細記録。",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE > items/CLUSTER
  # For example: a specific symptom such as nausea or pain; an event such as a fall off a bicycle; or an issue such as a desire to quit using tobacco.
  ['term', 'at0006', 'comment'] => "例：悪心や疼痛のような特定の症状、自転車からの転落のようなイベント、禁煙したいという希望のような問題。",

  # OBSERVATION > protocol/ITEM_TREE
  # Tree
  ['term', 'at0007', 'text'] => "Tree",

  # OBSERVATION > protocol/ITEM_TREE
  # @ internal @
  ['term', 'at0007', 'description'] => "@ internal @",

  # OBSERVATION > protocol/ITEM_TREE > items/CLUSTER
  # Extension
  ['term', 'at0008', 'text'] => "Extension",

  # OBSERVATION > protocol/ITEM_TREE > items/CLUSTER
  # Additional information required to capture local content or to align with other reference models/formalisms.
  ['term', 'at0008', 'description'] => "ローカルコンテンツを捕捉するため、あるいは他の参照モデルや形式手法と整合させるために必要な追加情報。",

  # OBSERVATION > protocol/ITEM_TREE > items/CLUSTER
  # For example: Local information requirements or additional metadata to align with FHIR equivalents.
  ['term', 'at0008', 'comment'] => "例：ローカルな情報要件や、FHIR の相当するものに適合させるための追加メタデータ。",

}.freeze

# note 列に残すメモ。迷った訳語には '要確認: ...' を付ける。
NOTES = {
  # ['term', 'at0000', 'text'] => '要確認: ...',
}.freeze

src, dst = ARGV
lines = File.readlines(src, chomp: true)
out = [lines.shift]
lines.each do |l|
  c = l.split("\t", -1)
  key = c[1..3]
  c[6] = T.fetch(key).gsub("\n", '\n')
  c[7] = NOTES[key] || ''
  out << c.join("\t")
end
File.write(dst, out.join("\n") + "\n")
