# frozen_string_literal: true
# Japanese translation for openEHR-EHR-CLUSTER.address.v1
# Generated by tools/scaffold_fill.rb - fill every empty string, following glossary-ja.md.
# Human proofreading: edit work/openEHR-EHR-CLUSTER.address.v1.ja.tsv and run `make import ID=openEHR-EHR-CLUSTER.address.v1` (regenerates this file).

T = {
  # To record details about the location of a person, physical building or landmark as they are known or understood in the course of clinical documentation.
  ['description', '-', 'purpose'] => "臨床記録の作成に際して取得した、人、建物、または目印となる場所の所在に関する詳細情報を記録するため。",

  # Use to record details about the location of a person, physical building or landmark as they are known or understood in the course of clinical documentation, often ad hoc or when it is not appropriate or possible to use an address lookup service. Examples include:
  # - the business address of an organisation providing home care to an individual; or
  # - the postal address of the copyholder of an advanced care record, within the EVALUATION.advance_care_directive archetype; or
  # - the physical location of a fall or accident.
  # 
  # The scope of this archetype has been constrained to carry the commonest structured components for identifying a specific physical building or landmark. In this context, a complete address may be described using:
  # - One or more free text 'Address line' data elements to represent the huge variety of ways that ‘street-level' details may need to be recorded; and
  # - 'Town' to represent a suburb, town, city, village, or community;
  # - 'District/County' to represent a local government district;
  # - 'State/Territory/Province’ to represent a major government district;
  # - ‘Postcode’, and 
  # - ‘Country'.
  # However, this archetype can be extended to include additional fine-grained details about the address by nesting the CLUSTER.structured_address within the 'Structured address' SLOT.
  # 
  # This CLUSTER.address archetype can also be used as a proxy for an address in formal demographic address data when reviewing a template with domain experts - for example, an assessment where reviewers would expect to see the individual's full contact details at the top of the assessment form.
  ['description', '-', 'use'] => "臨床記録の作成に際して取得した、人、建物、または目印となる場所の所在に関する詳細情報を記録するために用いる。住所登記簿や公式の住所一覧によらずに知り得た住所をその場で記録する場合や、住所検索サービスの利用が適切でない、または利用できない場合を主に想定している。以下のような使用例がある。\n- 個人に在宅ケアを提供する組織の事業所住所を記録する。\n- EVALUATION.advance_care_directive archetype内で、事前ケア記録の写しを保有する人の郵送先住所を記録する。\n- 転倒や事故が起きた物理的な場所を記録する。\n\n本archetypeの範囲は、特定の建物や目印となる場所を識別するための最も一般的な構造化された構成要素に限定している。この文脈では、完全な住所は次の要素で記述できる。\n- 「街区レベル」の詳細を記録する必要のある非常に多様な方法を表すために、1つ以上の自由記述の「住所行」データエレメントを用いる。\n- 郊外、町、市、村、または地域社会を表すために「市区町村」を用いる。\n- 地方自治体の区域を表すために「地区／郡」を用いる。\n- 主要な行政区域を表すために「都道府県／州」を用いる。\n- 「郵便番号」を用いる。 \n- 「国」を用いる。\nただし、「構造化された住所」SLOT に CLUSTER.structured_address を入れ子にすることで、住所に関するより細かな詳細情報を含めるよう本archetypeを拡張できる。\n\n本 CLUSTER.address archetypeは、対象領域の専門家とテンプレートをレビューする際に、正式なデモグラフィック住所データにおける住所の代用として使用することもできる。例えば、評価票の冒頭に個人の完全な連絡先が表示されることをレビュー担当者が想定している場合に、その情報を示すために用いる。",

  # Not to be used to record a fully structured address, such as described in ISO standards or as part of maintaining an official demographic register or index. Use an address lookup service, a formal Master Patient Index or a Health Provider Index for this purpose, or archetypes based on the openEHR Demographic Information Model.
  # 
  # Not to be used to represent digital addresses for use in electronic communication. Use CLUSTER.electronic_communication for this purpose.
  # 
  # Not to be used to record details about housing or homelessness. Use the EVALUATION.housing_summary for this purpose.
  ['description', '-', 'misuse'] => "ISO 規格に記述されているような完全に構造化された住所の記録や、住所登記簿や公式の住所一覧の維持・管理の一環としての記録に用いてはならない。これらの目的には、住所検索サービス、正式な患者マスターインデックス（MPI）や「医療従事者名簿（Health Provider Index）」、または openEHR デモグラフィック情報モデルに基づくarchetypeを用いること。\n\n電子的な連絡先に用いるデジタルアドレスの表現に用いてはならない。デジタルアドレスの記録には、CLUSTER.electronic_communication を用いること。\n\n住居やホームレス状態に関する詳細情報の記録に用いてはならない。これらの記録には、EVALUATION.housing_summary を用いること。",

  # address | postal | mailing | home | business | physical | landmark
  ['description', '-', 'keywords'] => "住所 | 郵便 | 郵送先 | 自宅 | 勤務先 | 事業所 | 所在地 | 目印 | 都道府県 | 市区町村 | 郵便番号",

  # CLUSTER
  # Address
  ['term', 'at0000', 'text'] => "住所",

  # CLUSTER
  # Details about the location of a person, physical building or landmark.
  ['term', 'at0000', 'description'] => "人、建物、または目印となる場所の所在に関する詳細情報。",

  # CLUSTER > items/ELEMENT
  # Address line
  ['term', 'at0001', 'text'] => "住所行",

  # CLUSTER > items/ELEMENT
  # An unstructured address line representing all relevant street-level or post-box details that would support the identification of a location.
  ['term', 'at0001', 'description'] => "場所を特定する手がかりとなる、街区レベルまたは私書箱の関連する詳細情報をすべて表す非構造化の住所行。",

  # CLUSTER > items/ELEMENT
  # Occurrences for this data element is set to 0..* to allow one or more free text 'Address line' data elements to represent the huge variety of ways that ‘street-level' details may need to be recorded within the context of a specified 'Town'. Multiple address lines can be represented in a template, renamed as 'Address line 1', 'Address line 2,' etc. For example: '7A/52 Davis Street' or 'Apartment 7A' as Address line 1 with '52 Davis Street' as Address line 2; a roadside mail box location, such as 'RMB 725, Princes Highway'; or using a descriptive landmark, such as or 'Corner of Smith & Brown Streets' or 'Second house north of the general store with the red door'.
  ['term', 'at0001', 'comment'] => "このデータエレメントの出現回数は 0..* に設定されており、指定した「市区町村」の中で「街区レベル」の詳細を記録する必要のある非常に多様な方法を、1つ以上の自由記述の「住所行」データエレメントで表せる。複数の住所行はテンプレートで「住所行 1」「住所行 2」などと名前を変えて表せる。例：「7A/52 Davis Street」、または住所行 1 を「Apartment 7A」とし住所行 2 を「52 Davis Street」とする；「RMB 725, Princes Highway」のような路上郵便受けの場所；あるいは「Corner of Smith & Brown Streets」や「Second house north of the general store with the red door」のような説明的な目印。日本の住所では、町域・丁目・番地・号・建物名・部屋番号（例：「本町一丁目2番3号 ○○ビル 401」）をここに記録する。",

  # CLUSTER > items/ELEMENT
  # City/Town
  ['term', 'at0002', 'text'] => "市区町村",

  # CLUSTER > items/ELEMENT
  # The name of the lowest level locality that contains the address.
  ['term', 'at0002', 'description'] => "住所を含む最下位の地域の名称。",

  # CLUSTER > items/ELEMENT
  # For example: suburb, town, city, settlement, village, or community. Coding with an external terminology is preferred, where possible. For example: 'Fitzroy'; 'Manchester'; 'Kingston' or 'Bergen'.
  ['term', 'at0002', 'comment'] => "例：郊外、町、市、集落、村、または地域社会。可能であれば、外部用語集によりコード化することが望ましい。例：「Fitzroy」、「Manchester」、「Kingston」または「Bergen」。日本の住所では市区町村（政令指定都市では市と区）が該当し、JIS X 0402 の全国地方公共団体コードでコード化できる。",

  # CLUSTER > items/ELEMENT
  # District/County
  ['term', 'at0003', 'text'] => "地区／郡",

  # CLUSTER > items/ELEMENT
  # The name of a local government district or geographical area that contains the address.
  ['term', 'at0003', 'description'] => "住所を含む地方自治体の区域または地理的区域の名称。",

  # CLUSTER > items/ELEMENT
  # Coding with an external terminology is preferred, where possible. For example: 'Surf Coast' and 'Yarra' local government councils in Victoria, Australia;and the Parishes of 'Saint Andrew' and 'Kingston' in Jamaica..
  ['term', 'at0003', 'comment'] => "可能であれば、外部用語集によりコード化することが望ましい。例：オーストラリア・ビクトリア州の地方自治体「Surf Coast」と「Yarra」、ジャマイカの教区「Saint Andrew」と「Kingston」。日本の住所では、町村の場合の郡が該当する（政令指定都市の区は「市区町村」側に記録する）。",

  # CLUSTER > items/ELEMENT
  # State/Territory/Province
  ['term', 'at0004', 'text'] => "都道府県／州",

  # CLUSTER > items/ELEMENT
  # The name of a major government district or geographical area that contains the address.
  ['term', 'at0004', 'description'] => "住所を含む主要な行政区域または地理的区域の名称。",

  # CLUSTER > items/ELEMENT
  # Coding with an external terminology is preferred, where possible. For example: 'New South Wales' and 'Queensland' in Australia; 'British Columbia' and 'Nova Scotia' in Canada; and the Counties of 'Cornwall', 'Middlesex' & 'Surrey' in Jamaica.
  ['term', 'at0004', 'comment'] => "可能であれば、外部用語集によりコード化することが望ましい。例：オーストラリアの「New South Wales」と「Queensland」、カナダの「British Columbia」と「Nova Scotia」、ジャマイカの「Cornwall」「Middlesex」「Surrey」の各カウンティ。日本の住所では都道府県が該当し、JIS X 0401 の都道府県コードでコード化できる。",

  # CLUSTER > items/ELEMENT
  # Postal code
  ['term', 'at0005', 'text'] => "郵便番号",

  # CLUSTER > items/ELEMENT
  # The code for a postal delivery area containing the address, as defined by the relevant postal delivery service.
  ['term', 'at0005', 'description'] => "該当する郵便配達サービスが定める、住所を含む郵便配達区域のコード。",

  # CLUSTER > items/ELEMENT
  # Also known as a postcode or ZIP code.
  ['term', 'at0005', 'comment'] => "ポストコードや ZIP コードとも呼ばれる。日本の郵便番号は 7 桁（例：100-0001）。\n",

  # CLUSTER > items/ELEMENT
  # Country
  ['term', 'at0006', 'text'] => "国",

  # CLUSTER > items/ELEMENT
  # The name of the country containing the address.
  ['term', 'at0006', 'description'] => "住所を含む国の名称。",

  # CLUSTER > items/ELEMENT
  # For example: Australia; Canada; Jamaica; or Norway. Coding with an external terminology, such as EN ISO 3166–1 Alpha 2 country code, is recommended.
  ['term', 'at0006', 'comment'] => "例：オーストラリア、カナダ、ジャマイカ、またはノルウェー。EN ISO 3166-1 の 2 文字国コードのような外部用語集によるコード化を推奨する（日本は JP）。",

  # CLUSTER > items/ELEMENT
  # Latitude
  ['term', 'at0007', 'text'] => "緯度",

  # CLUSTER > items/ELEMENT
  # Horizontal (y) coordinate of a geolocation for the address.
  ['term', 'at0007', 'description'] => "住所の地理的位置の水平（y）座標。",

  # CLUSTER > items/ELEMENT
  # Latitude is represented by positive values north of the equator and negative values south of the equator. For example the latitude of the Eiffel Tower is 48.858093.
  ['term', 'at0007', 'comment'] => "緯度は赤道以北を正の値、赤道以南を負の値で表す。例：エッフェル塔の緯度は 48.858093。",

  # CLUSTER > items/ELEMENT
  # Longitude
  ['term', 'at0008', 'text'] => "経度",

  # CLUSTER > items/ELEMENT
  # Horizontal (x) coordinate of a geolocation for the address.
  ['term', 'at0008', 'description'] => "住所の地理的位置の水平（x）座標。",

  # CLUSTER > items/ELEMENT
  # Longitude is represented by negative values west of Prime Meridian and positive values east of Prime Meridian. For example the longitude of the Eiffel Tower is 2.294694.
  ['term', 'at0008', 'comment'] => "経度は本初子午線以西を負の値、本初子午線以東を正の値で表す。例：エッフェル塔の経度は 2.294694。",

  # CLUSTER > items/ELEMENT
  # Altitude
  ['term', 'at0009', 'text'] => "高度",

  # CLUSTER > items/ELEMENT
  # The vertical coordinate of a geolocation representing height or depth of the address.
  ['term', 'at0009', 'description'] => "住所の高さまたは深さを表す、地理的位置の垂直座標。",

  # CLUSTER > items/ELEMENT
  # For example, the altitude of the top of the Eiffel Tower is +324m.
  ['term', 'at0009', 'comment'] => "例：エッフェル塔の頂上の高度は +324 m。",

  # CLUSTER > items/ELEMENT
  # Type
  ['term', 'at0010', 'text'] => "種別",

  # CLUSTER > items/ELEMENT
  # The type of address.
  ['term', 'at0010', 'description'] => "住所の種別。",

  # CLUSTER > items/ELEMENT
  # For example: physical or postal.
  ['term', 'at0010', 'comment'] => "例：物理的所在地または郵送先。",

  # Physical
  ['term', 'at0011', 'text'] => "物理的所在地",

  # A physical location that can be visited.
  ['term', 'at0011', 'description'] => "訪問できる物理的な場所。",

  # Postal
  ['term', 'at0012', 'text'] => "郵送先",

  # Address used as a destination for mailing letters or parcels.
  ['term', 'at0012', 'description'] => "手紙や小包の郵送先として使う住所。",

  # Both
  ['term', 'at0013', 'text'] => "両方",

  # Address of a physical location, also used as a destination for mail.
  ['term', 'at0013', 'description'] => "物理的な場所の住所で、郵送先としても使うもの。",

  # CLUSTER > items/ELEMENT
  # Use
  ['term', 'at0014', 'text'] => "用途",

  # CLUSTER > items/ELEMENT
  # The primary purpose or use for the address.
  ['term', 'at0014', 'description'] => "住所の主な目的または用途。",

  # Business
  ['term', 'at0015', 'text'] => "事業所",

  # Address of the physical location of a business or office.
  ['term', 'at0015', 'description'] => "事業所や事務所の物理的な場所の住所。",

  # Residential
  ['term', 'at0016', 'text'] => "自宅",

  # Address of where a person is living on a regular basis.
  ['term', 'at0016', 'description'] => "個人が常時居住している場所の住所。",

  # Temporary accommodation
  ['term', 'at0017', 'text'] => "一時滞在先",

  # Address of where a person is living on a temporary basis.
  ['term', 'at0017', 'description'] => "個人が一時的に居住している場所の住所。",

  # CLUSTER > items/ELEMENT
  # Comment
  ['term', 'at0018', 'text'] => "コメント",

  # CLUSTER > items/ELEMENT
  # Additional narrative about the address not captured in other fields.
  ['term', 'at0018', 'description'] => "他の項目には収まらない住所についての追加の記述。",

  # CLUSTER > items/ELEMENT
  # Map URL
  ['term', 'at0019', 'text'] => "地図 URL",

  # CLUSTER > items/ELEMENT
  # Link to a location on an online map.
  ['term', 'at0019', 'description'] => "オンライン地図上の場所へのリンク。",

  # CLUSTER > items/ELEMENT
  # For example: a location on a Google or iOS map.
  ['term', 'at0019', 'comment'] => "例：Google マップや iOS のマップ上の場所。",

  # CLUSTER > items/CLUSTER
  # Structured address
  ['term', 'at0020', 'text'] => "構造化された住所",

  # CLUSTER > items/CLUSTER
  # Structured details or extensions to the address.
  ['term', 'at0020', 'description'] => "住所の構造化された詳細または拡張。",

  # CLUSTER > items/CLUSTER
  # For example: to represent a  structured, fine-grained address, or be used as standardised concepts that can be concatenated together to consistently construct a single 'Address line'.
  ['term', 'at0020', 'comment'] => "例：構造化された細かな粒度の住所を表す、または一貫した方法で単一の「住所行」を組み立てるために連結できる標準化された概念として使う。日本の住所では、都道府県・市区町村・町域・丁目・番地・号・建物名・部屋番号とそれぞれの読みを持つ CLUSTER をここに入れる想定。",

  # CLUSTER > items/ELEMENT
  # Geolocation code
  ['term', 'at0021', 'text'] => "位置情報コード",

  # CLUSTER > items/ELEMENT
  # Unique identifier that represents a precise geographical location.
  ['term', 'at0021', 'description'] => "正確な地理的位置を表す一意の識別子。",

  # CLUSTER > items/ELEMENT
  # Also known as a geocode. For example: GPS coordinates concatenating longitude, latitude +/-altitude; Open Location Code or Plus Code; Universal Transverse Mercator (UTM); and geohash.
  ['term', 'at0021', 'comment'] => "ジオコードとも呼ばれる。例：経度、緯度、±高度を連結した GPS 座標；Open Location Code または Plus Code；ユニバーサル横メルカトル（UTM）；および geohash。",

}.freeze

# note 列に残すメモ。迷った訳語には '要確認: ...' を付ける。
NOTES = {
  ['description', '-', 'use'] => "要確認: address lookup service＝住所検索サービス、street-level＝街区レベル、landmark＝目印となる場所。misuse の housing or homelessness＝住居やホームレス状態",
  ['description', '-', 'keywords'] => "要確認: 原文 7 語（住所、郵便、郵送先、自宅、勤務先、所在地、目印）に「事業所」「都道府県」「市区町村」「郵便番号」を追加",
  ['term', 'at0001', 'text'] => "要確認: Address line＝「住所行」を採用（他候補: 住所（行）、番地以下）。comment 末尾に日本の住所での対応（町域〜部屋番号を 1 行）を例示として追加（localisation-ja.md）",
  ['term', 'at0002', 'text'] => "要確認: City/Town＝「市区町村」（localisation-ja.md の対応表。MML4 city＝市・区・郡、town＝町・村 とは区切りが違う）。comment に政令指定都市の扱いと JIS X 0402 を追加",
  ['term', 'at0003', 'text'] => "要確認: District/County＝「地区／郡」（他候補: 郡／地区、郡）。日本では町村の郡のみ該当",
  ['term', 'at0004', 'text'] => "要確認: State/Territory/Province＝「都道府県／州」を採用（日本の対応物を先に置いた。他候補: 州／準州／県、州・県）。comment に JIS X 0401 を追加",
  ['term', 'at0005', 'text'] => "「郵便番号」（MML4 zip）。comment に 7 桁の例を追加",
  ['term', 'at0010', 'text'] => "要確認: Type＝「種別」、値 Physical／Postal／Both＝「物理的所在地／郵送先／両方」（他候補: 所在地／郵送用／両用）",
  ['term', 'at0014', 'text'] => "要確認: Use＝「用途」、値 Business／Residential／Temporary accommodation＝「事業所／自宅／一時滞在先」（MML4 住所の種類 business＝勤務先、home＝自宅 を参考。他候補: 勤務先／居住地／一時的な宿泊先）",
  ['term', 'at0019', 'text'] => "要確認: Map URL＝「地図 URL」",
  ['term', 'at0020', 'text'] => "要確認: Structured address（スロット）＝「構造化された住所」。comment 末尾に日本の構造化住所 CLUSTER（structured_address_jp、localisation-ja.md）を入れる想定を追加",
  ['term', 'at0021', 'text'] => "要確認: Geolocation code＝「位置情報コード」、geocode＝「ジオコード」（他候補: 地理位置コード、ジオロケーションコード）",
}.freeze

src, dst = ARGV
lines = File.readlines(src, chomp: true)
out = [lines.shift]
lines.each do |l|
  c = l.split("\t", -1)
  key = c[1..3]
  c[6] = T.fetch(key).gsub("\n", '\n')
  c[7] = NOTES[key] || ''
  out << c.join("\t")
end
File.write(dst, out.join("\n") + "\n")
