# frozen_string_literal: true
# Japanese translation for openEHR-EHR-SECTION.referral_details.v0
# Generated by tools/scaffold_fill.rb - fill every empty string, following glossary-ja.md.
# Human proofreading: edit work/openEHR-EHR-SECTION.referral_details.v0.ja.tsv and run `make import ID=openEHR-EHR-SECTION.referral_details.v0` (regenerates this file).

T = {
  # To provide an example framework for modelling a referral within a template.
  ['description', '-', 'purpose'] => "テンプレート内で紹介状をモデル化するための枠組みの例を提供するため。",

  # Use to provide an example framework for modelling a referral within a template.
  # 
  # This archetype is intended to be nested within the COMPOSITION.request or any relevant COMPOSITION archetype.
  ['description', '-', 'use'] => "テンプレート内で紹介状をモデル化するための枠組みの例を提供するために用いる。\n\n本archetypeは、COMPOSITION.request または関連する任意の COMPOSITION archetypeの中に入れ子にして用いることを意図している。",

  # referral | request
  ['description', '-', 'keywords'] => "紹介 | 依頼 | 紹介状",

  # © openEHR Foundation
  ['description', '-', 'copyright'] => "© openEHR Foundation",

  # SECTION
  # Referral details
  ['term', 'at0000', 'text'] => "紹介状の詳細",

  # SECTION
  # Example framework for modelling a template for a referral.
  ['term', 'at0000', 'description'] => "紹介状のテンプレートをモデル化するための枠組みの例。",

  # SECTION > items/INSTRUCTION
  # Referral request
  ['term', 'at0001', 'text'] => "紹介依頼",

  # SECTION > items/INSTRUCTION
  # Details about the referral request.
  ['term', 'at0001', 'description'] => "紹介依頼に関する詳細情報。",

  # SECTION > items/ENTRY
  # Details
  ['term', 'at0002', 'text'] => "詳細",

  # SECTION > items/ENTRY
  # Additional clinical details supporting the referral.
  ['term', 'at0002', 'description'] => "紹介を裏付ける追加の臨床的な詳細情報。",

}.freeze

# note 列に残すメモ。迷った訳語には '要確認: ...' を付ける。
NOTES = {
  ['description', '-', 'keywords'] => "原文2語に「紹介状」を追加",
  ['term', 'at0000', 'text'] => "要確認: SECTION 名。「紹介状の詳細」（他候補: 紹介詳細／紹介情報）",
  ['term', 'at0001', 'text'] => "要確認: INSTRUCTION.service_request のスロット。「紹介依頼」（service_request 本体の概念名とは別に、スロット名として簡潔に）",
  ['term', 'at0002', 'text'] => "clinical_synopsis / story / exam / imaging_exam_result / laboratory_test_result のスロット。「詳細」のまま",
}.freeze

src, dst = ARGV
lines = File.readlines(src, chomp: true)
out = [lines.shift]
lines.each do |l|
  c = l.split("\t", -1)
  key = c[1..3]
  c[6] = T.fetch(key).gsub("\n", '\n')
  c[7] = NOTES[key] || ''
  out << c.join("\t")
end
File.write(dst, out.join("\n") + "\n")
