# frozen_string_literal: true
# Japanese translation for openEHR-EHR-OBSERVATION.body_temperature.v2
# Generated by tools/scaffold_fill.rb - fill every empty string, following glossary-ja.md.
# Human proofreading: edit work/openEHR-EHR-OBSERVATION.body_temperature.v2.ja.tsv and run `make import ID=openEHR-EHR-OBSERVATION.body_temperature.v2` (regenerates this file).

T = {
  # To record the measured temperature of a person - as a surrogate for the core body temperature.
  ['description', '-', 'purpose'] => "深部体温の代用として測定された人の体温を記録するため。",

  # Used for recording the measurement of an individual's body temperature, which is a surrogate for the core body temperature of the individual.
  # 
  # Additional clusters can be included to provide additional state data - including environmental conditions and exertion details, where appropriate.
  # 
  # Please Note: The site and method of recording may need to be displayed to the end user to facilitate accurate interpretation of the temperature recorded.
  ['description', '-', 'use'] => "測定対象の個人の深部体温の代用として測定された体温を記録するために用いられる。\nさらに状態データを表すために、追加のクラスタを内包することもできる。たとえば、環境条件や、月経周期の詳細、労作についての詳細を必要に応じて内包する。\n注意：計測された温度を正確に解釈するためにエンドユーザーに記録方法や部位を示す必要があるかもしれない。",

  # This archetype is not to be used to record the temperature of any other object.
  # 
  # This archetype is not to be used to record the temperature of a part of the body in isolation e.g. temperature of the sole of the foot as a part of chronic diabetes management.
  ['description', '-', 'misuse'] => "このアーキタイプは、体温以外を測定するためには用いられない。\nこのアーキタイプは、身体において独立した一部の温度を記録するためには用いられない。たとえば、糖尿病の慢性期管理の一環として、足底温を測定すること。",

  # temperature | body | core | fever | hypothermia | hyperthermia
  ['description', '-', 'keywords'] => "体温 | 人体 | 深部体温 | 発熱 | 低体温 | 高体温",

  # © openEHR Foundation
  ['description', '-', 'copyright'] => "© openEHR Foundation",

  # OBSERVATION
  # Body temperature
  ['term', 'at0000', 'text'] => "体温",

  # OBSERVATION
  # A measurement of the body temperature, which is a surrogate for the core body temperature of the individual.
  ['term', 'at0000', 'description'] => "測定対象の個人の深部体温の代替として測定された体温",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE
  # Tree
  ['term', 'at0001', 'text'] => "Tree",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE
  # @ internal @
  ['term', 'at0001', 'description'] => "@ internal @",

  # OBSERVATION > data/HISTORY
  # History
  ['term', 'at0002', 'text'] => "History",

  # OBSERVATION > data/HISTORY
  # @ internal @
  ['term', 'at0002', 'description'] => "@ internal @",

  # OBSERVATION > data/HISTORY > events/EVENT
  # Any event
  ['term', 'at0003', 'text'] => "任意のイベント",

  # OBSERVATION > data/HISTORY > events/EVENT
  # Default, unspecified point in time or interval event which may be explicitly defined in a template or at run-time.
  ['term', 'at0003', 'description'] => "デフォルトではテンプレートや実行時に明示的に定義されるまで、特定されない時点あるいは一定の間隔のイベント",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE > items/ELEMENT
  # Temperature
  ['term', 'at0004', 'text'] => "体温",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE > items/ELEMENT
  # The measured temperature.
  ['term', 'at0004', 'description'] => "測定された体温",

  # OBSERVATION > protocol/ITEM_TREE
  # Protocol
  ['term', 'at0020', 'text'] => "Protocol",

  # OBSERVATION > protocol/ITEM_TREE
  # @ internal @
  ['term', 'at0020', 'description'] => "@ internal @",

  # OBSERVATION > protocol/ITEM_TREE > items/ELEMENT
  # Location of measurement
  ['term', 'at0021', 'text'] => "測定部位",

  # OBSERVATION > protocol/ITEM_TREE > items/ELEMENT
  # Simple description about the site of measurement.
  ['term', 'at0021', 'description'] => "測定部位についての簡単な記述。",

  # Mouth
  ['term', 'at0022', 'text'] => "口腔",

  # Temperature is measured within the mouth.
  ['term', 'at0022', 'description'] => "口腔内で測定された温度",

  # Ear canal
  ['term', 'at0023', 'text'] => "外耳道",

  # Temperature is measured from within the external auditory canal.
  ['term', 'at0023', 'description'] => "外耳道内で測定された温度。",

  # Axilla
  ['term', 'at0024', 'text'] => "腋窩",

  # Temperature is measured from the skin of the axilla with the arm positioned down by the side.
  ['term', 'at0024', 'description'] => "腕を脇につけた状態で測定された腋窩の皮膚から測定された温度。",

  # Rectum
  ['term', 'at0025', 'text'] => "直腸",

  # Temperature measured within the rectum.
  ['term', 'at0025', 'description'] => "直腸内で測定された温度。",

  # Nasopharynx
  ['term', 'at0026', 'text'] => "鼻咽頭",

  # Temperature is measured within the nasopharynx.
  ['term', 'at0026', 'description'] => "鼻咽頭内で測定された温度。",

  # Urinary bladder
  ['term', 'at0027', 'text'] => "膀胱",

  # Temperature is measured in the urinary bladder.
  ['term', 'at0027', 'description'] => "膀胱内で測定された温度",

  # Intravascular
  ['term', 'at0028', 'text'] => "血管内",

  # Temperature is measured within the vascular system.
  ['term', 'at0028', 'description'] => "血管系の内部で測定された温度。",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE
  # State
  ['term', 'at0029', 'text'] => "状態",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE
  # State information about the patient.
  ['term', 'at0029', 'description'] => "患者の状態についての情報",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE > items/ELEMENT
  # Body exposure
  ['term', 'at0030', 'text'] => "身体暴露",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE > items/ELEMENT
  # The degree of exposure of the individual at the time of measurement.
  ['term', 'at0030', 'description'] => "体温を計測した際の対象個人の露出状況",

  # Naked
  ['term', 'at0031', 'text'] => "裸体",

  # No clothing, bedding or covering.
  ['term', 'at0031', 'description'] => "着衣、寝具や被服がない状態",

  # Reduced clothing/bedding
  ['term', 'at0032', 'text'] => "着衣や寝具が減らされている状態",

  # The person is covered by a lesser amount of clothing or bedding than deemed appropriate for the environmental circumstances.
  ['term', 'at0032', 'description'] => "計測対象が周辺環境として適切と見なされるよりも少ない着衣や寝具に覆われた状態",

  # Appropriate clothing/bedding
  ['term', 'at0033', 'text'] => "適切な着衣、寝具が与えられている状態",

  # The person is covered by an amount of clothing or bedding deemed appropriate for the environmental circumstances.
  ['term', 'at0033', 'description'] => "計測対象者が着衣や寝具が周囲の環境として適切と考えられる量で覆われている状態",

  # Increased clothing/bedding
  ['term', 'at0034', 'text'] => "過剰な着衣や寝具",

  # The person is covered by an increased amount of clothing or bedding than deemed appropriate for the environmental circumstances.
  ['term', 'at0034', 'description'] => "計測対象者が環境として適切であると考えられる量よりも多くの着衣や寝具で覆われている状態。",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE > items/ELEMENT
  # Description of thermal stress
  ['term', 'at0041', 'text'] => "熱応力についての記載",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE > items/ELEMENT
  # Narrative description of the conditions applied to the subject that might influence their measured body temperature.
  ['term', 'at0041', 'description'] => "測定された体温に影響を与えうる対象個人の状況についての叙述的記録",

  # Skin
  ['term', 'at0043', 'text'] => "皮膚",

  # Temperature is measured from exposed skin.
  ['term', 'at0043', 'description'] => "露出された皮膚で測定された温度。",

  # Vagina
  ['term', 'at0051', 'text'] => "膣",

  # Temperature is measured within the vagina.
  ['term', 'at0051', 'description'] => "膣内で測定された温度。",

  # Oesophagus
  ['term', 'at0054', 'text'] => "食道",

  # Temperatue is measured within the oesophagus.
  ['term', 'at0054', 'description'] => "食道内で測定された温度。",

  # Inguinal skin crease
  ['term', 'at0055', 'text'] => "鼠径溝",

  # Temperature is measured in the inguinal skin crease between the leg and abdominal wall.
  ['term', 'at0055', 'description'] => "下肢と腹壁の間にある鼠径溝で測定された温度。",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE > items/CLUSTER
  # Environmental conditions
  ['term', 'at0056', 'text'] => "環境条件",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE > items/CLUSTER
  # Details about the environmental conditions at the time of temperature measurement.
  ['term', 'at0056', 'description'] => "体温を測定した時点での環境条件についての詳細。",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE > items/CLUSTER
  # Exertion
  ['term', 'at0057', 'text'] => "労作",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE > items/CLUSTER
  # Details about the exertion of the person at the time of temperature measurement.
  ['term', 'at0057', 'description'] => "体温を測定した時点での労作状態についての詳細",

  # OBSERVATION > protocol/ITEM_TREE > items/CLUSTER
  # Device
  ['term', 'at0059', 'text'] => "機器",

  # OBSERVATION > protocol/ITEM_TREE > items/CLUSTER
  # Details about the device used to measure body temperature.
  ['term', 'at0059', 'description'] => "体温の測定に用いた機器に関する詳細情報。",

  # Temple
  ['term', 'at0060', 'text'] => "側頭部",

  # Temperature is measured at the temple, over the superficial temporal artery.
  ['term', 'at0060', 'description'] => "側頭部（浅側頭動脈の上）で測定された温度。",

  # Forehead
  ['term', 'at0061', 'text'] => "前額部",

  # Temperature is measured on the forehead.
  ['term', 'at0061', 'description'] => "前額部で測定された温度。",

  # OBSERVATION > protocol/ITEM_TREE > items/CLUSTER
  # Extension
  ['term', 'at0062', 'text'] => "Extension",

  # OBSERVATION > protocol/ITEM_TREE > items/CLUSTER
  # Additional information required to extend the model with local content or to align with other reference models or formalisms.
  ['term', 'at0062', 'description'] => "ローカルコンテンツでモデルを拡張するため、あるいは他の参照モデルや形式手法と整合させるために必要な追加情報。",

  # OBSERVATION > protocol/ITEM_TREE > items/CLUSTER
  # For example: local information requirements; or additional metadata to align with FHIR.
  ['term', 'at0062', 'comment'] => "例：ローカルな情報要件や、FHIR に適合させるための追加メタデータ。",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE > items/ELEMENT
  # Comment
  ['term', 'at0063', 'text'] => "コメント",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE > items/ELEMENT
  # Additional comment about the body temperature measurement not captured in other fields.
  ['term', 'at0063', 'description'] => "他のフィールドで記録されない体温についての追加コメント",

  # OBSERVATION > protocol/ITEM_TREE > items/CLUSTER
  # Structured measurement location
  ['term', 'at0064', 'text'] => "構造化された測定部位",

  # OBSERVATION > protocol/ITEM_TREE > items/CLUSTER
  # Structured details about the location of measurement.
  ['term', 'at0064', 'description'] => "測定部位に関する構造化された詳細情報。",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE > items/ELEMENT
  # Day of menstrual cycle
  ['term', 'at0065', 'text'] => "月経周期の日",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE > items/ELEMENT
  # Current day of the menstrual cycle.
  ['term', 'at0065', 'description'] => "月経周期における現在の日",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE > items/ELEMENT
  # The first day of menstruation is considered to be Day 1 of each menstrual cycle.
  ['term', 'at0065', 'comment'] => "月経初日をそれぞれの月経周期で1日目と考える。",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE > items/ELEMENT
  # Confounding factors
  ['term', 'at0066', 'text'] => "交絡因子",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE > items/ELEMENT
  # Additional issues or factors that may impact on the measurement of body temperature, not captured in other fields.
  ['term', 'at0066', 'description'] => "他の項目には収まらない、体温の測定に影響する可能性のある問題や因子。",

}.freeze

# note 列に残すメモ。迷った訳語には '要確認: ...' を付ける。
NOTES = {
  # ['term', 'at0000', 'text'] => '要確認: ...',
}.freeze

src, dst = ARGV
lines = File.readlines(src, chomp: true)
out = [lines.shift]
lines.each do |l|
  c = l.split("\t", -1)
  key = c[1..3]
  c[6] = T.fetch(key).gsub("\n", '\n')
  c[7] = NOTES[key] || ''
  out << c.join("\t")
end
File.write(dst, out.join("\n") + "\n")
