# frozen_string_literal: true
# Japanese translation for openEHR-EHR-CLUSTER.problem_qualifier.v2
# Generated by tools/scaffold_fill.rb - fill every empty string, following glossary-ja.md.
# Human proofreading: edit work/openEHR-EHR-CLUSTER.problem_qualifier.v2.ja.tsv and run `make import ID=openEHR-EHR-CLUSTER.problem_qualifier.v2` (regenerates this file).

T = {
  # To record a clinical context-specific or time-specific qualifier for a specified problem or diagnosis.
  ['description', '-', 'purpose'] => "特定のプロブレムまたは診断に対する、臨床的な文脈や時点に固有の修飾子を記録するため。",

  # Use to record a relevant context-specific or time-specific qualifier that provides additional detail which is relevant at the time of recording or within the clinical context where a problem or diagnosis is recorded. The qualifier may not be appropriate at another time or in another clinical context. 
  # 
  # This archetype is designed to be included in Status SLOT in the EVALUATION.problem_diagnosis archetype. The intent is for the EVALUATION.problem_diagnosis archetype to hold all of the information that applies in all contexts, in contrast to this archetype describing only information that depends on the context of use.
  # 
  # IMPORTANT NOTES FOR IMPLEMENTATION: 
  # - It is not intended or implied that any or all of these qualifiers should be used within the same context or period of time. In contrast to the usual design of archetypes, this archetype has been deliberately designed to collect a number of common qualifiers into one place in an effort to attempt some simple standardisation within a very messy area of clinical practice. It is acknowledged that the data elements contained in this archetype embrace many different, and sometimes even competing, concepts. This has been done mainly to prevent the need for multiple qualifier archetypes, each containing only one or two data elements. 
  # - Some of these data elements are potentially directly conflicting if used simultaneously within the same context, for example it would not make sense to have an 'inactive' problem together with an Episode that is 'ongoing'. As such, these status qualifiers should be used with extreme care as they are variably applied in practice and interoperability cannot be assured unless usage guidelines are clearly defined within the clinical community in which the 'Problem/Diagnosis' and 'Problem/Diagnosis qualifier' archetype pair may be shared. 
  # 
  # Full DRG coding will require the DRG-related data elements from this archetype in combination with data elements from other archetypes.
  ['description', '-', 'use'] => "記録時点、またはプロブレムや診断が記録される臨床的な文脈において追加の意味を持つ詳細情報を提供するために、固有の文脈や固有の時点への修飾子を記録する。その修飾子は、別の時点や別の臨床的な文脈では適切でないことがある。 \n\n本archetypeは、EVALUATION.problem_diagnosis archetypeの「状態」SLOT に含めて使うよう設計されている。EVALUATION.problem_diagnosis archetypeがあらゆる文脈で当てはまる情報をすべて保持するのに対し、本archetypeは使用文脈に依存する情報だけを記述する、という意図である。\n\n実装上の重要な注意： \n- これらの修飾子のいずれか、またはすべてを同じ文脈や同じ期間の中で使うことを意図したり示唆したりするものではない。通常のarchetype設計とは対照的に、本archetypeは、臨床実践の中でも非常に混沌とした領域にいくらかの単純な標準化を試みるため、よく使われる多数の修飾子を意図的に一か所に集めて設計されている。本archetypeに含まれるデータ要素が、多くの異なる、ときには互いに競合する概念を包含していることは認識している。これは主に、データ要素を1つか2つしか持たない修飾子archetypeが多数必要になるのを避けるためである。 \n- これらのデータ要素の一部は、同じ文脈の中で同時に使うと直接矛盾する可能性がある。例えば、「インアクティブ」のプロブレムに「継続中」のエピソードが同時に付くのは意味をなさない。したがって、これらの状態修飾子は実践の中でさまざまに適用されており、「プロブレム・診断」と「プロブレム・診断の修飾子」のarchetypeの組を共有しうる臨床コミュニティの中で使用指針が明確に定義されない限り相互運用性は保証できないため、細心の注意を払って使うこと。 \n\nDRG コーディングを完全に行うには、本archetypeの DRG 関連データ要素を他のarchetypeのデータ要素と組み合わせる必要がある。",

  # Not to be used to represent a differential diagnosis - use the archetype EVALUATION.differential_diagnosis for this purpose.
  # 
  # Not to be used to represent diagnostic certainty - use the 'Diagnostic certainty' data element within the EVALUATION.problem_diagnosis archetype.
  ['description', '-', 'misuse'] => "鑑別診断を表すために用いてはならない。その目的には EVALUATION.differential_diagnosis archetypeを用いること。\n\n診断確度を表すために用いてはならない。EVALUATION.problem_diagnosis archetype内の「診断確度」データエレメントを用いること。",

  # problem | active | inactive | status | episode | diagnosis
  ['description', '-', 'keywords'] => "プロブレム | アクティブ | インアクティブ | 状態 | エピソード | 診断 | 修飾子 | 病名",

  # © openEHR Foundation
  ['description', '-', 'copyright'] => "© openEHR Foundation",

  # CLUSTER
  # Problem/Diagnosis qualifier
  ['term', 'at0000', 'text'] => "プロブレム・診断の修飾子",

  # CLUSTER
  # Contextual or temporal qualifier for a specified problem or diagnosis.
  ['term', 'at0000', 'description'] => "特定のプロブレムまたは診断に対する、文脈的または時間的な修飾子。",

  # CLUSTER > items/ELEMENT
  # Episodicity
  ['term', 'at0001', 'text'] => "エピソード区分",

  # CLUSTER > items/ELEMENT
  # Category of this episode for the identified problem/diagnosis.
  ['term', 'at0001', 'description'] => "特定のプロブレム・診断における、このエピソードの区分。",

  # CLUSTER > items/ELEMENT
  # For example: 'New' will enable clinicians to distinguish a new, acute episode of otitis media that may have arisen soon after a previous diagnosis, to distinguish it from an unresolved or 'Ongoing' diagnosis of chronic otitis media. Treatment of recurring, new and acute, episodes of a condition may differ significantly from the same condition that is not resolving or responding to treatment. In many situations the clinician will not be able to tell, and so indeterminate may be appropriate.
  ['term', 'at0001', 'comment'] => "例：「新規」により、以前の診断の直後に生じたかもしれない新たな急性の中耳炎エピソードを、未治癒または「継続中」の慢性中耳炎の診断と区別できる。繰り返し生じる新規の急性エピソードの治療は、治癒に向かわない、または治療に反応しない同じ病態の治療とは大きく異なることがある。多くの状況では臨床医には判断できないため、「判定不能」が適切な場合もある。",

  # CLUSTER > items/ELEMENT
  # Active/Inactive?
  ['term', 'at0003', 'text'] => "アクティブ/インアクティブ？",

  # CLUSTER > items/ELEMENT
  # Category that supports division of problems and diagnoses into Active or Inactive problem lists.
  ['term', 'at0003', 'description'] => "プロブレムと診断を「アクティブ」と「インアクティブ」のプロブレムリストに分けることを支援する区分。",

  # CLUSTER > items/ELEMENT
  # The Active/Inactive and Current/Past data elements have similar clinical impact but represent slightly different semantics. Both are actively used in different clinical settings, but usually not together. If a Current/Past qualifier is recorded, then this data element is likely to be redundant. An exception where a condition can be current but inactive is asthma that is not causing acute symptoms.
  ['term', 'at0003', 'comment'] => "「アクティブ/インアクティブ」と「現症/既往」のデータ要素は、臨床的な影響は似ているが意味がわずかに異なる。どちらも異なる臨床現場で実際に使われているが、通常は一緒には使われない。「現症/既往」の修飾子が記録されている場合、このデータ要素は冗長になる可能性が高い。現症ではあるがインアクティブという例外として、急性症状を起こしていない喘息がある。",

  # CLUSTER > items/ELEMENT
  # Diagnostic status
  ['term', 'at0004', 'text'] => "診断状況",

  # CLUSTER > items/ELEMENT
  # Stage or phase of diagnostic process.
  ['term', 'at0004', 'description'] => "診断プロセスの段階または局面。",

  # CLUSTER > items/ELEMENT
  # The status is usually determined by a combination of the timing of diagnosis plus level of clinical certainty resulting from diagnostic tests and clinical evidence available. This data element and 'Diagnostic certainty' in EVALUATION.problem_diagnosis are two important axes of the diagnostic process, and valid combinations will need to be presented by software that exposes both data elements, so it is not possible for users to select conflicting combinations. 
  # Preliminary or working diagnoses are intended to represent the single most likely choice out of all differential diagnosis options.
  ['term', 'at0004', 'comment'] => "この状況は通常、診断の時期と、実施した臨床検査および得られている臨床的根拠から導かれる臨床的確度の水準との組み合わせで決まる。このデータ要素と EVALUATION.problem_diagnosis の「診断確度」は診断プロセスの2つの重要な軸であり、両方のデータ要素を提示するソフトウェアは、利用者が矛盾する組み合わせを選べないように、妥当な組み合わせを提示する必要がある。 \n予備的診断または暫定診断は、すべての鑑別診断の選択肢の中で最も可能性の高い単一の選択を表すことを意図している。",

  # Preliminary
  ['term', 'at0016', 'text'] => "予備的",

  # The initial diagnosis made, usually associated with a low level of clinical certainty. It may change as test results or advice become available.
  ['term', 'at0016', 'description'] => "最初に下された診断で、通常は臨床的確度が低い。検査結果や助言が得られるにつれて変わることがある。",

  # Working
  ['term', 'at0017', 'text'] => "暫定",

  # Interim diagnosis, based on a reasonable amount of clinical certainty but pending further test results or clinical advice. It may still change as test results or advice become available.
  ['term', 'at0017', 'description'] => "相応の臨床的確度に基づくが、さらなる検査結果や臨床的助言を待っている中間段階の診断。検査結果や助言が得られるにつれて、なお変わることがある。",

  # Established
  ['term', 'at0018', 'text'] => "最終",

  # Final substantiated diagnosis, based on a high level of clinical certainty, which may include clinical evidence from test results. It is not expected to change.
  ['term', 'at0018', 'description'] => "高い臨床的確度に基づいて裏付けられた最終的な診断で、検査結果による臨床的根拠を含むことがある。変わることは想定されていない。",

  # Active
  ['term', 'at0026', 'text'] => "アクティブ",

  # The problem or diagnosis is currently active and clinically relevant.
  ['term', 'at0026', 'description'] => "プロブレムまたは診断は現在有効であり、臨床的に意味を持つ。",

  # Inactive
  ['term', 'at0027', 'text'] => "インアクティブ",

  # The problem or diagnosis is not completely resolved but is inactive or felt less relevant to the current clinical context.
  ['term', 'at0027', 'description'] => "プロブレムまたは診断は完全には治癒していないが、無効であるか、現在の臨床的文脈では重要性が低いと考えられる。",

  # New
  ['term', 'at0034', 'text'] => "新規",

  # A new occurrence of either a new or existing problem or diagnosis. A flag for 'First occurrence' can be recorded separately to distinguish the first from other occurrences.
  ['term', 'at0034', 'description'] => "新しい、または既存のプロブレムまたは診断の新たな発生。最初の発生を他の発生と区別するために、「初発」のフラグを別に記録できる。",

  # Ongoing
  ['term', 'at0035', 'text'] => "継続中",

  # The issue, problem or diagnosis continues, without new, acute episodes occurring.
  ['term', 'at0035', 'description'] => "問題、プロブレム、または診断が、新たな急性エピソードを生じることなく続いている。",

  # CLUSTER > items/ELEMENT
  # Current/Past?
  ['term', 'at0060', 'text'] => "現症/既往？",

  # CLUSTER > items/ELEMENT
  # Category that supports division of problems and diagnoses into Current or Past problem lists.
  ['term', 'at0060', 'description'] => "プロブレムと診断を「現症」と「既往」のプロブレムリストに分けることを支援する区分。",

  # CLUSTER > items/ELEMENT
  # The Current/Past and Active/Inactive data elements have similar clinical impact but represent slightly different semantics. Both are actively used in different clinical settings, but usually not together. If an Active/Inactive qualifier is recorded, then this data element is likely to be redundant. An exception where a condition can be current but inactive is asthma that is not causing acute symptoms.
  ['term', 'at0060', 'comment'] => "「現症/既往」と「アクティブ/インアクティブ」のデータ要素は、臨床的な影響は似ているが意味がわずかに異なる。どちらも異なる臨床現場で実際に使われているが、通常は一緒には使われない。「アクティブ/インアクティブ」の修飾子が記録されている場合、このデータ要素は冗長になる可能性が高い。現症ではあるがインアクティブという例外として、急性症状を起こしていない喘息がある。",

  # Past
  ['term', 'at0061', 'text'] => "既往",

  # An issue which ocurred in the past.
  ['term', 'at0061', 'description'] => "過去に発生した問題。",

  # Current
  ['term', 'at0062', 'text'] => "現症",

  # An issue occuring at present.
  ['term', 'at0062', 'description'] => "現在発生している問題。",

  # CLUSTER > items/ELEMENT
  # Diagnostic category
  ['term', 'at0063', 'text'] => "診断カテゴリ",

  # CLUSTER > items/ELEMENT
  # Category of the problem or diagnosis within a specified episode of care and/or local care context.
  ['term', 'at0063', 'description'] => "特定のケアエピソードおよび／またはローカルなケアの文脈における、プロブレムまたは診断のカテゴリ。",

  # CLUSTER > items/ELEMENT
  # This data element contains a value set commonly used in diagnostic categorisation. In episodic care contexts (commonly secondary care) it is common to categorise/organise diagnoses according to their relationship to the principal diagnosis being addressed during that episode of care. These categories may also be used for clinical coding, reporting and billing purposes. In some countries the diagnostic category may be known as a DRG.
  #  In addition, the free text choice permits use of other local value sets, as required.
  ['term', 'at0063', 'comment'] => "このデータ要素は、診断の分類でよく使われる値セットを含む。エピソード型のケアの文脈（一般には二次医療）では、そのケアエピソードで扱われる主病名との関係に従って診断を分類・整理するのが一般的である。これらのカテゴリは、臨床コーディング、報告、請求の目的にも使われることがある。国によっては、診断カテゴリは DRG として知られている場合がある。\n さらに、自由記述の選択肢により、必要に応じて他のローカルな値セットも使用できる。",

  # Principal diagnosis
  ['term', 'at0064', 'text'] => "主病名",

  # The diagnosis determined to be the primary reason for an episode of admitted patient care, an episode of residential care or an attendance at the health care establishment.
  ['term', 'at0064', 'description'] => "入院患者ケアのエピソード、施設ケアのエピソード、または医療機関への受診の主たる理由と判断された診断。",

  # Secondary diagnosis
  ['term', 'at0066', 'text'] => "副病名",

  # A problem or diagnosis that occurs at the same time as the primary problem or diagnosis. May also be known as a comorbid condition.
  ['term', 'at0066', 'description'] => "主たるプロブレムまたは病名と同時に存在するプロブレムまたは病名。併存疾患とも呼ばれる。",

  # Indeterminate
  ['term', 'at0070', 'text'] => "判定不能",

  # It is not possible to determine if this occurrence of the problem or diagnosis is new or ongoing.
  ['term', 'at0070', 'description'] => "このプロブレムまたは診断の今回の発生が新規か継続中かを判定できない。",

  # CLUSTER > items/ELEMENT
  # Occurrence
  ['term', 'at0071', 'text'] => "発生区分",

  # CLUSTER > items/ELEMENT
  # Category of the occurrence for this problem or diagnosis.
  ['term', 'at0071', 'description'] => "このプロブレムまたは診断の発生の区分。",

  # CLUSTER > items/ELEMENT
  # This data element can be an additional qualifier to the 'New' value in the 'Episodicity' value set, that is a condition such as asthma can have recurring new episodes that have periods of resolution in between. However it can be important to identify the first ever episode of asthma from all of the other episodes.
  ['term', 'at0071', 'comment'] => "このデータ要素は、「エピソード区分」の値セットの「新規」に対する追加の修飾子になりうる。すなわち、喘息のような病態は、間に治癒している期間を挟んで新規のエピソードを繰り返すことがある。しかし、喘息の最初のエピソードを他のすべてのエピソードから識別することが重要な場合がある。",

  # CLUSTER > items/ELEMENT
  # Admission diagnosis?
  ['term', 'at0073', 'text'] => "入院時診断？",

  # CLUSTER > items/ELEMENT
  # Was the problem or diagnosis present at admission?
  ['term', 'at0073', 'description'] => "入院時にそのプロブレムまたは診断が存在したか。",

  # CLUSTER > items/ELEMENT
  # Record as True or 'Yes' if the problem or diagnosis was present on admission. This data element is a requirement from DRG reporting in some countries.
  ['term', 'at0073', 'comment'] => "入院時にそのプロブレムまたは診断が存在していた場合は True または「はい」と記録する。このデータ要素は、国によっては DRG 報告の要件である。",

  # Complication
  ['term', 'at0076', 'text'] => "合併症",

  # An unfavorable evolution of a problem or diagnosis.
  ['term', 'at0076', 'description'] => "プロブレムまたは診断の好ましくない推移。",

  # CLUSTER > items/ELEMENT
  # Course label
  ['term', 'at0077', 'text'] => "経過区分",

  # CLUSTER > items/ELEMENT
  # Category reflecting the speed of onset and/or duration and persistence of the problem or diagnosis.
  ['term', 'at0077', 'description'] => "プロブレムまたは診断の発症の速さおよび／または持続期間と持続性を反映する区分。",

  # CLUSTER > items/ELEMENT
  # Definitions of acute vs chronic will differ for each diagnosis.
  ['term', 'at0077', 'comment'] => "急性と慢性の定義は診断ごとに異なる。",

  # Chronic
  ['term', 'at0079', 'text'] => "慢性",

  # A problem or diagnosis with persistent or long-lasting effects, or that evolves over time.
  ['term', 'at0079', 'description'] => "持続的または長期にわたる影響を持つ、あるいは時間とともに推移するプロブレムまたは診断。",

  # Acute
  ['term', 'at0081', 'text'] => "急性",

  # A problem or diagnosis with a rapid onset, a short course, or both.
  ['term', 'at0081', 'description'] => "発症が急速である、経過が短い、またはその両方であるプロブレムまたは診断。",

  # CLUSTER > items/ELEMENT
  # Resolution phase
  ['term', 'at0083', 'text'] => "治癒段階",

  # CLUSTER > items/ELEMENT
  # Phase of healing for an acute problem or diagnosis.
  ['term', 'at0083', 'description'] => "急性のプロブレムまたは診断の治癒の局面。",

  # CLUSTER > items/ELEMENT
  # For example: tracking the progress of resolution of a middle ear infection.
  ['term', 'at0083', 'comment'] => "例：中耳炎の治癒の進み具合の追跡。",

  # Resolved
  ['term', 'at0084', 'text'] => "治癒",

  # Problem or diagnosis has completed the normal phases of restoration or healing and can be considered resolved.
  ['term', 'at0084', 'description'] => "プロブレムまたは診断が回復または治癒の通常の局面を終え、治癒したとみなせる。",

  # Resolving
  ['term', 'at0085', 'text'] => "回復中",

  # Problem or diagnosis is progressing satisfactorily through the normal stages of restoration or healing towards resolution.
  ['term', 'at0085', 'description'] => "プロブレムまたは診断が、回復または治癒の通常の段階を経て治癒に向かって順調に進んでいる。",

  # Not resolving
  ['term', 'at0086', 'text'] => "未回復",

  # Problem or diagnosis is not progressing satisfactorily through the normal stages of restoration or healing towards resolution.
  ['term', 'at0086', 'description'] => "プロブレムまたは診断が、回復または治癒の通常の段階を経て治癒に向かって順調には進んでいない。",

  # Indeterminate
  ['term', 'at0087', 'text'] => "判定不能",

  # It is not possible to determine the resolution or healing status of the problem or diagnosis.
  ['term', 'at0087', 'description'] => "プロブレムまたは診断の治癒の状況を判定できない。",

  # Refuted
  ['term', 'at0088', 'text'] => "否定",

  # The previously recorded diagnosis has been clinically reassessed or disproved with a high level of clinical certainty. This status is used to correct an error in the health record.
  ['term', 'at0088', 'description'] => "以前に記録された診断が、臨床的に再評価されたか、高い臨床的確度をもって誤りと判明した。この状態は健康記録の誤りを訂正するために用いる。",

  # CLUSTER > items/ELEMENT
  # Remission status
  ['term', 'at0089', 'text'] => "寛解状態",

  # CLUSTER > items/ELEMENT
  # Status of the remission of an incurable diagnosis.
  ['term', 'at0089', 'description'] => "治癒しない診断の寛解の状態。",

  # CLUSTER > items/ELEMENT
  # For example: the status of a cancer or haematological diagnosis.
  ['term', 'at0089', 'comment'] => "例：がんや血液疾患の診断の状態。",

  # In remission
  ['term', 'at0090', 'text'] => "寛解中",

  # No ongoing signs or symptoms of the disease have been identified.
  ['term', 'at0090', 'description'] => "その疾患の徴候や症状が現在認められない。",

  # Not in remission
  ['term', 'at0092', 'text'] => "非寛解",

  # No diminution of the signs or symptoms of the disease have been identified.
  ['term', 'at0092', 'description'] => "その疾患の徴候や症状の軽減が認められない。",

  # Indeterminate
  ['term', 'at0093', 'text'] => "判定不能",

  # It is not possible to determine if there have been diminution of the signs or symptoms of the disease have been identified.
  ['term', 'at0093', 'description'] => "その疾患の徴候や症状の軽減があったかどうかを判定できない。",

  # Acute-on-chronic
  ['term', 'at0094', 'text'] => "慢性疾患の急性増悪",

  # A problem or diagnosis with an acute exacerbation of a chronic condition.
  ['term', 'at0094', 'description'] => "慢性期の病態の急性増悪を伴うプロブレムまたは診断。",

  # First occurrence
  ['term', 'at0095', 'text'] => "初発",

  # This is the first ever occurrence of this problem or diagnosis.
  ['term', 'at0095', 'description'] => "このプロブレムまたは診断の、初めての発生である。",

  # Recurrence
  ['term', 'at0096', 'text'] => "再発",

  # New occurrence of the same problem or diagnosis after a previous episode was resolved.
  ['term', 'at0096', 'description'] => "以前のエピソードが治癒した後の、同じプロブレムまたは診断の新たな発生。",

  # Relapsed
  ['term', 'at0097', 'text'] => "再燃",

  # Problem or diagnosis has deteriorated after a period of temporary improvement.
  ['term', 'at0097', 'description'] => "一時的な改善の期間の後に、プロブレムまたは診断が悪化した。",

  # CLUSTER > items/ELEMENT
  # Level of control
  ['term', 'at0098', 'text'] => "コントロール状況",

  # CLUSTER > items/ELEMENT
  # Category of the level of control of the problem or diagnosis by the current management.
  ['term', 'at0098', 'description'] => "現在の管理によるプロブレムまたは診断のコントロールの程度の区分。",

  # Controlled
  ['term', 'at0099', 'text'] => "コントロール良好",

  # The problem or diagnosis is controlled by current management.
  ['term', 'at0099', 'description'] => "プロブレムまたは診断は現在の管理によりコントロールされている。",

  # Indeterminate
  ['term', 'at0100', 'text'] => "判定不能",

  # It is not possible to determine if the problem or diagnosis is controlled by current management.
  ['term', 'at0100', 'description'] => "プロブレムまたは診断が現在の管理によりコントロールされているかどうかを判定できない。",

  # Not controlled
  ['term', 'at0101', 'text'] => "コントロール不良",

  # The problem or diagnosis is not controlled by current management.
  ['term', 'at0101', 'description'] => "プロブレムまたは診断は現在の管理によりコントロールされていない。",

  # CLUSTER > items/ELEMENT
  # Progression
  ['term', 'at0102', 'text'] => "進行状況",

  # CLUSTER > items/ELEMENT
  # Category of the progression through the course of a chronic problem or diagnosis.
  ['term', 'at0102', 'description'] => "慢性のプロブレムまたは診断の経過における進行の区分。",

  # Improving
  ['term', 'at0103', 'text'] => "改善",

  # The problem or diagnosis is improving.
  ['term', 'at0103', 'description'] => "プロブレムまたは診断は改善している。",

  # Stable
  ['term', 'at0104', 'text'] => "安定",

  # The problem or diagnosis is unchanged.
  ['term', 'at0104', 'description'] => "プロブレムまたは診断は変化していない。",

  # Worsening
  ['term', 'at0105', 'text'] => "悪化",

  # The problem or diagnosis is worsening.
  ['term', 'at0105', 'description'] => "プロブレムまたは診断は悪化している。",

  # Indeterminate
  ['term', 'at0106', 'text'] => "判定不能",

  # It is not possible to determine the progression of the problem or diagnosis.
  ['term', 'at0106', 'description'] => "プロブレムまたは診断の進行状況を判定できない。",

  # CLUSTER > items/ELEMENT
  # Reason for an ongoing episode
  ['term', 'at0107', 'text'] => "継続中エピソードの理由",

  # CLUSTER > items/ELEMENT
  # Reason for a problem or diagnosis not resolving as expected.
  ['term', 'at0107', 'description'] => "プロブレムまたは診断が予想どおりに治癒しない理由。",

  # CLUSTER > items/ELEMENT
  # For example: incomplete or failed treatment.
  ['term', 'at0107', 'comment'] => "例：治療の不完全または失敗。",

  # Yes
  ['term', 'at0108', 'text'] => "はい",


  ['term', 'at0108', 'description'] => '',

  # No
  ['term', 'at0109', 'text'] => "いいえ",


  ['term', 'at0109', 'description'] => '',

  # CLUSTER > items/ELEMENT
  # Comment
  ['term', 'at0110', 'text'] => "コメント",

  # CLUSTER > items/ELEMENT
  # Additional narrative about the Problem/Diagnosis qualifier values, not captured in other fields.
  ['term', 'at0110', 'description'] => "他の項目では捉えられない、プロブレム・診断の修飾子の値についての追加の記述。",

  # CLUSTER > items/ELEMENT
  # Disorder category
  ['term', 'at0111', 'text'] => "疾患カテゴリ",

  # CLUSTER > items/ELEMENT
  # A high‑level grouping of the problem or diagnosis.
  ['term', 'at0111', 'description'] => "プロブレムまたは診断の高次の分類。",

  # CLUSTER > items/ELEMENT
  # For example: 'Cancer', 'Mental health and/or addiction', 'Infectious disease', 'Rare disease'. 
  # Coding with a terminology is preferred, where possible.
  ['term', 'at0111', 'comment'] => "例：「がん」「精神保健および／または依存症」「感染症」「希少疾患」。 \n可能であれば、用語集によりコード化することが望ましい。",

}.freeze

# note 列に残すメモ。迷った訳語には '要確認: ...' を付ける。
NOTES = {
  ['term', 'at0064', 'text'] => "日本では保険上の取り扱いもあり、主診断や主要病名というよりも主病名が一般的と考える。",
  ['term', 'at0071', 'text'] => "要確認: 「発生区分」を採用（他候補: 発生、出現）",
  ['term', 'at0111', 'text'] => "要確認: 「疾患カテゴリ」を採用（他候補: 疾患区分）。例示の Mental health and/or addiction は「精神保健および／または依存症」",
}.freeze

src, dst = ARGV
lines = File.readlines(src, chomp: true)
out = [lines.shift]
lines.each do |l|
  c = l.split("\t", -1)
  key = c[1..3]
  c[6] = T.fetch(key).gsub("\n", '\n')
  c[7] = NOTES[key] || ''
  out << c.join("\t")
end
File.write(dst, out.join("\n") + "\n")
