#!/usr/bin/env ruby
# frozen_string_literal: true
#
# scaffold_fill.rb - generate a fill.rb skeleton from an extracted TSV.
#
#   ruby tools/scaffold_fill.rb archetypes/<id>/<id>.tsv > archetypes/<id>/fill.rb
#
# The skeleton lists every (section, code, field) key with the English source
# as a comment and an empty target string.  The translator (human or agent)
# fills in the strings; keys whose source is 'Tree', '@ internal @', 'Extension'
# or '© openEHR Foundation...' are pre-filled per glossary-ja.md.

require 'json'

tsv = ARGV[0] or abort 'usage: scaffold_fill.rb TSV'
rows = File.readlines(tsv, chomp: true)[1..].map { |l| l.split("\t", -1) }
id = rows.first[0]

PREFILL = lambda do |field, src|
  return src if src == 'Tree' || src == '@ internal @' || src == 'Extension'
  return src if field == 'copyright'
  nil
end

puts "# frozen_string_literal: true"
puts "# Japanese translation for #{id}"
puts "# Generated by tools/scaffold_fill.rb - fill every empty string, following glossary-ja.md."
puts
puts 'T = {'
rows.each do |r|
  _id, section, code, field, context, source = r
  key = "['#{section}', '#{code}', '#{field}']"
  src_c = source.gsub('\n', "\n").lines.map { |l| "  # #{l.chomp}" }.join("\n")
  puts "  # #{context}" unless context.to_s.empty?
  puts src_c
  pre = PREFILL.call(field, source)
  puts "  #{key} => #{pre ? pre.to_json : "''"},"
  puts
end
puts '}.freeze'
puts
puts "# note 列に残すメモ。迷った訳語には '要確認: ...' を付ける。"
puts 'NOTES = {'
puts "  # ['term', 'at0000', 'text'] => '要確認: ...',"
puts '}.freeze'
puts
puts <<~'RUBY'
  src, dst = ARGV
  lines = File.readlines(src, chomp: true)
  out = [lines.shift]
  lines.each do |l|
    c = l.split("\t", -1)
    key = c[1..3]
    c[6] = T.fetch(key).gsub("\n", '\n')
    c[7] = NOTES[key] || ''
    out << c.join("\t")
  end
  File.write(dst, out.join("\n") + "\n")
RUBY
