#!/usr/bin/env ruby
# frozen_string_literal: true
#
# scaffold_fill.rb - generate work/fill.rb from a TSV.
#
#   ruby tools/scaffold_fill.rb archetypes/<id>/work/<id>.tsv    > archetypes/<id>/work/fill.rb   # skeleton (make new)
#   ruby tools/scaffold_fill.rb archetypes/<id>/work/<id>.ja.tsv > archetypes/<id>/work/fill.rb   # import (make import)
#
# The output lists every (section, code, field) key with the English source as
# a comment and the target string.  With the extracted TSV (empty target column)
# the targets are empty strings for the translator (human or agent) to fill in;
# keys whose source is 'Tree', '@ internal @', 'Extension' or '© openEHR
# Foundation...' are pre-filled per glossary-ja.md.  With a filled TSV
# (work/<id>.ja.tsv, e.g. after a human proofread it in place) the target and
# note columns are carried over, so `make import` turns the edited TSV back into
# fill.rb and `make build` reproduces the same TSV from it (round trip).

tsv = ARGV[0] or abort 'usage: scaffold_fill.rb TSV'
lines = File.readlines(tsv, chomp: true, encoding: 'bom|utf-8').reject { |l| l.strip.empty? }
header = lines.shift.split("\t", -1)
abort "#{tsv}: not an adl_i18n TSV (header #{header.first.inspect})" unless header.first == 'archetype'
rows = lines.each_with_index.map do |l, i|
  c = l.chomp("\r").split("\t", -1)
  abort "#{tsv}:#{i + 2}: expected #{header.size} columns, got #{c.size} (tabs inside a field? use a space)" if c.size != header.size
  c
end
abort "#{tsv}: no rows" if rows.empty?
id = rows.first[0]

PREFILL = lambda do |field, src|
  return src if src == 'Tree' || src == '@ internal @' || src == 'Extension'
  return src if field == 'copyright'
  nil
end
unescape = ->(s) { s.to_s.gsub('\n', "\n") }

puts "# frozen_string_literal: true"
puts "# Japanese translation for #{id}"
puts "# Generated by tools/scaffold_fill.rb - fill every empty string, following glossary-ja.md."
puts "# Human proofreading: edit work/#{id}.ja.tsv and run `make import ID=#{id}` (regenerates this file)."
puts
puts 'T = {'
notes = []
rows.each do |r|
  _id, section, code, field, context, source, target, note = r
  key = "['#{section}', '#{code}', '#{field}']"
  src_c = unescape.call(source).lines.map { |l| "  # #{l.chomp}" }.join("\n")
  puts "  # #{context}" unless context.to_s.empty?
  puts src_c
  val = target.to_s.empty? ? PREFILL.call(field, source) : unescape.call(target)
  puts "  #{key} => #{val ? val.inspect : "''"},"
  puts
  notes << [key, note] unless note.to_s.empty?
end
puts '}.freeze'
puts
puts "# note 列に残すメモ。迷った訳語には '要確認: ...' を付ける。"
puts 'NOTES = {'
puts "  # ['term', 'at0000', 'text'] => '要確認: ...'," if notes.empty?
notes.each { |key, note| puts "  #{key} => #{note.inspect}," }
puts '}.freeze'
puts
puts <<~'RUBY'
  src, dst = ARGV
  lines = File.readlines(src, chomp: true)
  out = [lines.shift]
  lines.each do |l|
    c = l.split("\t", -1)
    key = c[1..3]
    c[6] = T.fetch(key).gsub("\n", '\n')
    c[7] = NOTES[key] || ''
    out << c.join("\t")
  end
  File.write(dst, out.join("\n") + "\n")
RUBY
