# frozen_string_literal: true
# Japanese translation for openEHR-EHR-OBSERVATION.body_weight.v2
# Generated by tools/scaffold_fill.rb - fill every empty string, following glossary-ja.md.
# Human proofreading: edit work/openEHR-EHR-OBSERVATION.body_weight.v2.ja.tsv and run `make import ID=openEHR-EHR-OBSERVATION.body_weight.v2` (regenerates this file).

T = {
  # To record the body weight of an individual - both actual and approximate.
  ['description', '-', 'purpose'] => "個人の体重を記録するため。実測値あるいはおおよその値として。",

  # To be used for recording the actual measurement of body weight, including when the individual is missing a body part due to a congenital cause or after surgical removal.   A statement identifying the physical incompleteness of the body can be recorded in the 'Confounding factors' data element, if required. This is the usual archetype to be used for a typical measurement of weight, for example self-measured by the individual at home, a clinician measurement in a clinic/hospital, or a fitness instructor in a gymnasium.  
  # 
  # Can also be used for recording an approximation of body weight measurement in a clinical scenario where it is not possible to measure accurately body weight - for example, weighing an uncooperative child, or estimating the weight of an unborn fetus (where the 'subject of data' is the Fetus and recording occurs within the mother's health record).  This is not modelled explicitly in the archetype as the openEHR Reference model allows approximations  for any Quantity data type by setting the attribute Magnitude_status to the value '~'.  At implementation, for example, an application user interface could allow clinicians to select an appropriately labelled check box adjacent to the Weight data field to indicate that the recorded weight is an approximation, rather than actual.
  # 
  # To be used for recording weight change, that is, either weight loss or weight gain.  This can currently be modelled by constraining the 'any event' to an interval with associated mathematical function of increase or decrease, as appropriate.
  ['description', '-', 'use'] => "身体の一部を先天的な理由あるいは外科的に切除していることにより欠損している場合を含めて、実測した体重を記録するために使われる。必要であれば身体の一部を物理的に欠損している状態は、「交絡因子」(confounding factor)データエレメントに指定される。これは一般的な体重測定のために使われるアーキタイプであり、たとえば個人の家庭で自己測定された体重や、クリニックや病院で臨床スタッフにより計測されたものあるいは、ジムでフィットネスインストラクタにより測定されたものである。\n\nまた、正確な体重測定が不可能であると臨床上想定される場面において、体重を概算して記録するときにも利用される。たとえば、非協力的な子供の体重測定や、未出産の胎児の体重を見積もるような場合である。（胎児体重を見積もる場合、「データの対象」(subject of data)は「胎児」(Fetus)であり、母親の健康を記録するときに同時に記録される。）このアーキタイプでは、openEHRの参照モデルが量(Quantity)を表すデータ型に概算であることを示す属性を明示するようにはモデリングされていない。実装する場合には、たとえばアプリケーションのユーザーインターフェースが臨床スタッフに実測したデータでは無く概算であると言うことを明示的に記録できるようなチェックボックスを用意して、体重データフィールドに記録するようにしておくこともできる。\n\n体重変化、つまり体重が増加しているか減少しているかを記録するために利用することもできる。これについては、現在では「任意のイベント」(any event)による制約を適切な間隔で制約して、数学的に足したり引いたりすることができるようにモデリングされている。",

  # Not to be used to record a calculated body weight, such as an estimation of the body weight of a person with one or more limbs missing. A calculated body weight may be based on, some or all of, the measured body weight, other body measurements and an algorithm. Use other OBSERVATION archetypes for this purpose.
  # 
  # Not to be used to record the weight of a body part or other object.
  ['description', '-', 'misuse'] => "新生児が生まれた直後に最初にはかる体重、つまり新生児の「生下時体重」(birth weight)を記録するためには設計されていない。生下時体重の記録にはこのアーキタイプを特殊化したOBSERVATION.body_weight-birthアーキタイプを利用すること。\n調整された体重、たとえば四肢を切断した人の全体重を身体の他の部位を計測して、一定のアルゴリズムに基づいて計算するような場合にも用いられない。その場合には、OBSERVATION.body_weight-adjustedを用いること。\nそのほかの物体や体の一部の重さを記録するためにも用いられない。",

  # weight | gain | loss | increase | decrease | mass | estimate | actual
  ['description', '-', 'keywords'] => "重量 | 増量 | 減量 | 増加 | 減少 | 質量 | 推定値 | 実測値",

  # © openEHR Foundation
  ['description', '-', 'copyright'] => "© openEHR Foundation",

  # OBSERVATION
  # Body weight
  ['term', 'at0000', 'text'] => "体重",

  # OBSERVATION
  # Measurement of the body weight of an individual.
  ['term', 'at0000', 'description'] => "個人の体重を測定したもの",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE
  # Simple
  ['term', 'at0001', 'text'] => "Simple",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE
  # @ internal @
  ['term', 'at0001', 'description'] => "@ internal @",

  # OBSERVATION > data/HISTORY
  # history
  ['term', 'at0002', 'text'] => "history",

  # OBSERVATION > data/HISTORY
  # @ internal @
  ['term', 'at0002', 'description'] => "@ internal @",

  # OBSERVATION > data/HISTORY > events/EVENT
  # Any event
  ['term', 'at0003', 'text'] => "任意のイベント",

  # OBSERVATION > data/HISTORY > events/EVENT
  # Default, unspecified point in time or interval event which may be explicitly defined in a template or at run-time.
  ['term', 'at0003', 'description'] => "デフォルトではテンプレートや実行時に明示的に定義される特定されていない時点あるいは間隔でのイベント",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE > items/ELEMENT
  # Weight
  ['term', 'at0004', 'text'] => "重量",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE > items/ELEMENT
  # The weight of the individual.
  ['term', 'at0004', 'description'] => "個人の重量",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE
  # state structure
  ['term', 'at0008', 'text'] => "state structure",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE
  # @ internal @
  ['term', 'at0008', 'description'] => "@ internal @",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE > items/ELEMENT
  # State of dress
  ['term', 'at0009', 'text'] => "着衣状態",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE > items/ELEMENT
  # Description of the state of dress of the person at the time of weighing.
  ['term', 'at0009', 'description'] => "体重測定時の着衣状態についての記述￥",

  # Fully clothed, including shoes
  ['term', 'at0010', 'text'] => "靴も履いている着衣状態",

  # Clothing which may add significantly to weight, including shoes.
  ['term', 'at0010', 'description'] => "靴を含めて、体重測定に大きく関与するような着衣状態",

  # Lightly clothed/underwear
  ['term', 'at0011', 'text'] => "軽装／下着",

  # Clothing which will not add to weight significantly.
  ['term', 'at0011', 'description'] => "体重測定にあまり寄与しない着衣",

  # Naked
  ['term', 'at0013', 'text'] => "全裸",

  # Without any clothes.
  ['term', 'at0013', 'description'] => "何も着衣していない",

  # OBSERVATION > protocol/ITEM_TREE
  # protocol structure
  ['term', 'at0015', 'text'] => "protocol structure",

  # OBSERVATION > protocol/ITEM_TREE
  # @ internal @
  ['term', 'at0015', 'description'] => "@ internal @",

  # Nappy/diaper
  ['term', 'at0017', 'text'] => "おむつを付けている状態",

  # Wearing only a nappy - which may add significantly to weight.
  ['term', 'at0017', 'description'] => "おむつだけをはいている状態。体重測定に関与しうる。",

  # OBSERVATION > protocol/ITEM_TREE > items/CLUSTER
  # Device
  ['term', 'at0020', 'text'] => "測定機器",

  # OBSERVATION > protocol/ITEM_TREE > items/CLUSTER
  # Details about the weighing device.
  ['term', 'at0020', 'description'] => "測定に使用された機器についての詳細な記録",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE > items/ELEMENT
  # Comment
  ['term', 'at0024', 'text'] => "コメント",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE > items/ELEMENT
  # Additional narrative about the measurement of Body weight, not captured in other fields.
  ['term', 'at0024', 'description'] => "他のフィールドには記載されない体重の計測についての叙述的記録",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE > items/ELEMENT
  # Confounding factors
  ['term', 'at0025', 'text'] => "交絡因子",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE > items/ELEMENT
  # Record any issues or factors that may impact on the measurement of body weight eg timing in menstrual cycle, timing of recent bowel motion or noting of amputation.
  ['term', 'at0025', 'description'] => "体重計測に影響を与えうるすべての要素や問題。例えば、月経周期や直近の排便時、四肢切断の有無。",

  # OBSERVATION > data/HISTORY > events/POINT_EVENT
  # Birth
  ['term', 'at0026', 'text'] => "生下時",

  # OBSERVATION > data/HISTORY > events/POINT_EVENT
  # Usually the first weight, measured soon after birth. This event will only be used once per health record
  # .
  ['term', 'at0026', 'description'] => "一般的には誕生後最初に計測される体重。このイベントは一生に1回だけ記録される。",

  # OBSERVATION > protocol/ITEM_TREE > items/CLUSTER
  # Extension
  ['term', 'at0027', 'text'] => "拡張領域",

  # OBSERVATION > protocol/ITEM_TREE > items/CLUSTER
  # Additional information required to capture local content or to align with other reference models/formalisms.
  ['term', 'at0027', 'description'] => "ローカルの内容や他の参照モデル、形式に割り当ててデータを取得する追加情報",

  # OBSERVATION > protocol/ITEM_TREE > items/CLUSTER
  # For example: local information requirements or additional metadata to align with FHIR or CIMI equivalents.
  ['term', 'at0027', 'comment'] => "例えば、FHIRやCIMIと同等に割り当てられるメタデータやローカルの情報要件",

  # Fully clothed, without shoes
  ['term', 'at0028', 'text'] => "靴を脱いだ着衣状態",

  # Clothing which may add significantly to weight.
  ['term', 'at0028', 'description'] => "体重計測に影響を与えうる着衣状態",

}.freeze

# note 列に残すメモ。迷った訳語には '要確認: ...' を付ける。
NOTES = {
  ['term', 'at0001', 'text'] => "内部の構造ノード名（Simple / history / state structure / protocol structure）は文体規則により英字のまま。placeholder の *…(en) を外しただけ。",
  # ['term', 'at0000', 'text'] => '要確認: ...',
}.freeze

src, dst = ARGV
lines = File.readlines(src, chomp: true)
out = [lines.shift]
lines.each do |l|
  c = l.split("\t", -1)
  key = c[1..3]
  c[6] = T.fetch(key).gsub("\n", '\n')
  c[7] = NOTES[key] || ''
  out << c.join("\t")
end
File.write(dst, out.join("\n") + "\n")
