# frozen_string_literal: true
# Japanese translation for openEHR-EHR-OBSERVATION.blood_pressure.v2
# Generated by tools/scaffold_fill.rb - fill every empty string, following glossary-ja.md.
# Human proofreading: edit work/openEHR-EHR-OBSERVATION.blood_pressure.v2.ja.tsv and run `make import ID=openEHR-EHR-OBSERVATION.blood_pressure.v2` (regenerates this file).

T = {
  # To record the systemic arterial blood pressure of an individual.
  ['description', '-', 'purpose'] => "個々人の全身における動脈血圧を記録するためのもの。",

  # Use to record all representations of systemic arterial blood pressure measurement, no matter which method or body location is used to record it. 
  # 
  # The archetype is intended to capture blood pressure measurements in all clinical scenarios - for example:
  # - self-measurement with a home blood pressure machine; 
  # - an emergency assessment of systolic using palpation and a sphygmomanometer; 
  # - measurements taken in clinical consultations or during exercise stress testing; and 
  # - a series of measurements made by a machine in Intensive Care.   
  # 
  # There is a rich state model that supports interpretation of measurements through identifying patient position, exercise, confounding factors and angle of a tilt table in research. 
  # 
  # Named events have been limited to average over a 24 hour period, however templates can further constrain the default 'any event' to cater for specific requirements for blood pressure measurements such as recording Blood Pressure against specific points in time, or over a range of intervals (+/- mathematical functions).
  ['description', '-', 'use'] => "測定方法や身体部位を問わず、すべての血圧についての表現を記録するために使用される。このアーキタイプはすべての臨床シナリオを網羅することを目指している。以下に例を挙げる。\n- 家庭用血圧計で自己測定した血圧\n- 緊急時の評価として触診法により血圧計で測定された収縮期圧\n- 臨床上のコンサルテーションや運動負荷テストの間に測定されたもの\n- 集中治療において機械的に計測された一連の血圧などである。\n患者の体位や運動負荷、交絡因子やティルト台の角度など識別することにより、研究にて計測状態の解釈を手助けする豊富なステートモデルもある。\n24時間平均血圧だけが特定のイベントとして名前がつけられているが、テンプレートではデフォルトの「任意のイベント」にさらなる制約を加えることで、特定の時間や間隔を指定したり（数学的機能を追加したり、削除して）、血圧を記録するように、血圧測定に対する特定の要求を行ったイベントを指定することができる。",

  # Not to be used to record the measurement of arterial blood pressure which is NOT a surrogate for arterial pressure in the systemic circulation eg specific measurement of right pulmonary artery pressure. Use OBSERVATION.intravascular_pressure in this situation.  
  # 
  # Not to be used to record measurements of intravenous pressure. Use the appropriate specialisations of OBSERVATION.intravascular_pressure in this situation.
  ['description', '-', 'misuse'] => "全身循環を表す指標としての代わりとならない特定の動脈血圧、たとえば右肺動脈の血圧測定には用いない。このような場合には、OBSERVATION.intravascular_pressureを利用すること。\n血管内圧の測定には用いられない。このような場合には、適切に特殊化されたOBSERVATION.intravascular_pressureを利用すること",

  # observations | measurement | bp | vital signs | mean arterial pressure | pulse pressure | systolic | diastolic | RR | NIBP
  ['description', '-', 'keywords'] => "観察 | 測定 | 血圧 | バイタルサイン | 平均動脈圧 | 脈圧 | 収縮期 | 拡張期 | RR間隔 | 非観血血圧",

  # © openEHR Foundation
  ['description', '-', 'copyright'] => "© openEHR Foundation",

  # OBSERVATION
  # Blood pressure
  ['term', 'at0000', 'text'] => "血圧",

  # OBSERVATION
  # The local measurement of arterial blood pressure which is a surrogate for arterial pressure in the systemic circulation.
  ['term', 'at0000', 'description'] => "全身を循環する動脈圧の指標として，局所で測定される血圧。一般的には「血圧」とは上腕で上腕動脈圧を測定したものをさすことが多い。",

  # OBSERVATION
  # Most commonly, use of the term 'blood pressure' refers to measurement of brachial artery pressure in the upper arm.
  ['term', 'at0000', 'comment'] => "ごく一般的には「血圧」という用語は上腕で計測される上腕動脈の圧を示している。",

  # OBSERVATION > data/HISTORY
  # History
  ['term', 'at0001', 'text'] => "履歴",

  # OBSERVATION > data/HISTORY
  # History Structural node.
  ['term', 'at0001', 'description'] => "履歴構造ノード",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE
  # blood pressure
  ['term', 'at0003', 'text'] => "血圧",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE
  # @ internal @
  ['term', 'at0003', 'description'] => "@ internal @",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE > items/ELEMENT
  # Systolic
  ['term', 'at0004', 'text'] => "収縮期",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE > items/ELEMENT
  # Peak systemic arterial blood pressure  - measured in systolic or contraction phase of the heart cycle.
  ['term', 'at0004', 'description'] => "全身の動脈血圧での最高値 - 心機図の収縮期で測定される",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE > items/ELEMENT
  # Diastolic
  ['term', 'at0005', 'text'] => "拡張期",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE > items/ELEMENT
  # Minimum systemic arterial blood pressure - measured in the diastolic or relaxation phase of the heart cycle.
  ['term', 'at0005', 'description'] => "全身の動脈血圧での最低値 - 心機図の拡張期で測定される",

  # OBSERVATION > data/HISTORY > events/EVENT
  # Any event
  ['term', 'at0006', 'text'] => "任意のイベント",

  # OBSERVATION > data/HISTORY > events/EVENT
  # Default, unspecified point in time or interval event which may be explicitly defined in a template or at run-time.
  ['term', 'at0006', 'description'] => "デフォルトで、テンプレートや実行時に明示的に定義されていない任意の時点や間隔を示す。",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE
  # state structure
  ['term', 'at0007', 'text'] => "state structure",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE
  # @ internal @
  ['term', 'at0007', 'description'] => "@ internal @",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE > items/ELEMENT
  # Position
  ['term', 'at0008', 'text'] => "体位",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE > items/ELEMENT
  # The position of the individual at the time of measurement.
  ['term', 'at0008', 'description'] => "測定時の対象者の体位",

  # OBSERVATION > protocol/ITEM_TREE
  # Tree
  ['term', 'at0011', 'text'] => "ツリー",

  # OBSERVATION > protocol/ITEM_TREE
  # List structure.
  ['term', 'at0011', 'description'] => "リスト構造",

  # OBSERVATION > protocol/ITEM_TREE > items/ELEMENT
  # Cuff size
  ['term', 'at0013', 'text'] => "カフサイズ",

  # OBSERVATION > protocol/ITEM_TREE > items/ELEMENT
  # The size of the cuff used for blood pressure measurement.
  ['term', 'at0013', 'description'] => "血圧測定のために使われるカフの大きさ.",

  # OBSERVATION > protocol/ITEM_TREE > items/ELEMENT
  # Perloff D, Grim C, Flack J, Frohlich ED, Hill M, McDonald M, Morgenstern BZ. Human blood pressure determination by sphygmomanometry. Circulation 1993;88;2460-2470. 
  ['term', 'at0013', 'comment'] => "Perloff D, Grim C, Flack J, Frohlich ED, Hill M, McDonald M, Morgenstern BZ. Human blood pressure determination by sphygmomanometry. Circulation 1993;88;2460-2470.",

  # OBSERVATION > protocol/ITEM_TREE > items/ELEMENT
  # Location of measurement
  ['term', 'at0014', 'text'] => "測定部位",

  # OBSERVATION > protocol/ITEM_TREE > items/ELEMENT
  # Simple body site where blood pressure was measured.
  ['term', 'at0014', 'description'] => "血圧が測定された一つの身体部位",

  # Adult Thigh
  ['term', 'at0015', 'text'] => "成人大腿",

  # A cuff used for an adult thigh.
  ['term', 'at0015', 'description'] => "成人の大腿で血圧を測定するためのカフ。",

  # Large Adult
  ['term', 'at0016', 'text'] => "大柄な成人",

  # A cuff for adults with larger arms.
  ['term', 'at0016', 'description'] => "大柄な成人の腕で測定するためのカフ。",

  # Adult
  ['term', 'at0017', 'text'] => "成人",

  # A cuff that is standard for an adult.
  ['term', 'at0017', 'description'] => "一般成人のためのカフ",

  # Right arm
  ['term', 'at0025', 'text'] => "右腕",

  # The right arm of the person.
  ['term', 'at0025', 'description'] => "測定対象者の右腕",

  # Left arm
  ['term', 'at0026', 'text'] => "左腕",

  # The left arm of the person.
  ['term', 'at0026', 'description'] => "測定対象者の左腕",

  # Right thigh
  ['term', 'at0027', 'text'] => "右大腿",

  # The right thigh of the person.
  ['term', 'at0027', 'description'] => "測定対象者の右大腿",

  # Left thigh
  ['term', 'at0028', 'text'] => "左大腿",

  # The left thigh of the person.
  ['term', 'at0028', 'description'] => "測定対象者の左大腿",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE > items/ELEMENT
  # Comment
  ['term', 'at0033', 'text'] => "コメント",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE > items/ELEMENT
  # Additional narrative about the measurement, not captured in other fields.
  ['term', 'at0033', 'description'] => "この計測について他に項目に該当しない追加記録",

  # Standing
  ['term', 'at1000', 'text'] => "立位",

  # Standing at the time of blood pressure measurement.
  ['term', 'at1000', 'description'] => "血圧測定時に立位",

  # Sitting
  ['term', 'at1001', 'text'] => "座位",

  # Sitting (for example on bed or chair) at the time of blood pressure measurement.
  ['term', 'at1001', 'description'] => "血圧測定時に（たとえば、ベッドやイスの上で）坐位",

  # Reclining
  ['term', 'at1002', 'text'] => "斜位",

  # Reclining at the time of blood pressure measurement.
  ['term', 'at1002', 'description'] => "血圧測定時に斜位",

  # Lying
  ['term', 'at1003', 'text'] => "臥位",

  # Lying flat at the time of blood pressure measurement.
  ['term', 'at1003', 'description'] => "血圧測定時に臥位",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE > items/ELEMENT
  # Tilt
  ['term', 'at1005', 'text'] => "ティルト",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE > items/ELEMENT
  # The craniocaudal tilt of the surface on which the person is lying at the time of measurement.
  ['term', 'at1005', 'description'] => "測定時に対象者が臥床している台の頭尾方向の傾き",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE > items/ELEMENT
  # Mean arterial pressure
  ['term', 'at1006', 'text'] => "平均動脈圧",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE > items/ELEMENT
  # The average arterial pressure that occurs over the entire course of the heart contraction and relaxation cycle.
  ['term', 'at1006', 'description'] => "心臓の収縮拡張サイクルのすべての過程を通した動脈血圧の平均値.",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE > items/ELEMENT
  # Pulse pressure
  ['term', 'at1007', 'text'] => "脈圧",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE > items/ELEMENT
  # The difference between the systolic and diastolic pressure.
  ['term', 'at1007', 'description'] => "1回の収縮サイクルでの血圧の変動",

  # Small Adult
  ['term', 'at1008', 'text'] => "小柄な成人",

  # A cuff used for a small adult.
  ['term', 'at1008', 'description'] => "小柄な成人のためのカフ",

  # Paediatric/Child
  ['term', 'at1009', 'text'] => "幼児/小児",

  # A cuff that is appropriate for a child or adult with a thin arm.
  ['term', 'at1009', 'description'] => "小児あるいは痩せた成人のためのカフ",

  # OBSERVATION > protocol/ITEM_TREE > items/ELEMENT
  # Diastolic endpoint
  ['term', 'at1010', 'text'] => "拡張期終末",

  # OBSERVATION > protocol/ITEM_TREE > items/ELEMENT
  # Record which Korotkoff sound is used for determining diastolic pressure using auscultative method.
  ['term', 'at1010', 'description'] => "拡張期圧を決めるためにどのコロトコフ音が使用されたかについて記録.",

  # Phase IV
  ['term', 'at1011', 'text'] => "4期",

  # The fourth Korotkoff sound is identified as an abrupt muffling of sounds.
  ['term', 'at1011', 'description'] => "コロトコフの4音。急速に減弱する時期.",

  # Phase V
  ['term', 'at1012', 'text'] => "5期",

  # The fifth Korotkoff sound is identified by absence of sounds as the cuff pressure drops below the diastolic blood pressure.
  ['term', 'at1012', 'description'] => "コロトコフの5音が聴取される時期。カフ圧が拡張期圧を下回り音が聴取されなくなる時期",

  # Lying with tilt to left
  ['term', 'at1014', 'text'] => "左側臥位",

  # Lying flat with some lateral tilt, usually angled towards the left side.   Commonly required in the last trimester of pregnancy to relieve aortocaval compression.
  ['term', 'at1014', 'description'] => "通常は頭から足までを水平にしてから左側に傾けられた状態。一般的には妊娠の第3トリメスターで大動脈・静脈を圧排から解放するために求められる体位である。",

  # Infant
  ['term', 'at1018', 'text'] => "幼児",

  # A cuff used for infants.
  ['term', 'at1018', 'description'] => "幼児のために使われるカフ",

  # Neonatal
  ['term', 'at1019', 'text'] => "新生児",

  # A cuff used for a neonate, assuming cuff is the appropriate size for maturity and birthweight of the neonate.
  ['term', 'at1019', 'description'] => "新生児用のカフ 想定されるカフは新生児の生下時体重と成熟度に応じて適切なものであること.",

  # Right wrist
  ['term', 'at1020', 'text'] => "右手首",

  # The right wrist of the individual.
  ['term', 'at1020', 'description'] => "測定対象者の右手首",

  # Left wrist
  ['term', 'at1021', 'text'] => "左手首",

  # The left wrist of the individual.
  ['term', 'at1021', 'description'] => "測定対象者の左手首",

  # OBSERVATION > protocol/ITEM_TREE > items/CLUSTER
  # Device
  ['term', 'at1025', 'text'] => "測定機器",

  # OBSERVATION > protocol/ITEM_TREE > items/CLUSTER
  # Details about sphygmomanometer or other device used to measure the blood pressure.
  ['term', 'at1025', 'description'] => "水銀血圧計あるいはそのほかの血圧を測定するために使われる機器.",

  # Right ankle
  ['term', 'at1026', 'text'] => "右足首",

  # The right ankle of the individual.
  ['term', 'at1026', 'description'] => "測定対象者の右足首",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE > items/CLUSTER
  # Exertion
  ['term', 'at1030', 'text'] => "労作",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE > items/CLUSTER
  # Details about physical activity undertaken at the time of blood pressure measurement.
  ['term', 'at1030', 'description'] => "血圧測定時に行われた肉体的運動についての詳細。",

  # Left ankle
  ['term', 'at1031', 'text'] => "左足首",

  # The left ankle of the individual.
  ['term', 'at1031', 'description'] => "測定対象者の左足首",

  # Finger
  ['term', 'at1032', 'text'] => "手指",

  # A finger of the individual.
  ['term', 'at1032', 'description'] => "測定対象者の手指",

  # OBSERVATION > protocol/ITEM_TREE > items/ELEMENT
  # Method
  ['term', 'at1035', 'text'] => "方法",

  # OBSERVATION > protocol/ITEM_TREE > items/ELEMENT
  # Method of measurement of blood pressure.
  ['term', 'at1035', 'description'] => "血圧の測方法。",

  # Auscultation
  ['term', 'at1036', 'text'] => "聴診",

  # Method of measuring blood pressure externally, using a stethoscope and Korotkoff sounds.
  ['term', 'at1036', 'description'] => "聴診器を使いコロトコフ音で外部から血圧を測定する方法.",

  # Palpation
  ['term', 'at1037', 'text'] => "触診",

  # Method of measuring blood pressure externally, using palpation (usually of the brachial or radial arteries).
  ['term', 'at1037', 'description'] => "脈拍(通常は上腕動脈あるいは橈骨動脈）を触診することにより外部から血圧を測定する方法",

  # OBSERVATION > protocol/ITEM_TREE > items/ELEMENT
  # Mean arterial pressure formula
  ['term', 'at1038', 'text'] => "平均動脈圧の計算式",

  # OBSERVATION > protocol/ITEM_TREE > items/ELEMENT
  # Formula used to calculate the Mean Arterial Pressure (if recorded in data).
  ['term', 'at1038', 'description'] => "平均動脈圧を計算するために使われた式（もしデータに記録されていれば）",

  # Machine
  ['term', 'at1039', 'text'] => "機械",

  # Method of measuring blood pressure externally, using a blood pressure machine.
  ['term', 'at1039', 'description'] => "血圧測定器を使って外部から血圧を測定する方法.",

  # Invasive
  ['term', 'at1040', 'text'] => "侵襲的",

  # Method of measuring blood pressure internally ie involving penetration of the skin and measuring inside blood vessels.
  ['term', 'at1040', 'description'] => "経皮的に動脈を穿刺し，血管内部から血圧を測定する方法.",

  # OBSERVATION > data/HISTORY > events/INTERVAL_EVENT
  # 24 hour average
  ['term', 'at1042', 'text'] => "24時間平均",

  # OBSERVATION > data/HISTORY > events/INTERVAL_EVENT
  # Estimate of the average blood pressure over a 24 hour period.
  ['term', 'at1042', 'description'] => "24時間での推定平均血圧",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE > items/ELEMENT
  # Sleep status
  ['term', 'at1043', 'text'] => "睡眠状況",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE > items/ELEMENT
  # Sleep status - supports interpretation of 24 hour ambulatory blood pressure records.
  ['term', 'at1043', 'description'] => "睡眠状況 24時間外来血圧記録の解釈を助けるため",

  # Awake
  ['term', 'at1044', 'text'] => "覚醒",

  # The individual is fully conscious.
  ['term', 'at1044', 'description'] => "対象の意識は清明である。",

  # Sleeping
  ['term', 'at1045', 'text'] => "睡眠中",

  # The individual is in the natural state of bodily rest.
  ['term', 'at1045', 'description'] => "対象は自然な入眠状態にある",

  # Toe
  ['term', 'at1051', 'text'] => "足尖",

  # A toe of the individual.
  ['term', 'at1051', 'description'] => "対象者の足尖部",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE > items/ELEMENT
  # Confounding factors
  ['term', 'at1052', 'text'] => "交絡因子",

  # OBSERVATION > data/HISTORY > events/EVENT > state/ITEM_TREE > items/ELEMENT
  # Comment on and record other incidental factors that may be contributing to the blood pressure measurement.  For example, level of anxiety or 'white coat syndrome'; pain or fever; changes in atmospheric pressure etc.
  ['term', 'at1052', 'description'] => "血圧測定に寄与しうるその他の偶発的な要素についてのコメント。たとえば、不安の程度や「白衣性高血圧」、痛みや発熱、大気圧の変化など。",

  # Intra-arterial
  ['term', 'at1053', 'text'] => "動脈内",

  # Invasive measurement via transducer access line within an artery.
  ['term', 'at1053', 'description'] => "動脈内に観血的方法で留置したトランスデューサからAラインを経由して測定",

  # OBSERVATION > protocol/ITEM_TREE > items/ELEMENT
  # Systolic pressure formula
  ['term', 'at1054', 'text'] => "収縮期圧計算式",

  # OBSERVATION > protocol/ITEM_TREE > items/ELEMENT
  # Formula used to calculate the systolic pressure from from mean arterial pressure (if recorded in data).
  ['term', 'at1054', 'description'] => "（もしデータが記録されていれば）平均動脈圧から収縮期血圧を計算した式",

  # OBSERVATION > protocol/ITEM_TREE > items/ELEMENT
  # Diastolic pressure formula
  ['term', 'at1055', 'text'] => "拡張期圧計算式",

  # OBSERVATION > protocol/ITEM_TREE > items/ELEMENT
  # Formula used to calculate the diastolic pressure from mean arterial pressure (if recorded in data).
  ['term', 'at1055', 'description'] => "平均動脈圧から拡張期血圧を計算するために使われた式（もしデータに記録されていれば）",

  # Dorsum of foot
  ['term', 'at1056', 'text'] => "足背",

  # The individual's dorsum of the foot.
  ['term', 'at1056', 'description'] => "対象者の足背",

  # OBSERVATION > protocol/ITEM_TREE > items/CLUSTER
  # Structured measurement location
  ['term', 'at1057', 'text'] => "構造化された測定部位",

  # OBSERVATION > protocol/ITEM_TREE > items/CLUSTER
  # Structured anatomical location of where the measurement was taken.
  ['term', 'at1057', 'description'] => "測定が行われた部位の解剖学的位置について構造化された表現",

  # OBSERVATION > protocol/ITEM_TREE > items/CLUSTER
  # Extension
  ['term', 'at1058', 'text'] => "拡張領域",

  # OBSERVATION > protocol/ITEM_TREE > items/CLUSTER
  # Additional information required to capture local context or to align with other reference models/formalisms.
  ['term', 'at1058', 'description'] => "測定時の背景を収集したり、その他の参照モデルや形式と連携するために必要となる追加情報",

  # OBSERVATION > protocol/ITEM_TREE > items/CLUSTER
  # For example: Local hospital departmental infomation or additional metadata to align with FHIR or CIMI equivalents.
  ['term', 'at1058', 'comment'] => "例：FHIRやCIMIなどと連携するために病院内で独自に追加して利用されるメターデータ。",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE > items/ELEMENT
  # Clinical interpretation
  ['term', 'at1059', 'text'] => "臨床的解釈",

  # OBSERVATION > data/HISTORY > events/EVENT > data/ITEM_TREE > items/ELEMENT
  # Single word, phrase or brief description that represents the clinical meaning and significance of the blood pressure measurement.
  ['term', 'at1059', 'description'] => "血圧測定の臨床的意義や重要性についての一言あるいは一文の簡潔な表現。",

}.freeze

# note 列に残すメモ。迷った訳語には '要確認: ...' を付ける。
NOTES = {
  ['term', 'at0007', 'text'] => "内部の構造ノード名は文体規則により英字のまま。placeholder の *…(en) を外しただけ。",
}.freeze

src, dst = ARGV
lines = File.readlines(src, chomp: true)
out = [lines.shift]
lines.each do |l|
  c = l.split("\t", -1)
  key = c[1..3]
  c[6] = T.fetch(key).gsub("\n", '\n')
  c[7] = NOTES[key] || ''
  out << c.join("\t")
end
File.write(dst, out.join("\n") + "\n")
